### ISSUE TITLE
Group nodes without links

### ISSUE THREAD

**Issue by Benkevych** [vasturiano/react-force-graph#1]
Can i somehow connect couple of nodes in 1 group but without visible links?

**Comment by vasturiano** [comment]
There's probably different ways to achieve that, depending on what your intention is.
If it's just a visual difference and you simply wish to hide certain links, you can do that by setting a fully transparent color on those links. Something like:
```
linkColor={link => shouldHideLink(link) ? 'rgba(0, 0, 0, 0)' : link.color}
```

If however you wish to group nodes in another manner than not by the `link` force (or by configuring the `link` force in a different way) you can manipulate the internals of the forces in play in the system using the `d3Force` method.

**Comment by Benkevych** [comment]
i`ve tried that, and my links appear just black instead of transparent...

**Comment by vasturiano** [comment]
Seems like it's ignoring the alpha part. Are you using `rgba`? Also, are you running the latest version of `react-force-graph`?

**Comment by Benkevych** [comment]
I don`t know what was the issue, but everything works fine after reinstalling package. Both was latest versions...
Thank you for your time)
