### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by gummybear1202** [vasturiano/react-force-graph#10]
I tried npm i react-force-graph and kept hitting the same error:

```
warning: templates not found C:\Users\USERNAME\AppData\Local\Temp\pacote-git-template-tmp\git-clone-169f0298
Fatal: The remote end hung up unexpectedly
```
when trying with --verbose, it seems to hang on https://registry.npmjs.org/@tweenjs%2ftween.js

any idea why?

**Comment by vasturiano** [comment]
@gummybear1202 just tried `npm i react-force-graph` with npm `v5.3.0` and it installed fine.
Can you succesfully install `npm i gsap@1.20.4` in your machine?

**Comment by gummybear1202** [comment]
I was able to install gsap@1.20.4, as well as downgrade npm to v5.3.0 but same error. Even when I tried installing `npm i aframe`:

`42 silly pacote range manifest for @tweenjs/tween.js@^16.8.0 fetched in 547ms
43 silly resolveWithNewModule @tweenjs/tween.js@16.11.0 checking installable status
44 silly fetchPackageMetaData error for document-register-element@github:dmarcos/document-register-element#8ccc532b7 Command failed: C:\Users\...\git.EXE clone -q https://github.com/dmarcos/document-register-element.git C:\Users\USERNAME\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-05bd2adc --config core.longpaths=true
44 silly fetchPackageMetaData warning: templates not found C:\Users\USERNAME\AppData\Local\Temp\pacote-git-template-tmp\git-clone-7c6b309b
44 silly fetchPackageMetaData fatal: The remote end hung up unexpectedly
44 silly fetchPackageMetaData error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
45 silly fetchPackageMetaData error for three@github:supermedium/three.js#r90fixMTLLoader Command failed: C:\Users\...\git.EXE clone --depth=1 -q -b r90fixMTLLoader https://github.com/supermedium/three.js.git C:\Users\USERNAME\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-cebb4d62 --config core.longpaths=true
45 silly fetchPackageMetaData warning: templates not found C:\Users\USERNAME\AppData\Local\Temp\pacote-git-template-tmp\git-clone-7c6b309b
45 silly fetchPackageMetaData fatal: The remote end hung up unexpectedly
45 silly fetchPackageMetaData error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
46 silly fetchPackageMetaData error for debug@github:ngokevin/debug#noTimestamp Command failed: C:\Users\...\git.EXE clone --depth=1 -q -b noTimestamp https://github.com/ngokevin/debug.git C:\Users\USERNAME\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c3a1450f --config core.longpaths=true
46 silly fetchPackageMetaData warning: templates not found C:\Users\USERNAME\AppData\Local\Temp\pacote-git-template-tmp\git-clone-7c6b309b
46 silly fetchPackageMetaData fatal: The remote end hung up unexpectedly
46 silly fetchPackageMetaData error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden`

**Comment by gummybear1202** [comment]
Was able to do it on another computer. Closed now
