### ISSUE TITLE
Multiple edges between two nodes

### ISSUE THREAD

**Issue by rohankk2** [vasturiano/react-force-graph#100]
**Describe the bug**

I am trying to have multiple edges from the same source and target but the label of the edge is different. I tried doing this by having multiple source id entries in the links field for graphdata : 

   "links": [
        {
            "source": "id1",
            "target": "id2"
        },
        {
          "source" : "id1",
          "target":"id2",
}
    ]

**Expected behavior**

I should get two edges starting from node id1 to target id2. 
but only get one edge

**Comment by vasturiano** [comment]
@rohankk2 it's possible that both your edges are there but you can't distinguish them because they're in the exact same position. If that's the case you could try to separate them using curved links. Here's an example: https://vasturiano.github.io/react-force-graph/example/curved-links/

**Comment by rohankk2** [comment]
Thanks this solved it closing issue.
