### ISSUE TITLE
ForceGraph3D Hightlight

### ISSUE THREAD

**Issue by spcidealacm** [vasturiano/react-force-graph#101]
I have use the 3d-force-graph before, so I really like the 3d highlight function.
This time I need use react to show 3d highlight, I try to change the react 2d highlight example to 3D.
I think it cannot work on 3D version. So can you give an example to show 3d highlight. It will very significant for me.

**Comment by vasturiano** [comment]
@spcidealacm thanks for reaching out. 
It should just be a matter of converting this [example](https://vasturiano.github.io/3d-force-graph/example/highlight/) to React syntax. If you've tried to do the conversion, which specific issues did you encounter?

**Comment by louMoxy** [comment]
I know this issue is closed, but I had some difficulty doing the conversion for the example above. 

So the way to do this in React is to use `graphRef.current.emitParticle()` and this will give you the `Graph` reference which is used in the example. Happy to add a full example if needed.
