### ISSUE TITLE
Ability to change default mouseover label colours (3D)

### ISSUE THREAD

**Issue by IanMDay** [vasturiano/react-force-graph#102]
Very impressed with the addon, but I have one small issue. For ForceGraph3D the default mouseover label appears to be fixed as lavender without a way to change it. I've made the background of my 3D space quite light to match the theme of our app, but that makes the mouseover label nearly invisible. The 2D one doesn't have this issue because the label is placed onto a type of tooltip with its own dark background, which is great.

Some way to change this, or an example of how this could be done with the existing code.

I've attempted to inject HTML with colours into nodeLabel, but it appears that the spriting process strips out anything like that leaving only the shapes.

![image](https://user-images.githubusercontent.com/42613290/60716989-a18e4d80-9f18-11e9-8dcc-569087b563dc.png)

**Comment by vasturiano** [comment]
@IanMDay the tooltip is a plain `div` element overlapping the canvas. So, you can use simple CSS overrides for any style changes you'd like. Here's the relevant CSS where this is set: https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.css#L10

For example, to make the tooltip font red:
```
#mygraph-dom-id .scene-tooltip {
  color: red;
}
```

**Comment by IanMDay** [comment]
> @IanMDay the tooltip is a plain `div` element overlapping the canvas. So, you can use simple CSS overrides for any style changes you'd like. Here's the relevant CSS where this is set: https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.css#L10
> 
> For example, to make the tooltip font red:
> 
> ```
> #mygraph-dom-id .scene-tooltip {
>   color: red;
> }
> ```

Sorry if I’m being thick, but I don’t seem to be able to do that when creating the component with JSX directly from JavaScript (script based on a create-react-app base). Setting an ‘id’ for the ForceGraph3D component just sets the ‘id’ in the props.

Admittedly, I'm fairly new to react, so may well be missing something blindingly obvious.

**Comment by vasturiano** [comment]
@IanMDay in your CSS file, for example `src/App.css` just add css rules representing the style that you'd like. You don't even need to use the element id, just the class name. Depending on your setup, you may want to force with `!important`, like:
```
.scene-tooltip {
  color: red !important;
}
```

**Comment by IanMDay** [comment]
Alright, I'd tried to do it in a styles construct in the js, which apparently is of no use :)

Thanks for your time.

**Comment by schobernoise** [comment]
> > @IanMDay the tooltip is a plain `div` element overlapping the canvas. So, you can use simple CSS overrides for any style changes you'd like. Here's the relevant CSS where this is set: https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.css#L10
> > For example, to make the tooltip font red:
> > ```
> > #mygraph-dom-id .scene-tooltip {
> >   color: red;
> > }
> > ```
> 
> Sorry if I’m being thick, but I don’t seem to be able to do that when creating the component with JSX directly from JavaScript (script based on a create-react-app base). Setting an ‘id’ for the ForceGraph3D component just sets the ‘id’ in the props.
> 
> Admittedly, I'm fairly new to react, so may well be missing something blindingly obvious.

This is working quite well!
