### ISSUE TITLE
Is there any way to add a legend for a graph ? 

### ISSUE THREAD

**Issue by rohankk2** [vasturiano/react-force-graph#103]
I have a lot of nodes of different colors and hence want to make it easier for the user with a legend on the side.

Is there any way to do this or any way you would recommend going about this ?

**Comment by vasturiano** [comment]
@rohankk2 you can build a DOM element on the side (or even overlap it with the graph itself using some CSS absolute positioning) that shows any details you're interested in surfacing.
You can also make it change dynamically on interaction, by reacting from `onNodeHover` events.
