### ISSUE TITLE
onClickNode not working with nodeThreeObject

### ISSUE THREAD

**Issue by babbel1005** [vasturiano/react-force-graph#105]
Hello,

it seems like the the onClickNode works only if you leave everything by default.
Once I add the props nodeThreeObject, the onClickNode does nothing.
Is there a way to add the click to the subobject passed in the nodeThreeObject? 
In my example I added a image with TREE.Sprite and the click does nothing.
Thank you .

**Comment by vasturiano** [comment]
@babbel1005 the prop is called `onNodeClick`, and it should be compatible with `nodeThreeObject`.

If it doesn't work for your case could you make a simplified example on CodePen that reproduces the issue?

**Comment by technixp** [comment]
@babbel1005 try this
`
   nodeThreeObjectExtend={true}
   nodeOpacity={0}
`
