### ISSUE TITLE
Unable to hide nodes

### ISSUE THREAD

**Issue by rohankk2** [vasturiano/react-force-graph#108]
My function is as follows: 
_handlevisibility = node =>{

  if(node['nodeVisibility']==='false'){
    console.log('here')
    return false
  }
  return false
}

in the props of the react force graph i have added this: 
 nodeVisibility={this._handlevisibility}

However that function does not seem to be getting called. 

Any help would be appreciated

**Comment by vasturiano** [comment]
Is `false` meant to be a string here: `node['nodeVisibility']==='false'`?

Have you tried something like:
```
nodeVisibility={link => { 
   console.log('inside nodeVisibility', link); 
   return true; 
}}
```

If you don't see those console logs, perhaps you're using an older version that doesn't support the prop.
