### ISSUE TITLE
Center bug + Can't get node spread right, need help with d3-force-3d (2D graph)

### ISSUE THREAD

**Issue by Kira9204** [vasturiano/react-force-graph#109]
Hi!
I've been stuck on figuring out how to manipulate the node spread to match the examples provided below, and help would be greatly appreciated. I've also found what i think is a bug with the center force.

In the first example i want to separate "groups" of nodes not connected to each-other by a consistent path.

Bug: when having multiple "groups" of nodes, one of the groups will quickly fly away out of sight completely disregarding the center force. This only happens when there is a center force however. An example is provided below in the sandbox [here](https://codesandbox.io/s/non-connected-node-parents-gmrh8?fontsize=14).
Image: 
![](https://user-images.githubusercontent.com/2965460/62336928-c2739f80-b4d2-11e9-8cf5-b6721ca7a985.jpg)

I also have another case where i want the nodes to expand outwards instead of grouping around the center.
Sandbox example [here](https://codesandbox.io/s/nodes-spread-d2cy6?fontsize=14)
Image:
![](https://user-images.githubusercontent.com/2965460/62337181-e388c000-b4d3-11e9-92ef-503dfecd6338.jpg)
This might seem spacey, but i have multicoloured links with different widths and every node looks like this so i quickly run out of space 
<img width="154" alt="Screenshot 2019-08-02 at 03 28 13" src="https://user-images.githubusercontent.com/2965460/62337608-9b6a9d00-b4d5-11e9-9143-f9bfbbd7e459.png">

I've also tried adding a large charge like -500px, which initially looks fine (nice spread), but as soon as you hold the mouse anywhere everything flies off.

Again, any help explaining how to achieve any of the examples provided would be greatly appreciated.

**Comment by vasturiano** [comment]
@Kira9204 thanks for reaching out.

For your first example, I can't reproduce the case in which some of the nodes fly off the canvas. Also, in your image it seems that all 11 nodes are present in both cases, just in different positions.

For the second example, I'd recommend looking at the `dagMode` prop. The `radialOut` mode should bring you close to what you intend. 
Here's an example: https://vasturiano.github.io/react-force-graph/example/tree/

**Comment by Kira9204** [comment]
@vasturiano Thanks for the reply.
What i'm having trouble with is spreading out the nodes, the right side of the examples are a lot easer to read/digest. But i haven't figured out how to achieve that spread. This is much more an issue with the 1st example than the 2nd. A dagMod/radialOut doesn't really solve it since it would be a different kind of graph them.
I've sort of managed to get the spread i want currently with by "simulating" drag/forces at initial render:
```
//SelectedNode
{...node,
    fx: 300,
    fy: 300
}
      setTimeout(() => {
        graphData.nodes[0].fx = undefined;
        graphData.nodes[0].fy = undefined;
        graphRef.current.centerAt(
          graphData.nodes[0].x,
          graphData.nodes[0].y,
          0
        );
        graphRef.current.zoom(ZOOM, 0);
      }, 100);
```


Regarding the center issue, it becomes apparent if you drag the nodes out. I've provided examples below.
[View](https://gmrh8.csb.app/)
[Screen recoding](https://imgur.com/a/eq99b6J)

**Comment by vasturiano** [comment]
@Kira9204 if you wish to get the nodes more spread out, you can manipulate the repelling force that acts on all the nodes, via `.d3Force('charge')`.

Something like (assuming you have a React ref to your chart element):
```
forceGraphRef.d3Force('charge').strength(-120); // the default is -30
```

As for the `center` force, I've seen your recording and it seems to be behaving as expected. The more you pull one group to the side, the more the disconnected group falls to the opposite side, because the layout is attempting to center the view in the gravitational center of all the nodes combined. Makes sense once you think about it. You can however disable this force if you don't want that effect.

**Comment by Kira9204** [comment]
Thanks for the reply.
It does make sense, Altho i would personally prefer if it would only affect nodes connected to a center node :)
