### ISSUE TITLE
Issue minifying 

### ISSUE THREAD

**Issue by justindavies** [vasturiano/react-force-graph#11]
Seems with my production builds we are getting a minify issue with TweenLite:

║> react-scripts build                                                                                                       ║
║Creating an optimized production build...                                                                                   ║
║Failed to compile.                                                                                                          ║
║Failed to minify the code from this file:                                                                                   ║
║     ./node_modules/gsap/esm/TweenLite.js:1966                                                                              ║

**Comment by vasturiano** [comment]
@justindavies I wonder if it's related to this: https://github.com/greensock/GreenSock-JS/issues/267

Are you importing version 1.20.5 of GSAP?

**Comment by justindavies** [comment]
I'm not too hot on package.json management to be honest, but I can see it referenced here:

    "force-graph": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/force-graph/-/force-graph-1.4.0.tgz",
      "integrity": "sha512-LPPs455Jyq3IQrlCDyHJ2AS8cBhTuWMYKDP3zV8LqxLQ+acNfXjjaVEybqFf2JoK3Rpv9nGljBoShnU/fpXrIA==",
      "requires": {
        "accessor-fn": "1.2.2",
        "bezier-js": "2.2.5",
        "canvas-color-tracker": "1.0.0",
        "d3-drag": "1.2.1",
        "d3-force": "1.1.0",
        "d3-scale-chromatic": "1.3.0",
        "d3-selection": "1.3.0",
        "d3-zoom": "1.7.1",
        "gsap": "1.20.6",
        "index-array-by": "1.1.0",
        "kapsule": "1.9.1",
        "lodash.throttle": "4.1.1"
      }

Should I downgrade the gsap version in there ?

**Comment by justindavies** [comment]
Resolved issue #11 by specifying a previous version of GSAP

"gsap": "1.20.4"
