### ISSUE TITLE
Labels not lining up with nodes and links

### ISSUE THREAD

**Issue by jminnick** [vasturiano/react-force-graph#112]
Maybe I am missing something, but label/click areas are not lining up with the nodes and links on resolutions at or below 1920x1200

<img width="1025" alt="Screen Shot 2019-08-29 at 8 54 11 PM" src="https://user-images.githubusercontent.com/3810135/63986083-6df71c00-caa0-11e9-9b7a-b0152bb20d07.png">

**Comment by vasturiano** [comment]
@jminnick could you provide a reproducing example on CodePen or CodeSandbox, to help troubleshoot your issue further?
