### ISSUE TITLE
Get current camera position or at least a pan call back?

### ISSUE THREAD

**Issue by meds** [vasturiano/react-force-graph#113]
I'm trying to convert node positions from canvas space to the window view port space however there's no way I can find to get either the nodes position in the canvas viewport space or the view ports current pan offset to figure it out myself.

**Comment by vasturiano** [comment]
@meds assuming you are in 2D mode, you can track canvas pan/zoom interactions via the `onZoom(({ k, x, y }) => ...)` callback.

**Comment by meds** [comment]
@vasturiano ah yep that worked! the documentation on it was a bit vague I thought onZoom wasn't supported for 2D.

**Comment by vasturiano** [comment]
@meds good catch, there was a typo in the docs. That's now fixed and shows the correct compatibility.
