### ISSUE TITLE
Panning camera to root node while simulation is cooling down

### ISSUE THREAD

**Issue by NickRL21** [vasturiano/react-force-graph#114]
I am using ForceGraph2D with a DAG mode of null using dynamically generated data. The issue I am running into is for graphs with large numbers of nodes it can be difficult to find the root node. With each different dataset the root can be in a drastically different location often outside of the viewport. 

What I would like to accomplish is to have the camera track and center on the root node for the initial portion of the simulation until it cools down for the first time. Then after this initialization return to default behavior. 

I'm not sure if this is possible but any ideas would be appreciated.

**Comment by vasturiano** [comment]
@NickRL21 you could temporarily fix your center node to the center of the canvas (0,0), by adding these `f*` attributes to it: `{ fx: 0, fy: 0 }`. This will make the force directed engine not touch the coordinates of that node.

**Comment by NickRL21** [comment]
@vasturiano Thanks for the reply, seems like it will work for my needs.
