### ISSUE TITLE
React-force-graph-3d freezes with raycasted sprites.

### ISSUE THREAD

**Issue by bnowlin** [vasturiano/react-force-graph#115]
**Describe the bug**
After initial load the graph freezes.

![3d_freeze](https://user-images.githubusercontent.com/8888589/64624686-a526d080-d3b0-11e9-9949-7dc9d16b0ef9.png)

**To Reproduce**
1. Use a version of Three.js above 0.105.2
2. Use sprite as the 3D object returned to nodeThreeObject prop
`const spriteMaterial = new THREE.SpriteMaterial({ map: texture, color, depthWrite: false });
 const sprite = new THREE.Sprite(spriteMaterial);
 sprite.scale.set(20, 20, 1);
 sprite.frustumCulled = false;`

**Screenshots**
Error returned on the console:
![3d_freeze_console](https://user-images.githubusercontent.com/8888589/64625195-61809680-d3b1-11e9-8d7a-9108913ec81b.png)

**Additional context**
Threejs has a known issue with ray-casting and sprites in which they updated documents to include needing to the set the camera if your using sprites.

https://github.com/mrdoob/three.js/issues/17078
https://github.com/mrdoob/three.js/pull/16423

Updated example with raycaster.setFromCamera: https://threejs.org/examples/webgl_raycast_sprite.html

**Comment by bnowlin** [comment]
Found the duplicate issue deeper in the project tree of 3d-force-graph. 
https://github.com/vasturiano/3d-force-graph/issues/217

**Comment by wadehenning** [comment]
Hi @vasturiano 
I am having a similar issue-- my ForceGraph3D freezes and I get the same Error returned on the console as above.  Here is a codesandbox that produces similar output as I get locally(locally I actually get blue dots plotted).    
https://codesandbox.io/s/intro-uqel4

**Comment by vasturiano** [comment]
@wadehenning thanks for creating the sandbox! 
However I'm not able to reproduce this specific error. Do you get a 
```
Cannot read property 'matrixWorld' of undefined
```
error in the console?

Regardless, one change that I would recommend is to import the named modules from `three` separately instead of the `require("three")`. Something like:
```
import { CanvasTexture, SpriteMaterial, Sprite } from 'three';
```

And you can also import just the 3d force graph component with:
```
import ForceGraph3D from 'react-force-graph-3d';
```

**Comment by wadehenning** [comment]
Thanks for your advice, @vasturiano .  I have not been successful importing directly from 'three' as you suggest (I always get a THREE not found error).  I did change to importing from `react-force-graph-3d`.  

Locally, I do get the Uncaught TypeError `Cannot read property 'matrixWorld' of undefined`, but I don't get it in my codesandbox.  

However, I updated the [codesandbox](https://codesandbox.io/s/intro-uqel4) to get the circles to plot (I was not properly including the circles in the nodes.  I get the message `THREE.WebGLRenderer: Context Lost'.  Maybe that is significant?    The nodes are still not interactive, but there are no errors on codesandbox.

**Comment by wadehenning** [comment]
HA!!! @vasturiano 
You were right about `import { CanvasTexture, SpriteMaterial, Sprite } from 'three';`

I had tried updating it locally, but not on codesandbox[https://codesandbox.io/s/intro-uqel4](url).  When I made the change there, it works.  But now I have to figure out how to make it work locally.

**Comment by wadehenning** [comment]
@vasturiano .  Please take a look at line 64  of the code](https://codesandbox.io/s/intro-uqel4).  My hope is that understanding what is going on here will help me get it running locally.  Line 64 is actually incorrect:
`const sprite = new THREE.Sprite(material);`

The `THREE` should not be there. But if I remove it, the plot again becomes non-interactive.   Thank you.

**Comment by vasturiano** [comment]
@wadehenning glad you got most things working.

One thing I would check in your project is if you have a single version of `three` in your dependency tree. Looking inside your lockfile should tell you. If you have more than one I would suggest to deduplicate them, otherwise this is notorious for causing unexpected side effects, which may be the root cause of your issue.

About your sandbox, if I change L64 to
```
const sprite = new Sprite(material);
```
it works fine for me.

**Comment by wadehenning** [comment]
@vasturiano 
Simple-- thanks. I uninstalled related packages that I am not currently using and deleted/installed my package-lock file, and everything now works beautifully.  In addition, to recap your key advice from above, I switched my import strategies to:
` import { CanvasTexture, SpriteMaterial, Sprite } from 'three' `
`import ForceGraph3D from 'react-force-graph-3d' `

**Comment by bnowlin** [comment]
Hm.. I swore I posted a message here Tuesday. Anyway, I was able to get the error to go away after multiple package updates. (both react-force-2d/3d and three js)
