### ISSUE TITLE
I need  your help

### ISSUE THREAD

**Issue by gordal18** [vasturiano/react-force-graph#12]
Hello
I can't see the nodeLabel.
How can I solve this?
This is an excellent module..
I want to solve this ASAP.
Best Regards,

Gordal18

**Comment by vasturiano** [comment]
@gordal18 thanks for reaching out. What is the issue that you're experiencing?
The node labels should appear as tooltips when hovering over nodes. Does this example work for you: https://vasturiano.github.io/react-force-graph/example/click-to-focus/

**Comment by gordal18** [comment]
Thank you for your reply
It was CSS issue.
I can fix it myself.
Thank you .
But there's any example like this?
http://quesedice.cl/

**Comment by vasturiano** [comment]
Like this one? https://vasturiano.github.io/react-force-graph/example/text-nodes/index-2d.html

**Comment by gordal18** [comment]
Hello

When I select one word, I want to highlight the words linked the selected one
How can I do that?

**Comment by vasturiano** [comment]
@gordal18 there is a similar functionality in this example: https://bl.ocks.org/vasturiano/321a770c3f4b041d1a4f40f1f4ecbb6c

And here's another highlighting example with `react-force-graph`: https://vasturiano.github.io/react-force-graph/example/highlight/
