### ISSUE TITLE
How to draw a graph at the center of the canvas?

### ISSUE THREAD

**Issue by akhildixit** [vasturiano/react-force-graph#120]
How to draw the graph at the center of the canvas? In my case, no matter what height and width I set for the canvas, the graph gets drawn somewhere outside the canvas. Dragging the mouse on the canvas brings the graph on the canvas.

**Comment by vasturiano** [comment]
@akhildixit by default the graph is anchored on the center of the canvas. Could you post a minimal example on https://codesandbox.io reproducing your issue?
