### ISSUE TITLE
(2D) Question: d3ReheatSimulation() does nothing if cooldownTime has expired. Trying to change link distance programatically does nothing?

### ISSUE THREAD

**Issue by Kira9204** [vasturiano/react-force-graph#121]
Hi!
In my application i have a sidebar with a lot of different settings like freezing the graph, changing link distance etc.
Previously i've been using the following settings in an old version:
cooldownTicks={isFreeze ? 0 : 400} (no changed cooldownTime) paired with a graphRef.refresh().

Upon upgrading and replacing refresh() with d3ReheatSimulation i've noticed that changing distance didn't do anything almost as soon as the graph had mounted.
Using the following [sandbox](https://codesandbox.io/s/link-distance-change-y07qi?fontsize=14) i noticed that it took 15 seconds before the graph stopped responding to changes to the link distance, which brought my attention to the cooldownTime prop. Move things around and changing the distance worked for another 15 seconds.
I got things working as intended with the following props in the end:
cooldownTicks={isFreeze ? 0 : Infinity}
cooldownTime={Infinity}

My question boils down to this: If moving things around re-heats the graph and resets the cooldownTime, shouldn't a forced re-heat using d3ReheatSimulation do the same? And if not, what is the intended use-case for the function?

**Comment by vasturiano** [comment]
@Kira9204 thanks for the report. 
You're right, there was a small bug in the previous version that was preventing the simulation from reheating after the cooldown period has passed. This is now fixed, please pull the latest version (`1.11.0` of `react-force-graph-2d`) and try again. Sorry for the trouble.
