### ISSUE TITLE
Feature request/question: Swap directional arrow direction

### ISSUE THREAD

**Issue by Kira9204** [vasturiano/react-force-graph#122]
Hi! 
I have a pretty specific use-case that i need to solve. Sometimes depending on the context we have "incoming" or "outgoing" links that from a graph data perspective are the same (no changes to source, target, or any forces), but that from a user perspective gets confusing.
I'd like to be able to toggle the direction of the linkDirectionalArrow and do a 180° spin on it. This would also change the direction of the linkDirectionalParticles but that can be left out.
Illustrations:
![1](https://user-images.githubusercontent.com/2965460/66242082-108a6680-e701-11e9-8ded-deee6a8f41c6.png)
![2](https://user-images.githubusercontent.com/2965460/66242086-12ecc080-e701-11e9-87cd-e1f7bc08607c.png)
I'd be very interested in getting some hints on how these are currently implemented and if this is easily achievable.

**Comment by vasturiano** [comment]
@Kira9204 I think you can achieve this by simply swapping the `source` and `target` attributes on the link you wish to invert. Have you tried that?

**Comment by Kira9204** [comment]
![ScreenRecording2019-10-06at16145](https://user-images.githubusercontent.com/2965460/66345068-8dab1b00-e94f-11e9-90f9-2b664feacd87.gif)
Yes and with a little trickery i can get it to work, but since the same data is used for various things such as connecting nodes manually this creates a lot of hassle. Ultimately i want it to work as it does originally, but i **only** want to change the arrow direction.
Since im already drawing my own links using the nodeCanvasObject prop (the yellow ones you see) i might just be able to re-create the arrow on the fly based on [paintArrows()](https://github.com/vasturiano/force-graph/blob/master/src/canvas-force-graph.js#L270) but performace worries me a little.

**Comment by vasturiano** [comment]
@Kira9204 yes, since this is a bit of an uncommon use case, I'd recommend going the route of drawing your own arrows using the `linkCanvasObject` method. The performance impact should be no worse than when using the internal convenience `linkDirectionalArrow` methods.
