### ISSUE TITLE
dagMode radialout not working

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [vasturiano/react-force-graph#123]
**Describe the bug**
Hi everyone, 

I just add the library to our project, we wanna make a company tree, so we just add we create a basic example to know how it behaves.

So the dagMode radialout doesn't separate as we expected on the graph.

**To Reproduce**
 Our component.

  ```
 const MyData = {
      "nodes": [
        { "package": "one", "user": "vasturiano1" },
        { "package": "two", "user": "vasturiano2" },
        { "package": "three", "user": "vasturiano3" },
        { "package": "five", "user": "vasturiano5" },
        { "package": "six", "user": "vasturiano6" },
        { "package": "seven", "user": "vasturiano7" },
        { "package": "eight", "user": "vasturiano8" },
        { "package": "nine", "user": "vasturiano9" },
        { "package": "ten", "user": "vasturiano19" }
      ],
      "links": [
        { "target": "two", "source": "one" },
        { "target": "three", "source": "two" },
        { "target": "five", "source": "one" },
        { "target": "six", "source": "one" },
        { "target": "seven", "source": "one" },
        { "target": "eight", "source": "one" },
        { "target": "nine", "source": "one" },
        { "target": "ten", "source": "one" }
      ]
    };

 <Grid item xs={12} md={6}>
            <Paper className={classes.root}>
              <ForceGraph2D
                graphData={MyData}
                dagMode={'radialout'}
                dagLevelDistance={90}
                d3VelocityDecay={1}
                nodeId="package"
                nodeAutoColorBy="user"
                nodeRelSize={10}
                linkDirectionalParticles={12}
                linkDirectionalParticleWidth={1.5}
              />
  </Grid>
```

**Expected behavior**
We wanna show the view like the example

![Captura de Pantalla 2019-10-04 a la(s) 17 44 47](https://user-images.githubusercontent.com/25987364/66244557-ae187280-e6ce-11e9-9d27-e6d62812415e.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox 
 - Version 69.0.2

How the graph shows:

![Captura de Pantalla 2019-10-04 a la(s) 17 45 53](https://user-images.githubusercontent.com/25987364/66244586-d3a57c00-e6ce-11e9-8be7-25ee66aed8d5.png)

Any advice?

**Comment by vasturiano** [comment]
Setting `d3VelocityDecay={1}` is not advised. It will make the resistance too big and nearly immediately cancel the effect of the force simulation.

If you just remove that prop you'll get a better layout already:
![Screenshot 2019-10-05 at 23 42 12](https://user-images.githubusercontent.com/6784226/66265374-22840c00-e7ca-11e9-8ae3-ca1c7014baca.png)

**Comment by ulisescarreonalvarez** [comment]
Hi @vasturiano 
You know, we wanna make an orgnizational graph for a company, it will have teams and employees, so this graph could help, we wanna feel that we can drag the nodes withouth the bouncy effect and fisrt of all without modify the node positions.

is this possible?

Regards in advance

**Comment by vasturiano** [comment]
@ulisescarreonalvarez you could set `cooldownTicks={0}` after the force engine has passed the initial layout phase. This will tell the simulation to not run any force iteractions on updates, like node drags. You could apply this prop on `onEngineStop` for example.
