### ISSUE TITLE
How to stop the force and drag a node to a new (fixed) position?

### ISSUE THREAD

**Issue by Adel-M86** [vasturiano/react-force-graph#124]
Hello,

I need to being able to drag nodes and change their position to some new place without being affected by the force. How can I stop the force after the graph is rendered for the first time?
 
Regards.

**Comment by vasturiano** [comment]
@Adel-M86 one way is to set `cooldownTicks={0}`. This will tell the force simulation engine to not run any iterations on any engine re-heats like node drag. You could apply this prop on `onEngineStop`.

**Comment by Adel-M86** [comment]
@vasturiano  Thanks :)

**Comment by Lander37** [comment]
@vasturiano 
How can I apply cooldownTicks={0} in onEngineStop?

**Comment by ddor254** [comment]
+1 on @Lander37  question

**Comment by vasturiano** [comment]
@Lander37 assuming you're using hooks, if you have the prop `cooldownTicks` as a state:
```
const [cooldownTicks, setCooldownTicks] = useState(undefined);
```

You can apply it like:
```
<ForceGraph3D
  ...
  cooldownTicks={cooldownTicks}
  onEngineStop={() => setCooldownTicks(0)}
/>
```

**Comment by derin-art** [comment]
Good evening, I have a problem with using state with the component because it re-renders every time the state changes leading to an animation. Is there anyway to disable this? Thank you
