### ISSUE TITLE
onNodeRightClick() will automatically trigger the onNodeDragEnd().

### ISSUE THREAD

**Issue by Adel-M86** [vasturiano/react-force-graph#125]
When I use onNodeRightClick() and onNodeDragEnd() together, every time I use onNodeRightClick(), the onNodeDragEnd() is called, no matter if the node is dragged or not. it is not desired and make the layout inconsistent. 

onNodeDragEnd={n => {
          console.log("onNodeDragEnd is called!");
 }}

onNodeRightClick={n => {
          console.log("onNodeDragEnd is called!");
  }}

when right click on the node:

onNodeDragEnd is called!
onNodeDragEnd is called!

both of them is called!

* same thing happened for onNodeClick()

**Comment by vasturiano** [comment]
@Adel-M86 thanks for the report! This is now fixed in `v1.26.4`.
