### ISSUE TITLE
How to always show all node labels (maybe under the node) for a graph?

### ISSUE THREAD

**Issue by hsluoyz** [vasturiano/react-force-graph#126]
How to always show all node labels (maybe under the node) for a graph? I saw `nodeLabel` but it only shows a toast when hovering on a node.

I saw this issue: https://github.com/vasturiano/react-force-graph/issues/57 but it replaces the shape with text. But I want to see both shape and label like this one: https://bl.ocks.org/heybignick/3faf257bbbbc7743bb72310d03b86ee8

![image](https://user-images.githubusercontent.com/3787410/66892008-18111000-f01d-11e9-8185-e8335130b5ff.png)

Is there anyway to do this? Thanks.

**Comment by vasturiano** [comment]
@hsluoyz you can set 
```
nodeCanvasObjectMode={() => 'after'}
```

to leave the default node painting intact and just extend it with the labels. When you draw the labels, you just need to offset the text location in `fillText` so that it shows below (or on the side).

**Comment by hsluoyz** [comment]
Thanks.

**Comment by hsluoyz** [comment]
Hi @vasturiano I'm using your solution. But I found most of the text labels are covered by the node shapes. You can see the picture. So how to let all text labels on top of all node shapes? Thanks.

```js
  renderContent() {
    return <ForceGraph2D
        graphData={this.state.graphData}
        enableNodeDrag={false}
        nodeCanvasObjectMode={() => 'after'}
        nodeCanvasObject={(node, ctx, globalScale) => {
          const label = '1234567890';
          const fontSize = 12 / globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = 'black'; //node.color;
          ctx.fillText(label, node.x, node.y + 6);
        }}
    />
  }
```

![image](https://user-images.githubusercontent.com/3787410/67740195-f0c03700-fa4f-11e9-8827-767a8ef85584.png)

**Comment by vasturiano** [comment]
@hsluoyz that is not really possible as the nodes are drawn (according to your `nodeCanvasObject` function) atomically in the sequence that they are listed in your `nodes` section of the `graphData`. 

In a canvas element, when an item is drawn it overrides the pixels of whatever drawing was previously performed in the same area. That causes the overlap. But, you can play around with color opacities to make sure there's some degree of see-through between overlapping nodes.

**Comment by hsluoyz** [comment]
Is there any way (layers, draw orders, Z-axis, etc.) to draw all the text labels after all node shapes are rendered?

**Comment by vasturiano** [comment]
@hsluoyz there is no simple way I can think of.
One approach I can imagine is to have two graph components exactly overlapping (using a `position: absolute`), in which you draw the nodes on the bottom one and the labels on the top one. You can pass the same data object to both to ensure that the nodes positions match.
I would also recommend disabling the force engine in one of them so that you don't have double forces in action.
