### ISSUE TITLE
How to increase distance between nodes?

### ISSUE THREAD

**Issue by IVIyg0t** [vasturiano/react-force-graph#127]
Hi there!

When displaying text with Nodes, the text is just overlapping each other.  How do I increase the distance between nodes so that the text has enough space to be seen easily?

![image](https://user-images.githubusercontent.com/8680619/67121369-56433680-f1b9-11e9-8319-8fde836b9c21.png)

If this isn't supported, it'd be nice to have this feature!

**Comment by vasturiano** [comment]
https://github.com/vasturiano/react-force-graph/issues/107

**Comment by IVIyg0t** [comment]
Ahhh, thank you!
