### ISSUE TITLE
Node size based on links connected to it

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#128]
Is it possible to change the node size based on links connected to it?

The green link has two links connected to it, what I would like to do is increase it in size as compared to other nodes that have a single link connection. 
![Screen Shot 2019-10-21 at 11 36 05 AM](https://user-images.githubusercontent.com/22722805/67232831-005bd200-f3f7-11e9-837c-170fcfef1e59.png)

Thank you very much!

**Comment by vasturiano** [comment]
@Parul-Kudtarkar yes, that should be doable. You just need to pre-calculate how many links are connected to each node, and set the `nodeVal` prop according to it.

**Comment by IVIyg0t** [comment]
I think you can also do this via the `val` property of the node data model.

So, if you're able to, pre calculate that value before passing it into the component and the node sizes should according to that value.

**Comment by Parul-Kudtarkar** [comment]
Excellent! Both solutions work. @vasturiano @IVIyg0t thanks for your help!
