### ISSUE TITLE
adding nodes `onClick` cause disconnected links

### ISSUE THREAD

**Issue by ddor254** [vasturiano/react-force-graph#129]
Hi all, I encountered a problem when adding new nodes after clicking button - 

The simulation changes but the "old" links remain in the new simulation as they were in the previous simulation, they stay as disconnected links.

my link.source object looks like this:
`{"source":{"id":"Maximus33@yahoo.com","__indexColor":"#d80002","index":1,"x":-4.813047289466723,"y":-3.699349888419312,"vx":-0.20009118549264576,"vy":-0.12077736812875411} ... `

should I update the `source.index` to be corresponding to the `index` of the related node??

Adding a gif that show the problem.

![add](https://user-images.githubusercontent.com/33092692/67668214-285bb000-f978-11e9-9ffe-ee997578260d.gif)

**Comment by vasturiano** [comment]
@ddor254 could you make a minimal example on https://codesandbox.io/ that reproduces your issue, so that it's easier to debug?

**Comment by ddor254** [comment]
Hi @vasturiano, I tried and figure out what is happening and the solution i found was to "create" the graph edges in every `render`, since the 3d simulation fill up extra fields like `vx,vy` . 

when recreate the edges every render with only the fields relevant to me - the problem was solved.

**Comment by shikharsrivastava** [comment]
Hi @ddor254 @vasturiano I am facing a similar problem, when updating the graph data and rendering again the links seem be be at the same place and nodes move away making them disconnected. Can you please elaborate the solution that worked for you?

**Comment by ddor254** [comment]
@shikharsrivastava  as i said one comment above yours : 

you need to create the graph edges in each render. 
in my case i just did the `source` and `target` remapping on render.

`    links = _(this.state.links).map(function(link) {
      return {
        source: typeof(link.source) == 'object' ? link.source.id : link.source,
        target: typeof(link.target) == 'object' ? link.target.id : link.target
      }
    }).value();`
