### ISSUE TITLE
Loading feature

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#130]
Is there a loading feature (something like a spinner or "Graph Loading..." message displayed) while the application is fetching data to render the graph?

Thanks!
Parul

**Comment by vasturiano** [comment]
@Parul-Kudtarkar handling loading states should be the responsibility of the consuming application that knows about the asynchronous details of the `fetch` calls. This module just knows of whatever data is passed to it via the `graphData` prop.
I would recommend conditionally swapping this component with your own loading indicator whenever you're doing asynchronous operations like loading data.

**Comment by Parul-Kudtarkar** [comment]
That makes sense. Thank you so much @vasturiano
