### ISSUE TITLE
3D three geometry that has a canvas texture with image

### ISSUE THREAD

**Issue by cjm771** [vasturiano/react-force-graph#133]
Hi I am using react-konva to draw a canvas element, which I then use to texture the three 3D geometry , grabbing the canvas via a ref. It works kind of, but when my canvas has images, the images don’t load which I’m assuming because it’s asynchronous. What’s the best way to handle this?

**Comment by vasturiano** [comment]
@cjm771 thanks for reaching out. I think this is more a question for `threejs` than `react-force-graph`. `nodeThreeObject` just takes a well formed `Object3d` and places it in the scene. 
Can you render your textured 3d object with images on a regular threejs scene? I would try to test that first.

**Comment by cjm771** [comment]
O oh ok I guess this is true but is there a way to force a node to rerender and run nodeThreeObject function? I am basically doing : 
``` js
nodeThreeObject={ ({id, category}) => {
                     // grab canvas from react-konva stage
`                   const canvas = postsRef.current.querySelector(`#id-${id} canvas`);
                    var texture = new THREE.CanvasTexture(canvas);
                    var mainMaterial =  new THREE.MeshBasicMaterial({
                      color: 'white',
                      flatShading: true,
                      opacity: 1,
                      map: texture,
                    });
                    var basicMaterial = new THREE.MeshBasicMaterial({
                      color: getColor(category),
                      flatShading: true,
                      opacity: 0.75,
                      transparent: true
                    });
                    return new THREE.Mesh(
                    new THREE.BoxGeometry(5, 10.5, .5), [
                      basicMaterial,
                      basicMaterial,
                      basicMaterial,
                      basicMaterial,
                      mainMaterial,
                      mainMaterial,
                    ]);
```

**Comment by vasturiano** [comment]
I don't think there is a concept of re-rendering per se. The object you generate in `nodeThreeObject` is added to the scene. Whatever modifications you make to the object will be effective as soon as the scene updates (at every frame). 
I would recommend troubleshooting this by adding your object to a simple `threejs` scene. If it works there it should work here too.
