### ISSUE TITLE
How does one specify YXZ rotation order? i.e. stay aligned to horizon.

### ISSUE THREAD

**Issue by cjm771** [vasturiano/react-force-graph#134]
I would like to have camera not tilt, and always keep the xy world plane aligned  with the horizon. According to this post:  https://stackoverflow.com/questions/17517937/three-js-camera-tilt-up-or-down-and-keep-horizon-level , you just have to adjust the rotation order but cant figure out how to do that in the react binding. Any help would be great!

**Comment by vasturiano** [comment]
@cjm771 using `controlType="orbit"` should give you the effect you are looking for.

**Comment by cjm771** [comment]
Yup that worked! thanks!
