### ISSUE TITLE
How to get default zoom value on initial render of graph?

### ISSUE THREAD

**Issue by saurabhavid** [vasturiano/react-force-graph#135]
As per the available documentation there's a way to set the graph zoom level via `zoom()` but is there any way with which i can get the existing/default value of zoom when the graph is loaded?

```js
<ForceGraph2D
    ref="fgref"
    graphData={this.graphData}
    ...
    onZoom={(z)=>{
    }}
/>
```
Also `onZoom()` is not getting called when I use `this.refs.fgref.zoom(k, t)`;

**Comment by saurabhavid** [comment]
@vasturiano Would appreciate your help over this :)

**Comment by vasturiano** [comment]
@saurabhavid thanks for reaching out. I've just pushed an update that should fix the issue with the `onZoom` prop. It should be properly triggered if you pull the latest package version.
You can also retrieve the current zoom programmatically by invoking the `zoom` method without any arguments, i.e. `const curZoom = myRef.current.zoom()`;

**Comment by saurabhavid** [comment]
Thanks for the quick update @vasturiano. I'll update and try it out

**Comment by saurabhavid** [comment]
This is working as expected, Closing this issue. 
Thanks for your support @vasturiano

**Comment by rudranil-rebinInfotech** [comment]
I am getting error when i use zoom function, and the error is myref.current.zoom is not a function
