### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by yangguang-hs** [vasturiano/react-force-graph#136]
**Describe the bug**
When I load the 2d diagram, it will give me a window is undefined, at force-graph.common.js

Can you help to add the checking in the force-graph.common.js,
or you can use 'npm global', and have a var window = require('global/window'); in the beginning of  force-graph.common.js,

window = require('global/window') is below content

=> 

var win;

if (typeof window !== "undefined") {
    win = window;
} else if (typeof global !== "undefined") {
    win = global;
} else if (typeof self !== "undefined"){
    win = self;
} else {
    win = {};
}

module.exports = win;

**Comment by yangguang-hs** [comment]
@vasturiano Would appreciate your help over this :) , this is quite urgent for us. Thank you

**Comment by saurabhavid** [comment]
Hey @yangguang-hs  Are you using Server side rendering by any chance? 
if yes, then I would suggest you to suppress the loading of graph until your app is loaded on client.

You can use something like:
```js
{window && <YourGraph />}
```

**Comment by yangguang-hs** [comment]
Hi, I have tried but it doesn't work, so can I ask for adding the window inside to prevent error?

**Comment by vasturiano** [comment]
@yangguang-hs you should be able to do that from your application too. 
Keep in mind this module is not intended to be compatible with SSR. You should make sure that it's not rendered on the server side, like @saurabhavid mentioned.

**Comment by yangguang-hs** [comment]
Hi, I have tried to put the (window &&) or set state for a flag in componentDidMount, but none of them are working, So I hope you can help to add the window initialisation for error handling. Really appreciate if you can help! thank you

**Comment by Arrow891** [comment]
@yangguang-hs instead of checking window, you can check client side like this :

`const isCSR = process.env.BROWSER`
Then 
`{isCSR && <blah>... `

It worked for me, hope it helps.

**Comment by alitourani** [comment]
I had faced the same issue, and solved it like this:
1) Create a file to include your react-force-graph module:
```
import { ForceGraph2D } from 'react-force-graph';
export default ForceGraph2D;
```

2) Use Next.js's **dynamic** module:
```
import dynamic from 'next/dynamic';
const NoSSRForceGraph = dynamic(() => import('../lib/noSSR/NoSSRForceGraph'), {
  ssr: false,
});
.
.
.
return <NoSSRForceGraph
            graphData={sample}
            nodeLabel="id"
            nodeAutoColorBy="group"
            linkDirectionalParticles="value"
          />
```

**Comment by psygo** [comment]
@alitourani Very helpful, thanks!

For me, I had to change it slightly to:

```typescript
const NoSSRForceGraph2D = dynamic(
  () =>
    import("./components/Graph2d").then(
      (module) => module.Graph2d
    ),
  { ssr: false }
);
```
