### ISSUE TITLE
nodeCanvasObject gets called infinite time even when no changes in graph

### ISSUE THREAD

**Issue by ddor254** [vasturiano/react-force-graph#140]
Hi all, i have a graph with 9 nodes and 19 links, i did a :

`nodeCanvasObject={this.paintRing}` and paintRing is the same as in the examples :
https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html
i just added a `console.log` at the beginning of the function.

the problem is that the console.log/paintRing gets called infinite amount of times even when no changes to graph.

i did a `cooldownTicks={20}` and `cooldownTime={5000}` which had no effect. 

is this an expected behavior ? or is it a bug ?

**Comment by vasturiano** [comment]
@ddor254 this is intended behaviour. The way the motion animation works on a canvas context is at every frame the full canvas is wiped and all the objects redrawn. This means your `nodeCanvasObject` callback gets called at every frame and is continuosly used to draw each node object. So, it's important to keep this method as performant as possible.

**Comment by ddor254** [comment]
@vasturiano  thank you for the response - will work accordingly.
