### ISSUE TITLE
turn the labels on/off

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#141]
![Screen Shot 2019-12-05 at 11 21 06 AM](https://user-images.githubusercontent.com/22722805/70266525-8044be00-1751-11ea-8591-2ecf8ec57e99.png)

Hi is it possible to turn the node labels (on/off) via. on/off button?

Thanks!
Parul

**Comment by vasturiano** [comment]
@Parul-Kudtarkar I suppose you're using `nodeCanvasObject` to add the labels to the nodes. You just have to change the logic in the method to paint nothing if your label button state is off.

**Comment by Parul-Kudtarkar** [comment]
@vasturiano thanks! This is helpful however I am limited by input parameters that I can pass and won't allow me to pass the state of label button since the allowed parameters are graphData, nodeId, linkSource and linkTarget

**Comment by Sommerfeld** [comment]
```jsx
const hideLabels = useState(false)
```

```jsx
nodeCanvasObject={(node) => {
  if (hideLabels) {
    return
  }
  ctx.font = `${fontSize}px Sans-Serif`
  ctx.textAlign = "left"
  ctx.textBaseline = "middle"
  ctx.fillStyle = "black"
  ctx.fillText(node.label, node.x + 6, node.y)
}}
```

or per node

```jsx
const graphData = useMemo(() => ({
  nodes: [
    {id: "1", hideLabel: true, label: "Foo"},
    {id: "2", hideLabel: false, label: "Bar"},
  ],
  links: [{ source: "1", target: "2" }]
}), [])
```

```jsx
nodeCanvasObject={(node) => {
  if (node.hideLabel) {
    return
  }
  ctx.font = `${fontSize}px Sans-Serif`
  ctx.textAlign = "left"
  ctx.textBaseline = "middle"
  ctx.fillStyle = "black"
  ctx.fillText(node.label, node.x + 6, node.y)
}}
```

**Comment by Parul-Kudtarkar** [comment]
Perfect! @Sommerfeld this works, thank you very much!

**Comment by chaitali-pathak** [comment]
What should be nodeCanvasObjectMode for this?

**Comment by chaitali-pathak** [comment]
@Parul-Kudtarkar
