### ISSUE TITLE
npm found 5 vulnerabilities

### ISSUE THREAD

**Issue by xgaia** [vasturiano/react-force-graph#142]
**Describe the bug**
npm found 5 vulnerabilities during `npm install`

**To Reproduce**
`git clone https://github.com/vasturiano/react-force-graph.git && cd react-force-graph `
 `npm install`

or

`npm install react-force-graph`

Error:

```
found 5 vulnerabilities (3 low, 2 high) in 2095 scanned packages
  5 vulnerabilities require manual review. See the full report for details.
```
npm audit show that braces, clean-css and lodash are deprecated

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by vasturiano** [comment]
@xgaia thanks for reporting. This is fixed with the latest aframe dependency upgrade to `v1.0.0`.
