### ISSUE TITLE
Help with raycaster hit detection

### ISSUE THREAD

**Issue by ChrisLincoln** [vasturiano/react-force-graph#143]
I am using react-force-graph-3d. I am attempting to detect if one node is dragged "over" another node (from the user's POV) using the raycaster.  If it is, and they drop, I intend to link the two nodes.  I think I'm way out in left field with the coordinate system. The following type of logic works for mouse x/y, but not for nodes. Here is my onNodeDrag={} handler:
```    
    const { camera, scene } = forceGraph.current;
    const theScene = scene();
    const theCamera = camera();
    const raycaster = raycasterInstance.current;
    raycaster.setFromCamera({x: node.x, y: node.y}, theCamera);
    const intersects = raycaster.intersectObjects(theScene.children, true);
    // intersects is an empty array.
```
Alternate question:  Is the mouse x/y available to me during this event?

**Comment by vasturiano** [comment]
@ChrisLincoln thanks for reaching out. I think you are right that it's a discrepancy with the two coordinate systems. The node positions (`{ x, y, z }`) indicate the node's location relative to the center of the graph. The raycaster expects coordinates from the camera's POV, the viewport. Unless the camera is at the very center looking along the z axis, the two systems won't match.

So, what you need is just mouse coordinates along the viewport, like you mentioned. I think you should be able to track those by attaching a `mousemove` event handler to the DOM element where you mounted the force graph.

Let me know if that works out.

**Comment by ChrisLincoln** [comment]
I was able to implement the feature without graph drag-n-drop.
