### ISSUE TITLE
zoom is broken

### ISSUE THREAD

**Issue by xgaia** [vasturiano/react-force-graph#144]
**Describe the bug**

I use a default zoom value at component start (#63)

```javascript
  constructor(props) {
    this.fg
  }

  componentDidMount() {
    this.fg.zoom(5, 1000)
  }

  render() {
    return (
      <div>
        <ForceGraph2D
          ref={element => { this.fg = element }}
          graphData={this.props.graphState}
          width={this.w}
          height={this.h}
          backgroundColor="Gainsboro"
          onNodeClick={this.handleNodeSelection}
          nodeCanvasObject={this.drawNode}
          linkCanvasObject={this.drawLink}
        />
      </div>
      )
  }
```
It worked as expected, but since the upgrade from 1.26.4 to 1.29.3 this doesn't work anymore.

**Comment by vasturiano** [comment]
@xgaia, have you tried the same functionality but using React hooks? For example:
```
      const MyFg = () => {
        const fgRef = useRef();

        useEffect(() => { fgRef.current.zoom(5, 1000) }, []);

        return <ForceGraph2D
          ref={fgRef}
          graphData={this.props.graphState}
          ...
        />
      };
```

**Comment by xgaia** [comment]
Hello @vasturiano, thanks for you reply. The whole project use react classes, so we can't use hooks and we don't plan to rewrite classes to use hooks for now.

**Comment by vasturiano** [comment]
@xgaia I've pushed an update that should support class based components properly. Could you please pull the latest library version and let me know if it solves the issue for you?

**Comment by xgaia** [comment]
Hi @vasturiano, thanks for the update, its works as before !

thanks for your work on this package !
