### ISSUE TITLE
Orgainzing node label

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#145]
Hi!

I would like to style node labels (displayed upon hovering over the node) as attached in the image below (vertically aligned)
![Screen Shot 2019-12-12 at 5 02 43 PM](https://user-images.githubusercontent.com/22722805/70761288-90d0d780-1d01-11ea-931d-8280ae50397a.png)

**Current formatting** 
![Screen Shot 2019-12-12 at 5 02 54 PM](https://user-images.githubusercontent.com/22722805/70761335-afcf6980-1d01-11ea-9e42-a2f8d38f9600.png)

Thank you very much!

**Comment by vasturiano** [comment]
@Parul-Kudtarkar you can override the styling of the tooltips with your own css, by setting rules on the `graph-tooltip` class.

The default tooltip styling can be found here:
https://github.com/vasturiano/force-graph/blob/7d27f69984e38cfb1f001d562f0836399e812264/src/force-graph.css#L1-L11
