### ISSUE TITLE
Browser becomes unresponsive when there are large number of nodes

### ISSUE THREAD

**Issue by saurabhavid** [vasturiano/react-force-graph#146]
Hi @vasturiano ,

This is not sort of a bug, I might be doing something wrong on the implementation part.
When I get large number of nodes/links browser becomes unresponsive.

Need some help over this.

```js
    initializeChargeForce = () => {
        let fg = this.refs.fgref;
        fg.d3Force("center", null);
        fg.d3Force("charge", null);

        // Add collision
        fg.d3Force("collide", forceCollide(30));
    };

```

```js
<ForceGraph2D
    ref="fgref"
    graphData={this.graphData}
    dagLevelDistance={100}
    d3VelocityDecay={0.9}
    width={width || 1000}
    height={height || 500}
    nodeRelSize={15}
    nodeCanvasObject={({ id, name, highlight, img, imgd, x, y }, ctx) => {
        const size = 30;
        ctx.drawImage(
            !highlight && this.higlightedNode ? imgd : img,
            x - size / 2,
            y - size / 2,
            size,
            size
        );
    }}
    // nodeVisibility={node => !showOverprivileged && !hideUnconnected ? true : (showOverprivileged && node.shouldHiglightForOverpriveleged) || (hideUnconnected && node.unconnected)}
    nodeVisibility={node => !hideUnconnected
        ? (showOverprivileged ? node.shouldHiglightForOverpriveleged : true)
        : (showOverprivileged ? node.shouldHiglightForOverpriveleged && !node.unconnected : !node.unconnected)}
    linkVisibility={link => !hideUnconnected
        ? !showOverprivileged ? true : overprivilegedLinks.some(ol => ol.source === link.source.id && ol.target === link.target.id)
        : link.unconnected
            ? false
            : !showOverprivileged ? true : overprivilegedLinks.some(ol => ol.source === link.source.id && ol.target === link.target.id)
    }
    linkColor={link => !this.higlightedNode ? "rgba(150,150,150, 1)" : (this.highlightedLinks.some(hl => hl.source === link.source.id && hl.target === link.target.id) ? "red" : "rgba(150,150,150, 0.3)")}
    linkLabel={link => link.label}
    linkWidth={1}
    linkDirectionalArrowLength={5}
    linkDirectionalArrowRelPos={3}
    onNodeClick={this.highlightNode}
    onBackgroundClick={this.resetHighlightedNodes}
    onZoom={(z)=>{this.zoom = z.k}}
/>
```

**Comment by vasturiano** [comment]
@saurabhavid thanks for reaching out.
How many elements (nodes + links) do you have combined? Is it more than 75k? And how does the performance compare to this example: https://vasturiano.github.io/force-graph/example/large-graph/

To help debug further it would be useful if you can create a minimal example on https://codesandbox.io/

**Comment by saurabhavid** [comment]
Hi @vasturiano , Apologies for the late response.
I  have created an example here: https://codesandbox.io/s/reverent-rain-6nsnc 

Looks like when there are too many nodes in the same area, repelling each other out causes the issue.
I have also tried commenting the `await this.initializeChargeForce();` in `componentDidMount()` but no luck.

**Comment by vasturiano** [comment]
@saurabhavid  thanks for putting the example together.

You have about 6k elements in your data which should be doable.

I've tested your example and it doesn't make my browser unresponsive, but the nodes are coupled very close together. This is mainly due to your override of this prop: `d3VelocityDecay={0.9}`. Removing that setting achieves much better separation.

Also, another factor that's causing degraded performance is the image drawing in `nodeCanvasObject`. This is a more computationally intensive operation than the default node representation, therefore the graph becomes less fluid. Remember that this method is ran once for each node at each animation frame. To render 6k nodes while keeping a fluid 60fps would mean this method can take no longer than `3us` to run, which is why you see the lag. 
Falling back to the default node rendering considerably boosts the perceived performance, as you can see from this altered example:
https://codesandbox.io/s/tender-wildflower-jup3m

**Comment by saurabhavid** [comment]
@vasturiano Thanks for your response.

Removing images certainly improves the performance although in current scenario its required to render images on the nodes. Is there any other thing I can do to improve the performance? 

Also, If I change `d3VelocityDecay` to `0.1` rendering is bit smoother, but graph totally goes out of bounds and sometimes too far that zooming out doesn't help. How can I tackle such situation? :)

**Comment by vasturiano** [comment]
@saurabhavid you can try reducing the images resolution. I see that they are 200x200px but you're drawing them in a 30x30 size. Reducing the native size will possibly alleviate some of the computational load to render the images.

Regarding `d3Velocity`, the default value is `0.4`. Its intent is to impose a medium resistance that naturally slows down the nodes velocity. Lowering this value will make the nodes slide more easily but also affects the equilibrium of the system. Can you tell me what's your intent in modifying this setting?

**Comment by saurabhavid** [comment]
@vasturiano I reduced the image res to 30x30.

And regarding `d3Velocity`, overriding 0.1 caused nodes to flow freely and resulted in nodes going out of canvas bounds and performance gradually improved. But that's something I was just experimenting.

For now, I have halted the graph render if there's large number of data elements.

Thanks for your support. Really appreciate it!! :)
