### ISSUE TITLE
 react documentation for link styling suggests it only works for 2D

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#149]
**Describe the bug**
In the React README, the [link styling](https://github.com/vasturiano/react-force-graph#link-styling) table suggests that link styling props are only available for the 2D canvas version.

**To Reproduce**
1. Go to [link styling](https://github.com/vasturiano/react-force-graph#link-styling)

**Expected behavior**
Link styling applies to 3D, AR, VR versions as well as 2D

**Comment by vasturiano** [comment]
@JonThom thanks for reaching out. The other modes are marked as enabled for various link styling props.
You may be looking at a cut-off table on GitHub so some of the columns are not hiding, just scroll right and you'll see them. 👍
