### ISSUE TITLE
linkCurvature onLinkHover causes a hit box glitch.

### ISSUE THREAD

**Issue by GeoffGodwin** [vasturiano/react-force-graph#15]
Love this library, saved me some serious start up time on my current project!

While attempting to use the linkCurvature property in conjunction with the onLinkHover property I noticed that the curvature does not apply to the hit box of the hover. So although the line visually curves properly, hovering over the curved line will not trigger the onHover. However, hovering over the space where a straight link would be will fire the event as though the link is still straight.

Easy to reproduce using a curvature of .5 with onLinkHover.

**Comment by vasturiano** [comment]
Thanks the report @GeoffGodwin! There was a bug in the lib that wasn't respecting the link curvature on hover. Now fixed in the latest version (`1.5.1`).

**Comment by GeoffGodwin** [comment]
Awesome, works like a charm now, thank you again!
