### ISSUE TITLE
Expose canvas for external manipulation

### ISSUE THREAD

**Issue by GDownes** [vasturiano/react-force-graph#151]
Expose canvas for external manipulation. It would be useful to be able to manipulate the related canvas via a function like nodeCanvasObject. Exposing the underlying canvas object would simplify preforming additional canvas context actions.

My current desire is to use the new function to preform additional canvas context draw actions to add a colour key to the canvas.

Is there a simple way of performing additional canvas context actions I am missing?
Would others find this useful?
Does it fit into the wider ecosystem? I currently use force-graph via the react-force-graph wrapper.
Would the project be open to a related pull request submission to flesh out the idea?

**Comment by vasturiano** [comment]
@GDownes thanks for reaching out. 

The short of the story is that having access to the `canvas` object wouldn't help you much as it is continuously being wiped and redrawn. Additional elements related to the nodes/links can be added via the `nodeCanvasObject` and `linkCanvasObject` props.

There's some further reading on this subject at: https://github.com/vasturiano/force-graph/issues/53.

Also, does the `backgroundColor` prop solve your specific use case?

**Comment by GDownes** [comment]
Thanks for you reply.

My workaround is to use the nodeCanvasObject prop and conditionaly perform context actions on the first and last nodes using the nodes index.
