### ISSUE TITLE
 canvas width and height adaptable to screen size

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#153]
Is it possible to make canvas width and height adaptable to any browser/screen size?

Thanks!
Parul

**Comment by vasturiano** [comment]
@Parul-Kudtarkar you can use a responsive library that controls the canvas dimensions via the `width` and `height` props, for example: https://github.com/ctrlplusb/react-sizeme

**Comment by Parul-Kudtarkar** [comment]
Excellent! Thank you very much @vasturiano
