### ISSUE TITLE
use onNodeClick to update neighbours

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#154]
**Describe the bug**
Using a similar setup to the react [highlight](https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html) example, the goal is for onNodeHover to highlight not only the hovered node, but also its neighbors (stored in node.neighbors). 
However, only the hovered node is highlighted. 

**To Reproduce**
1. Go to the react [highlight](https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html) example and set it up to run locally.
2. Replace `const [data] = useState(genRandomTree(80));` with `const [data] = useState({nodes=[{"id":"node1","neighbors:["node2","node3"]}, {"id":"node2"),{"id":"node3"}], links=[{source:"node1", target:"node2"},{source:"node1", target:"node3"}])`
3. Replace `setHighlightNodes(node ? [node] : []);` with `setHighlightNodes(node ? [node.id, ...node.neighbors] : []);`
4. Set `nodeColor={(node => highlightNodes.indexOf(node.id) === -1? node.color  : 'rgb(250,215,80,1)')}`

**Expected behavior**
Upon hovering node1, all three nodes should be highlighted

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox
 - Version 72.0.2

**Comment by vasturiano** [comment]
@JonThom thanks for reaching out.

I'm not sure if that's the issue you're experiencing, but this section doesn't look like valid JavaScript:
```
useState({nodes=[{"id":"node1","neighbors:["node2","node3"]}, {"id":"node2"),{"id":"node3"}], links=[{source:"node1", target:"node2"},{source:"node1", target:"node3"}])
```

In general however, your idea is correct, this should be doable with the library. If you need more help, please create an example on https://codesandbox.io/ so it can be more easily debugged.

**Comment by JonThom** [comment]
@vasturiano thank you for the quick response - found the bug, so nothing to do, thanks anyway!
