### ISSUE TITLE
Add nodeOpacity and linkOpacity to 2D

### ISSUE THREAD

**Issue by hsluoyz** [vasturiano/react-force-graph#160]
I don't understand why this opacity feature exists in 3D, VR, AR but not in 2D? I think it's a commonly required feature.

**Comment by vasturiano** [comment]
@hsluoyz it could be added, no major reason why not. Just remember that this is merely a convenience method that applies to all nodes/links. The same can be done with `nodeColor` by add an alpha channel for example:
```
.nodeColor(() => 'rgba(0, 255, 0, 0.6)')
```

If you find it would still be useful to have the convenience prop, would you mind opening an issue on https://github.com/vasturiano/force-graph ?

**Comment by hsluoyz** [comment]
Thanks! I also found this solution. I think it already fits my need. Thanks!

**Comment by Chinmay-k96** [comment]
@hsluoyz  could you please share the solution
