### ISSUE TITLE
Can't turn off link particles once set

### ISSUE THREAD

**Issue by jumpinjackie** [vasturiano/react-force-graph#161]
**Describe the bug**

A mounted `ForceGraph2D` component with link particles set to some number doesn't turn them off if you change the `linkDirectionalParticles` prop to 0 or `undefined` afterwards as a result of some state change higher up.

Codesandbox that demonstrates the problem: https://codesandbox.io/s/dry-meadow-fsch5?fontsize=14&hidenavigation=1&theme=dark

This happens on the current release (1.31.0). I don't know what version introduced this bug, but my `package.json` diff shows that I upgraded `react-force-graph` from `^1.24.1`. So it's some release between those 2 versions.

**To Reproduce**

1. Visit above codesandbox link
2. Un-tick `Enable Particles` checkbox. Particles do not turn off
3. Tick/Un-tick `Toggle Link Color` checkbox. Link color updates properly (just to verify this problem is not affecting other link styling props)

**Expected behavior**

Setting `linkDirectionalParticles` to 0 or `undefined` turns off particles.

**Screenshots**

Refer to codesandbox link

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vasturiano** [comment]
Thanks for this report @jumpinjackie!

Turns out this was a big introduced in [v1.21.0](https://github.com/vasturiano/force-graph/commit/3956b4a865e42473314e6c04cdeb7fa8243485b9) of `force-graph` which is now fixed.

Please try with the latest version of `react-force-graph` (`v1.31.1`).

**Comment by jumpinjackie** [comment]
Yep, confirmed it is fixed in `1.31.1`. Thanks for the quick turnaround.
