### ISSUE TITLE
"Dashed lines" link rendering support

### ISSUE THREAD

**Issue by jumpinjackie** [vasturiano/react-force-graph#162]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to render 2d canvas graph links with a dashed pattern. Currently, the only way to do this AFAIK is to fully intercept the link rendering process with a fully custom link renderer so we have access to the canvas context and be able to call `setLineDash` before doing the regular canvas drawing calls. But doing this means we lose the declarative-ness of any other link styling properties set on the graph as we have to replicate all the internal link rendering behavior to ensure these properties are still respected (color/width/curvature/arrows/etc).

**Describe the solution you'd like**

A declarative `linkLineDash` prop on `ForceGraph2D` that if set, will map to the underlying `ctx.setLineDash(<value>)` canvas context call in the existing link rendering code where link color/width is being set up.

For max flexibility, the prop could either take `number[]` or `(link: any) => number[]` so the link object can drive whether it should be rendered solid or dashed.

**Describe alternatives you've considered**

A fully custom link renderer, but problems with this approach already mentioned above.

**Additional context**

N/A

**Comment by vasturiano** [comment]
@jumpinjackie I like your idea and I think it would be a useful addition. I agree with your design choice also of making it a link object accessor prop combo. It should also support link object attributes as strings, just like the existing ones.

Would you be willing to open a PR on https://github.com/vasturiano/force-graph for it?

**Comment by jumpinjackie** [comment]
I may have some time to give it a go

**Comment by vasturiano** [comment]
New prop `linkLineDash` exposed for the 2D mode. 👍 
A useful follow up would be to add the same functionality to the other `threeJs` modes, using https://threejs.org/docs/#api/en/materials/LineDashedMaterial.
