### ISSUE TITLE
Add support for additional mouse interaction - ctr/cmd/alt/shift + Click, box selection

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#163]
The current mouse interaction methods are great - but adding to the detected mouse events  would be really useful! (I'm building a graph database dashboard)

Proposed solution
* add ctr/cmd/alt/shift + Click detection
* add box selection 

Cheers!

**Comment by vasturiano** [comment]
@JonThom thanks for reaching out. 

For the key detection, you can check that from the `MouseEvent` parameter that is passed as part of the interaction callback methods, for example:
```
onNodeClick={(node, event) => {
  if (event.altKey) { /* alt key behavior */ }
  ...
}}
```

As for the box selection, that is a much more complex feature which warrants a separate discussion.  There was some talk about it here: https://github.com/vasturiano/3d-force-graph/issues/6

**Comment by JonThom** [comment]
@vasturiano thank you for the quick and helpful response. 

I look forward to making use of the `MouseEvent` parameter, very nice! 

(I would say you can close this issue)
