### ISSUE TITLE
Focus on a specific node programmatically for the 2d/3d?

### ISSUE THREAD

**Issue by haxoring** [vasturiano/react-force-graph#165]
**Is your featurea request related to a problem? Please describe.**
I need to update the node focus programmatically from another component.

**Describe the solution you'd like**
Implement "focusNode" that takes the id: name for the NodeObject or the linked target and then zoom in and render it. Like the onNodeClick callback function. 

**Additional context**
In the screenshot below i want to be able to click on the system ip and then zoom in on the object or the linked target.

![image](https://user-images.githubusercontent.com/49287826/78267464-4caf5000-7507-11ea-9859-d5688f459c70.png)

Thanks for an awesome component =)

**Comment by vasturiano** [comment]
@haxoring thanks for reaching out. Please see this [example](https://vasturiano.github.io/react-force-graph/example/click-to-focus/): https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html#L27

Basically you should move the viewport to the position that you wish using the `.cameraPosition` component method.

**Comment by haxoring** [comment]
Thanks for fast response!! yhee, the data needed was in the node object! 
const test = node.__threeObj.parent.children[0].__data;

I tried to changing the object color for the node
test.color = "#1f78b4";

It doesn't render?

Thanks

**Comment by vasturiano** [comment]
For changing node colors you should use:
```
nodeColor={node => ...}
```

**Comment by haxoring** [comment]
Thanks!!
