### ISSUE TITLE
How to update position of nodes

### ISSUE THREAD

**Issue by volkov-a-dev** [vasturiano/react-force-graph#172]
Hi, I have a question with how to correctly change the positions of nodes on a graph. Could you look at my example and tell me what I'm doing wrong?
https://codesandbox.io/s/competent-banzai-pupde?file=/src/ForceGraph3D.js

**Comment by vasturiano** [comment]
Something like:
```js
this.props.data.nodes.forEach(node => {
  node.x = 0;
  node.y = 0;
  node.z = 0;
})
```

As side note, `graphRef.current.d3Force` is used to add/edit the forces in the system, not access the simulation object, or the nodes themselves.
