### ISSUE TITLE
react-force-graph-vr depends on aframe@1.0.4 which pulls in packages from github

### ISSUE THREAD

**Issue by jonathan-irvin** [vasturiano/react-force-graph#175]
**Describe the bug**
react-force-graph-vr depends on aframe@1.0.4 which pulls in packages from github

**To Reproduce**
I'm using verdaccio/verdaccio for a npm proxy and discovered that react-force-graph-vr depends on a couple of dependencies that reference github hashes.  Despite my best efforts, I wasn't able to cache github hashes offline.

**Expected behavior**
Is there a way to rollback aframe to a version that satisfies this?

**Screenshots**
Here's the output of my `yarn list` 
[deps.txt](https://github.com/vasturiano/react-force-graph/files/4552398/deps.txt)

If you search for `#` you can see aframe and three-bmfont-text require pulls from github.
```
├─ aframe@1.0.4
│  ├─ custom-event-polyfill@^1.0.6
│  ├─ debug@2.2.0
│  ├─ debug@ngokevin/debug#noTimestamp
│  ├─ deep-assign@^2.0.0
│  ├─ document-register-element@dmarcos/document-register-element#8ccc532b7f3744be954574caf3072a5fd260ca90
│  ├─ load-bmfont@^1.2.3
│  ├─ object-assign@^4.0.1
│  ├─ present@0.0.6
│  ├─ promise-polyfill@^3.1.0
│  ├─ super-animejs@^3.1.0
│  ├─ super-three@^0.111.6
│  ├─ three-bmfont-text@dmarcos/three-bmfont-text#1babdf8507c731a18f8af3b807292e2b9740955e
│  └─ webvr-polyfill@^0.10.10
```

```
three-bmfont-text@2.3.0
│  ├─ array-shuffle@^1.0.1
│  ├─ inherits@^2.0.1
│  ├─ layout-bmfont-text@^1.2.0
│  ├─ nice-color-palettes@^1.0.1
│  ├─ object-assign@^4.0.1
│  ├─ quad-indices@^2.0.1
│  └─ three-buffer-vertex-data@dmarcos/three-buffer-vertex-data#69378fc58daf27d3b1d930df9f233473e4a4818c
```
**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by vasturiano** [comment]
@jonathan-irvin thanks for reaching out.

Since aframe is a deeper nested dependency of this package, it would probably be better to raise this issue in [that repo](https://github.com/aframevr/aframe), as they'd be able to provide more concrete answers.

But, have you tried changing the dependency resolution chain using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)?

**Comment by jonathan-irvin** [comment]
Hey @vasturiano, thanks for the tip! Yarn resolutions is a great tip! I also created an issue with aframe@1.0.4 https://github.com/aframevr/aframe/issues/4564
