### ISSUE TITLE
nodeVal resetting after state update

### ISSUE THREAD

**Issue by pbreinig** [vasturiano/react-force-graph#176]
I have 2 datasets and switch between them via state. I'm calculating the nodeVal based on how many links are targeted at a node. This is working correctly even when i switch the dataset with a state update. If i then switch back to the first dataset every node has the same size, even though the calculation of nodeVal is still working correctly.

```
<ForceGraph3D
    graphData={dataset}
    nodeVal={node => getNodeVal(node.id)}
    (...)
/>
```

```
const getNodeVal = (nodeId) => {
    let nodeVal = 1;
    for (let i = 0; i < dataset.links.length; i++) {
        if (dataset.links[i].target === nodeId) {
            nodeVal++;
        }
    }
    return nodeVal;
}
```

**Comment by vasturiano** [comment]
@pbreinig it's difficult to say without seeing the rest of the code. It may be related to which `dataset` you're referencing in your `getNodeVal` method.

Could you make a reduced example on https://codesandbox.io that reproduces the issue?

**Comment by pbreinig** [comment]
@vasturiano here's an example with the issue: https://codesandbox.io/s/loving-fire-t9u21?file=/src/App.tsx

**Comment by vasturiano** [comment]
@pbreinig thanks for making the example. 

I see what the issue is, it's in this line:
```js
if (dataset.links[i].target === nodeId) {
```

After initialization the link objects are converted to references to the node directly, instead of a nodeId. So your comparison never returns true after the first time you plot a set and that's why all the nodes have the same size (`1`). You just have to fix the comparison:

```js
if (dataset.links[i].target === nodeId 
   || (dataset.links[i].target.hasOwnProperty('id') && dataset.links[i].target.id === nodeId))
```

**Comment by pbreinig** [comment]
@vasturiano makes sense. Thank you so much!
