### ISSUE TITLE
ForceX,Y,Z handlers pass previous node data

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#177]
Case: I use EngineTick prop I set a `forceX `handler there, and When I modify the `nodes` for the graph(remove some elements), forceX handler runs and I have 1 cycle when I have previous nodes data, even if I set a `cooldownTicks` 0 and `cooldownTime` 0

**Comment by vasturiano** [comment]
@MaksZhukov this is probably related to the asynchronicity of the events. Whenever you change `graphData`, the data change is actually applied asynchronously after the component render.

If you need to make sure you do an operation after the data has changed (for example on `componentDidUpdate`) you can simply wrap it in a `setTimeout()` call.

**Comment by MaksZhukov** [comment]
@vasturiano Thank you!
