### ISSUE TITLE
Documentation Question: nodeVisibility and linkVisibility

### ISSUE THREAD

**Issue by HowardLander** [vasturiano/react-force-graph#180]
If I add functions to my ForceGraph3d to set the node and link visibility, then what parameters are passed to these functions when they are executed?

So if I have this:
ForceGraph3D graphData={data}
           nodeVisibility={this.props.nodeVisible}
           linkVisibility={this.props.linkVisible}
what should be the signature for the nodeVisible and linkVisible functions?

Alternatively can I set a property in each node or link to turn visibility off? If so, would this property just be "visibility"?

Thanks much
Howard

**Comment by HowardLander** [comment]
Hey I got it! Here's the solution for anyone else that gets confused:
 I added nodeVisibility={"visibility"} to my force graph definition.  Then in each node I set the visibility field.

Howard

**Comment by vasturiano** [comment]
Hi @HowardLander thanks for reaching out.

Yes, that is one way to do it. It's an accessor prop so you can use it in other ways too, for example:
```js
nodeVisibility={false}
nodeVisibility={node => node.someValue < 1}
```
