### ISSUE TITLE
How to keep custom geometry always face to user?

### ISSUE THREAD

**Issue by jediswear** [vasturiano/react-force-graph#183]
Hi! How can i keep custom node geometry alway face to user? Or how to update node rotation dynamically? I tried to set camera position to state, and then pass it to mesh.lookAt, but it doesnt work. Can u help?

```
  const graphRef = useRef();
  const [position, setPosition] = useState();

  useEffect(() => {
    if (graphRef.current) {
      const camera = graphRef.current.camera();
      setPosition(camera.position);
    }
  }, [graphRef.current]);
```

```
<ForceGraph3D
        ref={graphRef}
        graphData={graphData}
        nodeThreeObject={({ image }) => {
          const textureLoader = new THREE.TextureLoader();
          textureLoader.crossOrigin = "Anonymous";
          const myTexture = textureLoader.load(image);

          const material = new THREE.MeshLambertMaterial({
            map: myTexture,
            depthWrite: false
          });

          var geometry = new THREE.CircleGeometry(5, 32);
          var circle = new THREE.Mesh(geometry, material);

          if (position) {
            circle.lookAt(position);
          }

          return circle;
        }}
 />
```

**Comment by vasturiano** [comment]
If you want to have the objects always facing the camera, perhaps you need a [Sprite](https://threejs.org/docs/#api/en/objects/Sprite)?

**Comment by jediswear** [comment]
@vasturiano, thanks for your reply! i tried to use canvas as a texture for sprite, to make image rounded. But i wonder, is creating a new canvas texture for every node less performant, rather than usage of geometry with image texture?

**Comment by vasturiano** [comment]
@jediswear you can keep a reference to your Sprite object on your side and modify it whenever you wish.

Alternatively, you can just assign a new method to `nodeThreeObject` (possibly by extending the `[nodes]` dependencies argument in your `useCallback`) to trigger a regeneration of the node objects.

**Comment by jediswear** [comment]
@vasturiano thanks a lot!!! solution with references works nice for me!!
