### ISSUE TITLE
Export TypeScript types

### ISSUE THREAD

**Issue by wgpsutherland** [vasturiano/react-force-graph#189]
Hello. How are typescript types intended to be used, as LinkObject etc. are not exported and thus can not be used in function definitions? For example, I would like to do the following, however LinkObject is not exported:

```typescript
import { ForceGraph2D, LinkObject } from 'react-force-graph';

const handleLinkHover = (link: LinkObject) => {
        ... // do stuff with link
}

return <ForceGraph2D
    onLinkHover={handleLinkHover}
    ...
/>
```

 What is the recommended approach here? I would like to not have to define my functions as below, as this will quickly become messy:

```typescript
<ForceGraph2D
    onLinkHover={(link) => {
       ... // link is correctly typed here
    }}
    ...
/>
```

Thank you!

**Comment by vasturiano** [comment]
@wgpsutherland to get the `LinkObject` specific to the graph type you should import it from the specific module. So like:
```js
import ForceGraph2D, { LinkObject } from 'react-force-graph-2d';
```

**Comment by wgpsutherland** [comment]
@vasturiano thank you this is exactly what I wanted.
