### ISSUE TITLE
[TypeScript] - Generic Component w/ specific Node/Link types

### ISSUE THREAD

**Issue by wynch** [vasturiano/react-force-graph#196]
I'm playing with react-force-graph-2d & 3d.
I have my own graph data model, related to my own needs.
Types `NodeObject` and `LinkObject` are defined as intersection types with `object` 

It would be nice to be able to replace these unknown objects with a generics (e.g. : `<N>` for the nodes, `<L>` for the links ).
This way, I would get my own type fields on Component callback props

**Comment by ChuckJonas** [comment]
I also have this need... However, i think it would be reasonable if the generic types are still required to extend the concrete `NodeObject` & `LinkObject`...

Otherwise I imagine this would require a large rewrite.

eg 

```typescript
function ForceGraph2D<N extends NodeObject, L extends LinkObject>(props){
//...
}
```

**Comment by huw** [comment]
In the meantime you can work around this with module augmentation:

```ts
declare module "react-force-graph-2d" {
  interface NodeObject {
    id?: string | number;
    x?: number;
    y?: number;
    // other properties you want to access from `NodeObject` here
    label: string | null;
    // other properties you want to add to the object here
  }
}
```

Put this either directly in the file you’re importing from, or in `<name>.d.ts` in the root of your project.

**Comment by nathanpovo** [comment]
@vasturiano would you accept a PR that addresses this issue?
