### ISSUE TITLE
Access to Three.js renderer

### ISSUE THREAD

**Issue by Benkevych** [vasturiano/react-force-graph#2]
Is there any possibility to access scene renderer from my component?
I need to add a shadow to my graph, and add a parameter `{ antialias: true }` to make it less sharp.

**Comment by vasturiano** [comment]
@Benkevych the current renderer is not exposed at this abstraction level. Basically, `3d-force-graph` just provides a set of defaults for the renderer/camera/scene three.js scaffolding around [three-forcegraph](https://github.com/vasturiano/three-forcegraph). If you need to run it with a more customized render, I'd definitely recommend consuming from that lower-level module directly and roll your own renderer, camera, etc by bypassing the `3d-force-graph` abstraction. That will give you the maximum amount of flexibility for your specific case.
