### ISSUE TITLE
How to use postProcessingComposer?

### ISSUE THREAD

**Issue by diragb** [vasturiano/react-force-graph#201]
Hey, I was really struggling with figuring out how to implement an Unreal Bloom post processing to my graph. I've tried it on vanilla 3d-force-graph, but I have no clue how to accomplish this with react-force-graph.

Here's my code:
`const App = () => {
  const GData = [...jsonData];

  return (
    <div>
      <ForceGraph3D
        graphData={GData}
        nodeLabel="id"
        nodeAutoColorBy="group"
        linkColor="#dfe6e9"
        linkOpacity={0.05}
        linkCurvature={Math.random()}
        linkCurveRotation={(Math.random() * 360)}
        cameraPosition={[{ z: 8000 }]}
        enableNodeDrag={false}
      />
    </div>
  );
};`

**Comment by vasturiano** [comment]
@diragb I just created an example on how to use the bloom post processing effect in `react-force-graph`: https://github.com/vasturiano/react-force-graph/blob/master/example/bloom-effect/index.html

**Comment by diragb** [comment]
if there is a god, i hope he takes away my own blessings and showers them over you, good sir. ❤️
