### ISSUE TITLE
Improving performance for extremely large datasets

### ISSUE THREAD

**Issue by diragb** [vasturiano/react-force-graph#202]
hey, i'm attempting to display a large dataset (117,927 nodes and 117,921 links), but WebGL runs out of memory after the first few seconds. is there any way to optimize the model or the animation to reduce/eliminate crashes, fps throttling, memory hogging?

<img width="856" alt="Screenshot_5" src="https://user-images.githubusercontent.com/36959928/87232413-79afb080-c3dc-11ea-96ac-b55ecbaa40a0.png">

<img width="349" alt="Screenshot_6" src="https://user-images.githubusercontent.com/36959928/87232419-80d6be80-c3dc-11ea-947d-6c68ae8bbc5a.png">

**Comment by diragb** [comment]
used the 3rd advice from #181 of setting warmupTicks={100} and cooldownTicks={0}, also turned off bloom postprocessing. it's working now, but the fps is still choppy + it took around 5 minutes before i could see the structures (it was a white screen before that).

<img width="915" alt="Screenshot_8" src="https://user-images.githubusercontent.com/36959928/87233037-681cd780-c3e1-11ea-880c-ac88580f7c83.png">

**Comment by diragb** [comment]
a little good news, the structure finally renders with the post-processing
it's still very laggy though (due to obvious reasons), and takes a long time to load (5-7 mins)

here are some snaps!

<img width="960" alt="Screenshot_14" src="https://user-images.githubusercontent.com/36959928/87235692-36653a00-c3fc-11ea-91ba-e63b0c79d34a.png">
<img width="950" alt="Screenshot_12" src="https://user-images.githubusercontent.com/36959928/87235695-3d8c4800-c3fc-11ea-98e9-bc652b8260fb.png">
<img width="498" alt="Screenshot_13" src="https://user-images.githubusercontent.com/36959928/87235697-42e99280-c3fc-11ea-9059-d33991bf1b38.png">

**Comment by vasturiano** [comment]
@diragb those screenshots look stunning!

You're probably pushing your hardware to its limits by rendering so many objects. 😄 
I think the main things that you could do to alleviate the pressure is to simplify the objects themselves. A few examples I can think of:
* Not using curved lines. Straight lines are simpler objects.
* Reducing the resolution of the spheres, using `.nodeResolution`.
* Also the less post processing effects you have, the easier it is but I see you already tries deactivating the bloom pass filter.

**Comment by diragb** [comment]
hey, i used your suggestions and there was a moderate performance boost. i'll be using a few of my friends' powerful computers to render the model and hopefully take a few videos of it. i'm closing this issue now, i'll be commenting a link of our video (i'll credit you) as soon as it's done. thanks for the help!

**Comment by TheAussieStew** [comment]
> hey, i used your suggestions and there was a moderate performance boost. i'll be using a few of my friends' powerful computers to render the model and hopefully take a few videos of it. i'm closing this issue now, i'll be commenting a link of our video (i'll credit you) as soon as it's done. thanks for the help!

This looks pretty cool. Would you be able to share the source for the bloom post processing by any chance? I'm having trouble getting it to work.

**Comment by vasturiano** [comment]
@TheAussieStew there is an [example of it here](https://vasturiano.github.io/react-force-graph/example/bloom-effect/).

Relevant code:
https://github.com/vasturiano/react-force-graph/blob/153ab1f69604a9ea9536bb5331e340eaa5801248/example/bloom-effect/index.html#L28-L34

**Comment by TheAussieStew** [comment]
Ah thank you! I looked at that example but I'm having trouble getting useRef to work with Typescript. Looks like I'll just have to experiment.

**Comment by diragb** [comment]
### a meaningful update.

me and my friends used this library and made this [video](https://youtu.be/arztTjiVw2I) some time back.

this 3d graph only had around 10k to 20k nodes. some of the issues, as i mentioned here, were FPS drops. to fix this issue, we used an open source AI project that transforms low FPS footage to high FPS (DAIN) -- however this proved to be problematic since there were lots of artifacts.

eventually, we settled on producing this video with the shoddy footage and calling it a day. it was only a month later that we thought about timelapse-ing the whole project. so, essentially, i wrote a small script with rotated + panned + zoomed on the graph extremely slowly, slapped on OBS recorder on top of it, recorded for an hour and sped up the footage by 10x to 100x. the result was nothing short of fascinating.

we still haven't released this footage yet, because we got distracted and might work on it in the furure, but to anyone else wanting to make a video on extremely large 3d graphs using this library -- **this is the best way you can do it**, and the results will be insanely beautiful.

i'll add a short video clip soon, once i get hold of my old hard drive. :)
