### ISSUE TITLE
Select node in 3d graph without restarting simulation

### ISSUE THREAD

**Issue by devDesu** [vasturiano/react-force-graph#21]
I'm trying to implement node selection in ForceGraph3D component.
As I can see, every time I'm calling setState(), graph restarts physics simulation even if graph data wasn't modified. 
Part of code which shows selected links
`linkWidth={link => this.state.DataProvider.isSelectedLink(link) ? 3 : 1}`
Following code works pretty well and all needed links are changing their width, but graph also restarts physics simulation and all nodes are jumping and oscillating
If I'm not calling setState() and just update selected links in my DataProvider class, I can't see any changes in the graph

Without react bindings I've achieved pretty good effect just calling (without simulation restart on select)
`Graph.nodeRelSize(this.relSize);`

**Comment by devDesu** [comment]
Looks like it's not graph issue, but react component issue, because after setState were called react calls render() and component updates.
So am I able to update only graphics without physics?

**Comment by vasturiano** [comment]
@devDesu only the props that change value are propagated to the component. If the component always reheats the force simulation, could it be that one of the props you're passing to the component is changing value at every render?

**Comment by GeoffGodwin** [comment]
@devDesu to get around this behavior in a 2D graph I construct the graph in my render method, place it into a constant variable then insert that constant into the return structure JSX. I believe the reason this works is that React maintains a key on that object and knows not to re-render the entire component each time.

**Comment by devDesu** [comment]
I was able to fix this problem using special update method
`update(full=true) {
  if(full) 
    this.setState({cooldownTicks: 15000})
  else
    this.setState({cooldownTicks: 0})
}`
