### ISSUE TITLE
manage mouse wheel zoom 

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#212]
Ho can I manage mouse wheel zoom in 3D?
The task is I need to sync zoom with buttons and zoom with mouse wheel

**Comment by vasturiano** [comment]
@MaksZhukov you can access the camera controls via the `.controls()` ref method.

Assuming you're using the default Trackball controls you can integrate / configure those interactions to suit your app.
Docs here: https://threejs.org/docs/#examples/en/controls/TrackballControls

**Comment by MaksZhukov** [comment]
Thanks
