### ISSUE TITLE
Gettin a lot of warnings: can't invert matrix, determinant is 0

### ISSUE THREAD

**Issue by bayerlse** [vasturiano/react-force-graph#215]
**Describe the bug**
The console is bombed by following message: `aframe-master.js:9074 THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0` which lead to performance break down

**To Reproduce**
I tried your [example](https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-3d.html) with 3d text nodes. And if the nodeRenderer is active, the mass of warnings appears. If I dont set the nodeRenderer prop. All is working fine.

**Expected behavior**
No warnings when Sprite texts

**Desktop (please complete the following information):**
 - OS: MacBook
 - Browser chrome
 - Version 1.36.7

Thanks!

**Comment by vasturiano** [comment]
@bayerlse thanks for reaching out.

I'm not able to reproduce the issue. Could you perhaps create a [sandbox](https://codesandbox.io/) that triggers this so it can be debugged further?

Also, by `nodeRenderer` do you mean `nodeThreeObject`?

One thing that may be worth checking is if you have a single version of `three` in your dependency chain. It's a bit of a long shot, but if you do it can certainly cause some of these issues.

**Comment by bayerlse** [comment]
Hey @vasturiano 

Thanks for your answer. I cant really tell what caused the issue, but it seems your guess about the three.js version was right. After reinstalling all necessary packages for my application, the warning disappeared.

**Comment by bayerlse** [comment]
Hello again @vasturiano 
Sorry I was wrong with saying three js version fixed.

I still get the error, but just when using nodeThreeObject with [sprite-text](https://github.com/vasturiano/three-spritetext):

` const nodeThreeObject = useCallback(node => new SpriteText(node.name))`

If I render any other Object3D no warnings appear. But with sprite-text i get:

`aframe-master.js:9074 THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0`

**Comment by vasturiano** [comment]
@bayerlse glad to hear fixing the dependencies fixed the issue at least to some extent.
In the cases when you are still getting the error, can you confirm that you have a single version of `three` in your dependency tree?
And have you been able to reproduce the error on https://codesandbox.io/?

**Comment by bayerlse** [comment]
Hey @vasturiano Thanks for your answer. 

Yes, I just have one version three.js and thats the same you're using in your package: 0.118.3

Actually I tried to put it to codesandbox. But as soon as I set the nodeThreeObject prop to my renderTextNode function, codesandbox gets frozen. I added a screenshot of the code. Hope this is also ok. Because if you go to [codesandbox-example](https://codesandbox.io/s/compassionate-sound-fy5b6?file=/src/App.js) it gets frozen.

For data I used the same as in your [example](https://github.com/vasturiano/react-force-graph/blob/master/example/datasets/miserables.json) 

![Bildschirmfoto 2020-09-25 um 14 10 05](https://user-images.githubusercontent.com/38108896/94266246-27d9e980-ff3a-11ea-902c-82d35265e19c.png)

**Comment by vasturiano** [comment]
@bayerlse I think I understand the reason why that is happening. 
For the short version fix, just convert your `ForceGraph3D` import to the isolated package:
```
import ForceGraph3D from 'react-force-graph-3d;
```
instead of
```
import { ForceGraph3D } from 'react-force-graph;
```

The underlying reason is that the bundled package includes a version of A-Frame, which by itself includes a custom version of ThreeJs (`0.111.6`). That is a separate instance of Three than what's imported with `three-spritetext`. And the two versions are conflicting (`ThreeJs` likes to be a single global) therefore generating the console warnings.
