### ISSUE TITLE
Example of using with custom react components?

### ISSUE THREAD

**Issue by AdityaAnand1** [vasturiano/react-force-graph#217]
Is there a demo or example of using custom react components as force graph nodes?

**Comment by vasturiano** [comment]
@AdityaAnand1 the graph nodes are really [ThreeJs](https://threejs.org/) objects, and they are based around WebGL functionality, not DOM objects. React is used to manipulate a DOM structure not WebGL so the two items are in fact incompatible.

**Comment by boostpaal** [comment]
As @AdityaAnand1 said, this library paints three.js objects, so there is no direct way of painting HTML elements. There are some options, but it's not trivial:

### 1. Convert your rendered HTML to an image and paint it:
```
const imgTexture = new TextureLoader().load('/images/some-image.png');
const material = new SpriteMaterial({ map: imgTexture });
const sprite = new Sprite(material);
sprite.scale.set(12, 12, 12);
return sprite;
```

2. Position your React component with absolute positioning, using methods like `screen2GraphCoords` from ForceGraph3D.
