### ISSUE TITLE
Loading data from a state manger 

### ISSUE THREAD

**Issue by jminnick** [vasturiano/react-force-graph#22]
@vasturiano have you tried any examples loading from a state manager like Mobx or Redux? Getting some errors populating data from a Mobx observable variable.

`warning.js:33 Warning: Failed prop type: Invalid prop `graphData.nodes` of type `object` supplied to `ForceGraph2D`, expected an array.`

Looks like rendering the data gets caught in a wonky state.

**Comment by vasturiano** [comment]
@jminnick that seems like an issue with the structure of the data passed to the component. Have you checked that it follows this syntax:
```
{
    "nodes": [ 
        { 
          "id": "id1",
          "name": "name1",
          "val": 1 
        },
        { 
          "id": "id2",
          "name": "name2",
          "val": 10 
        },
        (...)
    ],
    "links": [
        {
            "source": "id1",
            "target": "id2"
        },
        (...)
    ]
}
```

More specifically, make sure the `nodes` property is an `array` and not an `object`.

**Comment by jminnick** [comment]
thanks for the quick reply @vasturiano . The data I am using is from example.

```javascript
this.stixBuilderData = {
        "nodes": [
            {
              "id": "id1",
              "name": "name1",
              "val": 10
            }, {
              "id": "id2",
              "name": "name2",
              "val": 10
            }
        ],
        "links": [
            {
                "source": "id1",
                "target": "id2"
            }
        ]
    }
```
I was able to get it worked out with the following. Mobx does some data mutation to add getters/setters so it had to be converted back to raw JS.

Here is the link in case this trips anyone else us. 

https://stackoverflow.com/questions/43166411/mobx-returning-observableobjectadministration-instead-of-my-object

**Comment by vasturiano** [comment]
Ah yes, that makes sense. The data should be a standard JS structure and not a wrapper class of some kind with custom getter/setters, like an immutable. So, converting it to plain JS is the key.
