### ISSUE TITLE
loop nodeCanvasObject

### ISSUE THREAD

**Issue by Karpig** [vasturiano/react-force-graph#221]
Hello, when I use the nodeCanvasObject method, I see it running endlessly in the console, is that how it should be?

I tried the [original example](https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-2d.html ) and this problem is present there too.
p.s. - Sorry for my English

**Comment by vasturiano** [comment]
@Karpig yes, that is expected, and by design. The canvas is repainted at every frame and this is how the nodes positions are updated. Therefore, the `nodeCanvasObject` needs to be re-invoked at every paint iteration to draw the nodes accordingly.

**Comment by Karpig** [comment]
Thanks for your reply!
