### ISSUE TITLE
Force Graph Zoom, Click, and Move does not work when Width and Height are set

### ISSUE THREAD

**Issue by samhincks** [vasturiano/react-force-graph#224]
I want to create a data interface where the Force Graph is one of several components, so I have set its width and height to be 400px, and included a different component containing React buttons beneath it. But when I set the width and height, the Force graph properties stop working. (They work fine when the Force graph gets to take up the whole screen.)

To reproduce this bug, create a multi component React App, like this:
```
<div className="App">
      {kgData &&
        <ForceGraph2D
          graphData={kgData} linkSource={"_from"} linkTarget={"_to"}
          nodeId={"_id"} nodeLabel={"_name"}
          width={400}
          height={400}

          nodeColor={(x) => {
            if (x._id.startsWith("tokens")) return "green";
            else return "orange"
          }} >
        </ForceGraph2D >}
      <BelowCenter>
        <div className={classes.root}>
          <Grid container spacing={3}>
            <Grid item xs={12}>

              <Button key="Decide"
                onClick={(e) => console.log("clicked")}
                color="primary"
              > 
.... 
```
![image](https://user-images.githubusercontent.com/2828596/93022102-5aedb600-f5e7-11ea-9a26-c69f57fd3834.png)

I appreciate the resolution of this bug, as something I'm doing wrong or a fix to the code. This is an excellent open source project ! :)

**Comment by vasturiano** [comment]
@samhincks thanks for reaching out.

There shouldn't be any issue with having `width` and `height` props on the force graph. The component should run fine inside a container like that. 
So, it's not clear why (and how) it's misbehaving in your case. Could you please do a simple reproducing example on [code sandbox](https://codesandbox.io/) so it can be debugged further?

**Comment by samhincks** [comment]
Here you go! https://codesandbox.io/s/wild-darkness-dj1nb?file=/src/App.js

`import React from "react";
import "./styles.css";
import { ForceGraph2D } from "react-force-graph";

export default function App() {
  let data = {
    nodes: [
      {
        id: "id1",
        _name: "name1",
        val: 1
      },
      {
        id: "id2",
        name: "name2",
        val: 10
      }
    ],
    links: [
      {
        source: "id1",
        target: "id2"
      }
    ]
  };

  return (
    <div className="App">
      <ForceGraph2D graphData={data} width={400} height={400} />
    </div>
  );
}`

**Comment by vasturiano** [comment]
@samhincks thanks for making the example.

The issue lies in your `styles.css`.  You are centering the graph element using `text-align: center`, but that is applicable to text/inline elements, not block elements like the graph. This is leading to miscalculations of the container size/position (using [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect)), and by consequence misleading mouse position measurements.

If you replace your centering styles with the following, you should be good:
```
  display: flex;
  justify-content: center;
```

**Comment by samhincks** [comment]
Thanks, this fixed it!
