### ISSUE TITLE
react-force-graph is there a way to not always re-render the graph when I want to change a node color

### ISSUE THREAD

**Issue by czanbaka** [vasturiano/react-force-graph#226]
I am using ForceGraph2D to visualize a network where the state of each node is depicted by its color. The nodes are constantly changing color, but the links/network structure does not change. Here is my code:

const NodeGraph2 = (props) => {

    var { nodes, subnets, nodeStatuses } = props;

    const links = useMemo(() => {
      var newLinks = []

      subnets.forEach( (s) => {
        var nodesCopy = s.nodes;
        s.nodes.forEach( (a, i) => {
          nodesCopy.forEach((b, j) => {
            if(i !== j)
            {
              newLinks.push({
                source: a,
                target: b,
              })};
            })
          })
        });
        return newLinks;
    }, [subnets]);

    const graphNodes = useMemo(() => {
      return nodes;
    }, [nodes]);

    const getNodeLabel = (node) =>
    {
      return node.id + " " + node.nodeNetworkType + " " + node.nodeStatus;
    }

    const renderNode = (node, ctx) => {
      let color = getColorFromStatus(nodeStatuses, node.nodeStatus);
      let lenght = node.addresses.length
      let size = Math.log(lenght) + lenght;
      ctx.fillStyle = color;
      if(node.nodeNetworkType.toUpperCase() === "HOST")
      {
        ctx.beginPath(); 
        ctx.arc(node.x, node.y, size*2, 0, 2 * Math.PI, false); 
        ctx.fill(); 
      }
      else{
        ctx.fillRect(node.x - size, node.y - size, size*2, size*2);
        ctx.fill();
      }
    }
   
    return (<ForceGraph2D graphData={{nodes: graphNodes, links: links}} 
                          nodeLabel={node => getNodeLabel(node)}
                          nodeCanvasObject={renderNode}
                          />);       
}

The nodes prop is constantly updating (from GraphQL) but I only want to change the color and not re-render the entire graph, any ideas?

@vasturiano

**Comment by czanbaka** [comment]
Ohhh, I might have figured it out, but not using the react component, so if you have a way of doing this with the react component let me know, but here is what I did.


var nodeGraph = null;

const NodeGraph2 = (props) => {

    var { nodes, subnets, nodeStatuses } = props;

    const data = useMemo(() => {
      var links = [];

      subnets.forEach( (s) => {
        var nodesCopy = s.nodes;
        s.nodes.forEach( (a, i) => {
          nodesCopy.forEach((b, j) => {
            if(i !== j)
            {
              links.push({
                source: a,
                target: b,
              })};
            })
          })
        });
        const gData = {nodes: nodes, links: links}
      return gData;
    }, [nodes, subnets]);

    const getNodeLabel = (node) =>
    {
      let actualNode = nodes.find(n=> n.id === node.id);
      return actualNode.id + " " + actualNode.nodeNetworkType + " " + actualNode.nodeStatus;
    }

    const renderNode = (node, ctx) => {
      let actualNode = nodes.find(n=> n.id === node.id);

      let color = getColorFromStatus(nodeStatuses, actualNode.nodeStatus);
      let lenght = node.addresses.length
      let size = Math.log(lenght) + lenght;
      ctx.fillStyle = color;
      
      if(node.nodeNetworkType.toUpperCase() === "HOST")
      {
        ctx.beginPath(); 
        ctx.arc(node.x, node.y, size*2, 0, 2 * Math.PI, false); 
        ctx.fill(); 
      }
      else{
        ctx.fillRect(node.x - size, node.y - size, size*2, size*2);
        ctx.fill();
      }
    }

    if(nodeGraph == null) {
      $(document).ready( function() 
      {
        nodeGraph = ForceGraph()
          (document.getElementById('newNodeGraph'))
                    .nodeCanvasObject(renderNode)
                    .nodeLabel(getNodeLabel)
                    .graphData(data);
      })
    }
    else
    {
      nodeGraph.nodeCanvasObject(renderNode)
               .nodeLabel(getNodeLabel)
    }

    return (<div id="newNodeGraph"></div>);       
}

**Comment by vasturiano** [comment]
@czanbaka thanks. for reaching out.

It's difficult to say for sure without a reproducing example, but if you're experiencing unwanted re-renders due to data object changes, it's probably a matter of adapting your memoizing logic to ensure that the data object references remain the same across re-renders. So the component can update only for the props that did change.

**Comment by czanbaka** [comment]
@vasturiano thanks! I adapted my momoizing logic as you suggested and that worked!
