### ISSUE TITLE
node question

### ISSUE THREAD

**Issue by jminnick** [vasturiano/react-force-graph#23]
@vasturiano is it possible to use an image for a node as opposed to the default circle?

**Comment by jminnick** [comment]
I appear to be asking questions too quickly, lol. I have the images figured out, thanks. 

However, one thing I am still having trouble with is starting a graph with no nodes and adding new ones dynamically. Is this possible?

**Comment by GeoffGodwin** [comment]
The graph object has a prop "graphData" which takes a JSON object of the following structure:

```
graphData: {
  nodes: [],
  links: []
}
```
Where the nodes array is comprised of JSON objects like this:
```
{
  id: int,
  name: string,
  val: int
};
```
and the links array contains JSON objects like this:
```
{
  source: Object,
  target: Object
}
```
where both the source and target are node objects which exist in the links array.

You construct the above structure using whichever algorithm you'd prefer, then feed it into the Graph object at render. I keep this graphData prop in my local state, then with modifications I simply reconstruct it and let a re-render occur.

It is also nice to note that if you so choose you can add additional properties to the node and link objects for your own purposes. Personally I keep a lookup of my nodes and links separately to avoid passing some needlessly enormous object full of extraneous data into the Graph.

Hopefully this helps!
