### ISSUE TITLE
combine image and text in a single sprite?

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#230]
**Is your feature request related to a problem? Please describe.**
In the 3D graph I am trying to combine images and text in a single sprite (by following the official examples). 

I have tried to use a group:
```
nodeThreeObject={(node => {  
    // text sprite
    const spriteText = new SpriteText(node.id);
    spriteText.color = node.color;
    spriteText.textHeight = 3;
    
    // image sprite
    var map = new THREE.TextureLoader().load("https://picsum.photos/100/100/?random"); 
    map.minFilter = THREE.LinearFilter;
    const material = new THREE.SpriteMaterial( { map: map } );
    const spriteImg =  new THREE.Sprite( material );
    spriteImg.scale.set(9,9,1)

    // combine the sprites as a group
    var group = new THREE.Group();
    group.add( spriteText );
    group.add( spriteImg );
    
    return group })}
```

I have also tried to use the `add` method on one of the sprites with the other sprite as argument.

However, mouse interaction doesn't work well (only one of the sprites can be clicked, the two sprites come apart when dragging one).                            

**Describe the solution you'd like**
It would be great with an idea on how to combine the image and text sprites.

**Describe alternatives you've considered**
I've considered first make the text label into a second image (e.g. using the HTML5 canvas) and then combining the two images into one, and make that into a sprite. I haven't tried to implement this yet as it feels quite impractical.

**Comment by vasturiano** [comment]
@JonThom thanks for reaching out.

I just published a module update that should fix your issue. Could you please try your example with `v1.18.8` and see if it's fine?

There is a deeper dive into the fix in [this issue](https://github.com/vasturiano/3d-force-graph/issues/395) if you're looking for more info.

**Comment by JonThom** [comment]
@vasturiano super - that did the trick! 
(good job solving before the issue was posted! ;) )
