### ISSUE TITLE
How can we create an icon sprite in 3D graph?

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#232]
**Describe the bug**
In the 2D graph, it is possible to paint an icon on the canvas within `nodeCanvasObject`:
I would like to find out how to use icons in sprites in the 3D graph. 
The current attempt, below, does not show the sprites upon initial render, and the graph crashes when adding new nodes and links.

**To Reproduce**

In 2D, the following will add icons as nodes:

```
const script = document.createElement('script');
script.src = "https://kit.fontawesome.com/a6e0eeba63.js";
script.async = true;
document.body.appendChild(script);
```

and then give ForceGraph3D the following nodeCanvasObject:

```
nodeCanvasObject={(node, ctx, globalScale) => {
ctx.font = '10px FontAwesome'
ctx.fillText('\uF1AD', node.x, node.y-size/2, size);
})}
```

In 3D, I've attempted to draw the icon to canvas and convert them to sprites:

```
nodeThreeObject={(node => {    
    // draw icon on canvas
    const canvas = document.createElement('canvas');
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#ff0000';
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.font = '10px FontAwesome'
    canvas.width = 100;
    canvas.height = 100;
    ctx.fillText('\uF1AD', 0,0);

    // convert canvas to sprite
    const map = new THREE.CanvasTexture(canvas);
    const material = new THREE.SpriteMaterial( { 
                                map: map } );
    const spriteImg =  new THREE.Sprite( material );
    return spriteImg})}
```

**Expected behavior**
See icon sprites as nodes

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser : Firefox

**Additional context**
I can set up an example if required, but thought someone might have tried something similar and be able to spot the problem.

**Comment by vasturiano** [comment]
@JonThom I was able to load the icons in 3D mode, using [three-spritetext](https://github.com/vasturiano/three-spritetext) for convenience.
Made a codepen here:
https://codepen.io/vasturiano/pen/mdErVjW

Perhaps the issue lies with the method of loading the FontAwesome fonttype on the page? It appears it can have a race condition and the fonttype may not yet be available at the time that the sprite object is created. Just a guess.

**Comment by JonThom** [comment]
I was able to get it to work using three-spritetext (don't know why I couldn't earlier!)
I'm generating the sprite with a memoized function. 
Much appreciate the help!
