### ISSUE TITLE
Nodes get unlinked from their edges when merging graph data

### ISSUE THREAD

**Issue by Kryptiique** [vasturiano/react-force-graph#234]
**Describe the bug**

I have a system that periodically (in testing, I've set it to every 15s) receives graph updates from a server. In order to prevent existing nodes from jumping around, I have implemented a mechanism that locks nodes in the graph while new data comes in, then waits 10 or so seconds for the simulation to cool before unlocking all the nodes. The quirk is that, when certain nodes are selected, the graph freaks out and unlinks all nodes from their edges, making them explode in all directions. The edges themselves stay where they are, and when new data comes with the next update, they all reattach themselves to their respective nodes.

I've managed to narrow down the cause of bug to when selecting a node, and auto sync and freezing has occurred at least once. I have not managed to figure out which nodes cause this behavior to happen.

**To Reproduce**

Here is my logic for merging data:

```javascript

function setD3Data(new_graph, merge){
  const { d3Data } = this.state

  // Convert lists to dicts to ensure unique nodes;
  // Using _.uniqBy made the graph unstable
  var d3DictGraph = {
    nodes: !merge ? {} : _.mapValues(_.keyBy(d3Data.nodes, 'id')),
    links: !merge ? {} : _.mapValues(_.keyBy(d3Data.links, 'id'))
  }
  
  var merged_graph = _.cloneDeep(new_graph)
  merged_graph.nodes = Object,values(_.merge(d3DictGraph.nodes, new_graph.nodes))
  merged_graph.links = Object.values(_.merge(d3DictGraph.links, new_graph.links))

  this.setState({ d3Data: merged_graph })
}
```

Here is my logic for locking/unlocking nodes:

```javascript
export function toggleSyncLock(graph, freeze){
  let processed_graph = _.cloneDeep(graph)

  processed_graph.nodes.forEach(node => {
    if(freeze){
      // only lock nodes that haven't been locked by user
      if (node.fx === undefined){
        node.fx = node.x
        node.fy = node.y
        node.fz = node.z
        node.syncLocked = true
      }
    } else {
      if(node.syncLocked !== undefined){
        delete node.syncLocked
        node.fx = undefined
        node.fy = undefined
        node.fz = undefined
      }
    }
  })

  return processed_graph
}
```

Node selection does not change the state of the graph, merely changes the rendering of a single node.
```javascript
  // nodeCanvasObject function:
  if (selectedItem && (selectedItem.id === id)){
      ctx.beginPath(); 
      ctx.arc(node.x, node.y, radius * 1.4, 0, 2 * Math.PI, false);
      ctx.fillStyle = theme.background + 'b9'
      ctx.fill();
    }
```

The project itself is quite large, so I'm sure there is something I am missing here that can't be reproduced with the functions I've provided. At the very least, this is what I believe is the bulk of the related code. There is some use of a local cache to store the graph, but the logic for merging graphs between current and cached states is nearly identical, with the exception being that I store the graph lists as dicts keyed by the `id` of the nodes instead of converting them into lists.

**Expected behavior**
I expect the nodes to not be unlinked from their edges. This is true the majority of the time, but not always. I read in [this post](https://github.com/vasturiano/react-force-graph/issues/157) that the nodes must be the exact same instance, so my best guess is that in some cases the nodes aren't merged to be the exact same every time.

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/8742491/98174442-e8040b80-1ec2-11eb-874d-5bbe8e6a4c6b.png)

After:
![image](https://user-images.githubusercontent.com/8742491/98174537-08cc6100-1ec3-11eb-9dfd-34057d4d4a0b.png)

I've also recorded a video of the behavior and posted it on my google drive which you can find [here](https://drive.google.com/file/d/1pK6_jbjBJ94KUxh14_Rsclt0Qq3rg2jO/view?usp=sharing).

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome
 - Version [react-force-2d 1.15.1]

**Additional context**

**Comment by vasturiano** [comment]
@Kryptiique thanks for reaching out.

For the practicality of debugging, it's easier if you create a live reproducing example, for instance on https://codesandbox.io/.
Otherwise the realm of possibilities is just too vast to provide any kind of informed feedback on how to go about solving the issue.

**Comment by Kryptiique** [comment]
Hm, it will take some time to isolate and put it on codesandbox but I will see what I can do

**Comment by stultusstudio** [comment]
I think I'm having a similar issue. I've created a codesandbox to demonstrate.

**Comment by Kryptiique** [comment]
I took a break from resolving this issue for a while, but it turns out my issue was exactly as described in #236.
