### ISSUE TITLE
Adding objects to the scene in 3D Force-Directed Graph in VR

### ISSUE THREAD

**Issue by afermeli** [vasturiano/react-force-graph#235]
Hi, I noticed that the Graph.scene() function doesn't exist in VR mode. Is there another way to add objects to the scene in VR mode ? Or to have VR controls in normal mode ? 
Thank you

**Comment by vasturiano** [comment]
Hello @afermeli and thanks for reaching out.

Well, the difference with the VR mode is that it uses [A-Frame](https://aframe.io/) for rendering. This VR framework, unlike the underlying ThreeJS layer, uses `HTML` to compose the scene. So, there isn't a direct scene JS object that you can manipulate/extend in the same way that you do with the plain 3D (ThreeJS based) mode.

However, you can see the `a-scene` element declared in the page source:
<img width="656" alt="Screenshot 2020-11-10 at 22 25 49" src="https://user-images.githubusercontent.com/6784226/98776459-cebbfd00-23a3-11eb-94a4-ea404c24327f.png">

If you append other a-frame compatible scene elements to this DOM node, they should be rendered as part of the scene in the VR context.

Hope that helps to clarify things.

**Comment by afermeli** [comment]
This definitely helps, thank you very much !
