### ISSUE TITLE
Combine 3d-graph with Blockchain data

### ISSUE THREAD

**Issue by vergeten** [vasturiano/react-force-graph#237]
Hi,

I'm trying to combine your beautifull 3d-graph with data from the ethereum blockchain. But i don't know where to start. I made a codesandbox: https://codesandbox.io/s/gracious-bartik-u9fmk where i get data from the blockchain. I tried a few things but nothing worked. I would be great if you can help me start out so i use this to visualize transactions on the blockchain.

Every little bit of help would be much appreciated 👍 

Greetings

**Comment by vergeten** [comment]
I've updated codesandbox: https://codesandbox.io/s/strange-shannon-efozz with the graph. I'm a bit stuck now on displaying the name of the nodes in the graph. Relationship is : to => tokenName => value. Hopefully you got some time to help me out :)

Thank you in advanced.

**Comment by vasturiano** [comment]
@vergeten have you looked into [this example](https://vasturiano.github.io/react-force-graph/example/text-nodes/index-3d.html).
The source code is here: https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-3d.html

**Comment by vergeten** [comment]
@vasturiano Thank you for suggesting this but i think i explained myself a bit wrong. Sorry about that. What i meant to do it show the data on hover on "nodeLabel".  The data is like this :

Home Data:  
![image](https://user-images.githubusercontent.com/39337564/99144574-3f467080-2667-11eb-9589-0596cedc9065.png)

So think i'm doing it wrong. My goal is to see the relationship between: to => tokenName => value in nodeLabel for all the data in the array.

Hopefully you can give again a bit of advise :)

Thank you in advandance and keep up the good work !!

**Comment by vasturiano** [comment]
@vergeten ok, in that case you can just use the `nodeLabel` method with a node accessor. Assuming that the data structure you've shown above is your nodes list, something like:
```js
myGraph.nodeLabel(node => `${node.tokenName}, ${node.value}`)
```

Would that work for your case?

**Comment by vergeten** [comment]
@vasturiano Thank you for your suggustion. I get "undefined, undefined" on the nodeLabel. I'm working with react. And this is the graph code:

<Graph 
                graphData={gData}
                nodeLabel={nodes => `${nodes.tokenName}, ${nodes.value}`}
                nodeAutoColorBy="group"
                linkDirectionalParticles="value"
                linkDirectionalParticleSpeed={d => d.value * 0.001}
                backgroundColor="#151719"
                      
              />

Or see codesandbox: https://codesandbox.io/s/gracious-bartik-u9fmk

Hopefully you can see what i'm doing wrong because i'm really close....i think!

Thank you for your time :)

**Comment by vasturiano** [comment]
@vergeten it appears your node data is nested under a `result` attribute. So you can access those fields by using `node.result.tokenName` for example.

**Comment by vergeten** [comment]
@vasturiano I tried that but for some reason i cannot access the array in the graph. Outside the graph i can access the data in the array with "resultData" . So im a bit lost what i'm doing wrong to acces the data in nodeLabel in the graph. Hopefully you can help again :)
