### ISSUE TITLE
Node Cluster Drifting

### ISSUE THREAD

**Issue by Kryptiique** [vasturiano/react-force-graph#242]
**Description**

This isn't so much a bug as much as it is a question on the simulation settings. It seems graphs with large clusters of nodes have an enormous amount of force on other nodes/clusters, eventually stretching the graph out to infinity whenever the graph is interacted with. Is there a way to prevent this from happening? I've been tweaking the force settings for quite a while now, but I've yet to find the right combination of settings that prevent this from happening. I'm sure there are some configuration settings I'm missing here. If this is more of a question for the D3 folks I can redirect it to them instead

**To Reproduce**

Use a large graph (+1K nodes) with 2 or more large clusters and at least 1 tiny cluster.
Configure physics settings like so:
```javascript
...
render() {
  return <ForceGraph2D
    virtualref={ this.fgRef }
    graphData={ this.state.graph }
    d3VelocityDecay={ 0.28 }
    d3AlphaDecay={ .055 }
    d3AlphaMin: { 0 }
  />
}

initialize(){
  this.fgRef.current.d3Force('charge').distanceMax(25)
  this.fgRef.current.d3Force('charge').strength(-25)
  this.fgRef.current.d3Force('link').distance(15)
  this.fgRef.current.d3Force('collision', d3.forceCollide(node => 2.5*node.radius))
  this.fgRef.current.d3Force('x_dist', d3.forceX().strength(10))
}
...
```

**Screenshots**

Here is an example of a graph with roughly 6.6K nodes after moving a couple nodes aroudn. Simulation slows down pretty quick on its own but when dragging a node it seems to continue to simulate and drift out to the edges of the screen.
![image](https://user-images.githubusercontent.com/8742491/100561938-30c3a000-3288-11eb-9e5e-02cf0b656b58.png)

Desktop:
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [react-force-2d 1.15.1]

**Comment by vasturiano** [comment]
@Kryptiique thanks for reaching out.

I'm afraid there's not really a silver bullet that can solve this always, and generally different calibration is needed on a case-by-case basis.

I see you've already tried the approach of limiting the `maxDistance` of the charge (repelling) force that is the main responsible for causing sub-graphs to drift apart.
And pulling things to the center gently with `forceX/Y` which is another common trick.

An additional thing you can do is setting limits on how far a node can go, to keep them in a contained area. For example with [d3-force-limit](https://github.com/vasturiano/d3-force-limit). There's a [demo here](https://observablehq.com/@vasturiano/d3-force-limit) that also shows the behavior of the soft limits which prevents nodes from congregating in the container walls.

In addition, perhaps you can come with other ideas from the available force plugins at [d3-force-registry](https://github.com/vasturiano/d3-force-registry).

**Comment by Kryptiique** [comment]
Thank you for the tips! I will definitely check out the force limit module, hopefully it helps out
