### ISSUE TITLE
ForceGraph3D paintRing

### ISSUE THREAD

**Issue by ItFlyingStart** [vasturiano/react-force-graph#246]
**Is your feature request related to a problem? Please describe.**
This is not a feature request, but I need your help.

**Describe the solution you'd like**
I would like to apply your example [https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html](url) for ForceGraph3D, but the logic defined below doesn't work in the 3D mode:

` const paintRing = useCallback(
    (node, ctx) => {
      // add ring just for highlighted nodes
      ctx.beginPath();
      ctx.arc(node.x, node.y, NODE_R * 1.4, 0, 2 * Math.PI, false);
      ctx.fillStyle = node === hoverNode ? "red" : "orange";
      ctx.fill();
    },
    [hoverNode]
  );`

![image](https://user-images.githubusercontent.com/5562995/103357061-8cb15c80-4ab2-11eb-9697-799f35cfed2b.png)

Is it possible to highlight the nodes in the 3D mode?

Many thanks in advance for your help.

**Comment by ItFlyingStart** [comment]
Another question, I would like to show the label of the neighbors as well, but I get stuck here, can you give me some hints?

  const createNodeLabel = (node) => {
    try {
      const { id, color } = node;

      if (node) {
        **node.neighbors.forEach((neighbor) => showNeighborLabel(neighbor));**
      }

      return `<div>
        <div>${id}</div>
        <div>${color}</div>
      </div>`;
    } catch(e) {
      return (
        <div />
      )
    }
  };

**Comment by vasturiano** [comment]
@ItFlyingStart thanks for reaching out. 

For both of the options you described you'd need to use the `nodeThreeObject` property instead of `nodeCanvasObject`, because you're in 3D mode and that requires a ThreeJS object, as opposite to 2D where you're painting on canvas.

There is a highlighting example in 3D on the `3d-force-graph` repo:
https://vasturiano.github.io/3d-force-graph/example/highlight/
But it may not do exactly what you're looking for. 

For showing text you can look into the [3D text nodes example](https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-3d.html).
As for adding a ring in the 3D world you can either add a semi-transparent sphere object that is larger than the node's radius, or add a 2D sprite circle representing a ring that always faces the camera.

In either case you would have to construct custom Three objects using `nodeThreeObject`.

Hope that helps.

**Comment by ItFlyingStart** [comment]
Hi @vasturiano ,

Many thanks for your help and hint.

Here are my codes. I do get a performance issue after dragging a node. The graph becomes "sluggish". Do you know how to prevent/resolve this issue?

`
import React, {
  useState,
  useMemo,
} from "react";

import { ForceGraph3D } from "react-force-graph";
import SpriteText from "three-spritetext";
import * as THREE from "three";

function App() {
  const GROUPS = 12;

  const gData = useMemo(() => {
    const data = genRandomTree(80);

    // cross-link node objects
    data.links.forEach(link => {
      const a = data.nodes[link.source];
      const b = data.nodes[link.target];
      !a.neighbors && (a.neighbors = []);
      !b.neighbors && (b.neighbors = []);
      a.neighbors.push(b);
      b.neighbors.push(a);

      !a.links && (a.links = []);
      !b.links && (b.links = []);
      a.links.push(link);
      b.links.push(link);
    });

    return data;
  }, []);

  const [highlightNodes, setHighlightNodes] = useState(new Set());
  const [highlightLinks, setHighlightLinks] = useState(new Set());
  const [hoverNode, setHoverNode] = useState(null);

  const updateHighlight = () => {
    setHighlightNodes(highlightNodes);
    setHighlightLinks(highlightLinks);
  };

  const handleNodeHover = node => {
    highlightNodes.clear();
    highlightLinks.clear();
    if (node) {
      highlightNodes.add(node);
      node.neighbors.forEach(neighbor => highlightNodes.add(neighbor));
      node.links.forEach(link => highlightLinks.add(link));
    }

    setHoverNode(node || null);
    updateHighlight();
  };

  const handleLinkHover = link => {
    highlightNodes.clear();
    highlightLinks.clear();

    if (link) {
      highlightLinks.add(link);
      highlightNodes.add(link.source);
      highlightNodes.add(link.target);
    }

    updateHighlight();
  };

  const generateColor = node => {
    if (node.id % 2 === 0) {
      return '#84A5B8';
    } else if (node.id % 3 === 0) {
      return '#F5AD94';
    } else if (node.id % 5 === 0) {
      return '#15B2D3';
    } else if (node.id % 7 === 0) {
      return '#F3872F';
    } else if (node.id % 11 === 0) {
      return '#603C14';
    } else {
      return '#5F5426';
    }
  }

  const formatNodeLayout = node => {
    if (node === hoverNode) {
      var sphereCore = new THREE.SphereGeometry(4);
      var lambertCore = new THREE.MeshLambertMaterial({ color: 0x808080 });
      var meshCore = new THREE.Mesh(sphereCore, lambertCore);

      var sphere = new THREE.SphereGeometry(8);
      var lambert = new THREE.MeshLambertMaterial({ color: 0xff0000, transparent: true, opacity: 0.5 });
      var mesh = new THREE.Mesh(sphere, lambert);
    
      const sprite = new SpriteText(`${node.id}`);
      sprite.color = "#8898aa";
      sprite.textHeight = 10;
      sprite.center.set(0.5, 2.5);

      var group = new THREE.Group();
      group.add(meshCore);
      group.add(mesh);
      group.add(sprite);
      
      return group;
    } else {
      const sprite = new SpriteText(`${node.id}`);
      sprite.color = "#8898aa";
      sprite.textHeight = 8;
      sprite.center.set(0.5, 2);
      return sprite;
    }
  }

  return (
    <div>
      <ForceGraph3D
        graphData={gData}
        nodeColor={node => highlightNodes.has(node) ? node === hoverNode ? 'rgb(255,0,0,1)' : 'rgba(255,160,0,0.8)' : generateColor(node)}
        linkWidth={link => highlightLinks.has(link) ? 5 : 1}
        linkDirectionalParticles={4}
        linkDirectionalParticleWidth={link => highlightLinks.has(link) ? 4 : 0}
        onNodeHover={handleNodeHover}
        onLinkHover={handleLinkHover}
        nodeThreeObjectExtend={true}
        nodeThreeObject={formatNodeLayout}
      />
    </div>
  );
}

function genRandomTree(N = 300, reverse = false) {
  return {
    nodes: [...Array(N).keys()].map((i) => ({ id: i })),
    links: [...Array(N).keys()]
      .filter((id) => id)
      .map((id) => ({
        [reverse ? "target" : "source"]: id,
        [reverse ? "source" : "target"]: Math.round(Math.random() * (id - 1)),
      })),
  };
}

export default App;
`

**Comment by ItFlyingStart** [comment]
Hi @vasturiano ,

Any chance to check my issue reported below?

When I try to drag the node, then I see the next errors:


![image](https://user-images.githubusercontent.com/5562995/113593498-ca37ff80-9636-11eb-9b0c-538ebafeab74.png)

![image](https://user-images.githubusercontent.com/5562995/113593524-d1f7a400-9636-11eb-9357-52a675e6d7ea.png)

![image](https://user-images.githubusercontent.com/5562995/113593547-d754ee80-9636-11eb-9f96-641e88351723.png)

![image](https://user-images.githubusercontent.com/5562995/113593567-dd4acf80-9636-11eb-9019-99015cbad3e2.png)

**Comment by vasturiano** [comment]
@ItFlyingStart by looking at your example, I think the core of the issue is that you're not memoizing the callback functions that you're passing on to the `ForceGraph3D` component. This in turn is causing feedback render loops within React.

I would first try to memoize those functions using `useCallback` and then see if there's any other issue going on.

**Comment by ItFlyingStart** [comment]
Thanks for your help @vasturiano . This issue has been resolved by adding `useCallback` like you have suggested.
