### ISSUE TITLE
d3Force method

### ISSUE THREAD

**Issue by Zeckrom** [vasturiano/react-force-graph#25]
The way to use this method to change the charge of the nodes is very unclear!

**Comment by vasturiano** [comment]
@Zeckrom could you give some more details about what you're trying to achieve?

**Comment by Zeckrom** [comment]
Sure! I am trying to change the 'charge' value on the react 3D graph (I am accessing the method through the ref props )

**Comment by vasturiano** [comment]
@Zeckrom if you mean the `strength` of the `charge` force, you could do the following:
```
myGraphRef.d3Force('charge').strength(-42);
```

**Comment by naumanzchaudhry** [comment]
Guys, trying this out. I want to set the link distance (ForceGraph2D)
```
componentDidMount(){
      this.fg.d3Force("link").distance(120)
}
```

In my render method.
```
<ForceGraph2D
       ref={el => { this.fg = el; }}
      // other graph props.
/>
```

> this.fg is undefined

What am I doing wrong?

**Comment by larissa-n** [comment]
If anyone is looking for an example with a function component, I created one with hooks:

https://codesandbox.io/s/force-graph-2d-charge-udu5c

This works:
```
  useEffect(() => {
       forceRef.current.d3Force('charge').strength(-400);
  });
```
