### ISSUE TITLE
Not clear how to get access to the DOM element (e.g. for converting to png/jpg)

### ISSUE THREAD

**Issue by dysticus** [vasturiano/react-force-graph#255]
Hi,

I'm in the process of trying to download the generated react-force-graph component as svg or png but can't find the documentation to get access to the canvas element (so I can call toDataUrl).

I've provided a ref to the component like this:
```
<ForceGraph2D
        ...
        ref={fgRef}
        ...
      />
```
But it only exposes the following things:
![image](https://user-images.githubusercontent.com/1104252/108716026-e3b83880-751b-11eb-9590-46ada6ab1ba9.png)
Could you put me in the right direction?

Thanks!

**Comment by vasturiano** [comment]
@dysticus thanks for reaching out.

The `canvas` is an internal element of the component tied to the specific implementation in the module, and therefore it is not exposed externally via the component api.

However you can still access it if you explore the DOM from your graph root element. If you inspect the DOM you will find this structure:
<img width="648" alt="dom" src="https://user-images.githubusercontent.com/6784226/108785626-a73e0a00-7526-11eb-81b7-36b467cd9b57.png">

Using a some sort of DOM selector you can reach into the specific `canvas` element. However keep in mind this structure is not guaranteed to remain the same and could change in future versions of the module.

**Comment by dysticus** [comment]
@vasturiano Thanks for putting me in the right direction!
