### ISSUE TITLE
"cursor:pointer;" on Node Hover Reignites the Graph

### ISSUE THREAD

**Issue by bathrobe** [vasturiano/react-force-graph#259]
I'm using `useState` to set an `isHovered` boolean when a node is hovered. I want this to style the cursor as `pointer` when hovering a node, and go back to `auto` when the node is null. But when I hover the node, it reignites/redraws the whole graph, causing all nodes in the graph to shake around and jitter like they do on the initial page load. I'm using `useMemo` as the store for my data and have also tried setting `cooldownTicks` to 0 when `isHovered` is true, but the problem continues.

I'm using NextJS, so the graph component is brought in to the actual page with `next/dynamic` and SSR set to false.

```javascript
import { ForceGraph2D } from "react-force-graph";
import { getData } from "./data/getData";
import { useRef, useMemo, useState } from "react";

export default function ForceGraph({ index }) {
  const fRef = useRef();
  const gData = getData(index);
  const memoData = useMemo(() => gData);
  const [isHovered, setIsHovered] = useState(false);

  return (
    <>
      <ForceGraph2D
        ref={fRef}
        graphData={memoData}
        onNodeHover={(node) => {
          if (node != null) {
            //tried fRef.current.pauseAnimation(); here, but it didn't change anything
            setIsHovered(true);
          } else {
            setIsHovered(false);
          }
        }}
        cooldownTicks={isHovered ? 0 : Infinity} //when this is active, the graph "shrinks" on hover and all link lengths shorten
      />
      <style jsx>{`
        cursor: ${isHovered ? "pointer" : "auto"};
      `}</style>
    </>
  );
}
```
I just want the cursor to change to pointer when a node is hovered without any change to the graph. I'd be OK with pausing the animation, but had no luck with the `pauseAnimation()` method either. Using Windows 10, Brave v. 1.20

**Comment by jlangner-hubble** [comment]
`setIsHovered` is triggering a state change, which causes your ForceGraph component to re-render its output (the `return (...` (and therefore "reignite"). You need to manage the state of `isHovered` separately.

**Comment by bathrobe** [comment]
Thanks for the response @jlangner-hubble. I'm unclear on how to 'manage the state of isHovered separately'. Do you have any ideas on how to get `cursor-pointer` to work while managing state elsewhere?

**Comment by joshlangner** [comment]
Here's one way I'd approach it, and I admit my knowledge of the more modern hooks-based React is still limited. Conceptually though:

- Abstract the two places where state needs to be applied
- In the style case, you *DO* need to trigger a rerender, but prevent the child component from rerendering
- In the second case (cooldownTicks), you don't want to rerender the whole graph, just change the variable being passed in to the coldownTicks and HOPE that the underlying ForceGraph2d component handles its own internal state changes well. If it doesn't, you're out-of-luck I think.

> The following code probably needs some additional improvements in order to work, but hopefully sets you on a workable path

```jsx
const ForceGraph extends Component {
  constructor() {
    this.fRef = React.createRef();
  }
  shoudlComponentUpdate(nextProps) {
    const { index: nextIndex } = nextProps;

     // you'll need to improve this logic to accurately determine if your object / arrays have changed
    if (nextIndex !== this.props.index) {
      return true;
    }
    return false;
  }

  this.cooldownTicksSetting = Infinity;
  setCoolDownTicks = (setting) => {
    this.cooldownTicksSetting = setting;
  }

  return (
      <ForceGraph2D
        ref={fRef}
        graphData={this.props.index}
        onNodeHover={(node) => {
          if (node != null) {
            setIsHovered(true);
            this.setCoolDownTicks(0)
          } else {
            setIsHovered(false);
            this.setCoolDownTicks(Infinity)
          }
        }}
        cooldownTicks={this.cooldownTicksSetting}
      />
  );
}

const ForceGraphContainer = () => {
  const [isHovered, setIsHovered] = useState(false);
  return (
    <>
      <ForceGraph setIsHovered={setIsHovered} index={index} />
      <style jsx>{`
        cursor: ${isHovered ? "pointer" : "auto"};
      `}</style>
    </>
  )
}
```

**Comment by bathrobe** [comment]
Hi @joshlangner, thanks for the tip. Working through implementing this in functional hooks now-- seems tricky, but a HOC might solve everything. Appreciate you taking the time.

**Comment by vasturiano** [comment]
@bathrobe the issue might be in your `useMemo` call: 
```
const memoData = useMemo(() => gData);
```
You're not providing any dependencies to the hook (2nd argument), therefore `memoData` get re-generated at every render, in turn causing the graph to update as it receives new data. Just adding a `[]` as 2nd parameter will change that, but I don't know if that's your application's intent.
https://reactjs.org/docs/hooks-reference.html#usememo

**Comment by bathrobe** [comment]
Ahh it works! Thanks so much @vasturiano.
