### ISSUE TITLE
How to use CDN version within React

### ISSUE THREAD

**Issue by justindavies** [vasturiano/react-force-graph#26]
Apologies, I know this isn't specifically a Force Graph issue, but I'm a bit confused about how to use ForceGraph when including the CDN reference:

<script src="//unpkg.com/react-force-graph"></script>

I'm getting the issue that it cannot find the 2d and 3d definition:

  Line 623:  'ForceGraph3D' is not defined  react/jsx-no-undef
  Line 634:  'ForceGraph2D' is not defined  react/jsx-no-undef

I'm not sure how to pull in from the CDN in a React friendly way:

import { ForceGraph3D } from 'react-force-graph'
import { ForceGraph2D } from 'react-force-graph'

Thanks!

**Comment by vasturiano** [comment]
@justindavies loading the lib via a script tag will declare a global variable called `ForceGraph`, which is in an object that includes all the modules. So you can consume from it like:
```
<script src="//unpkg.com/react-force-graph"></script>
...
const { ForceGraph2D, ForceGraph3D, ForceGraphVR } = ForceGraph;
```
