### ISSUE TITLE
Context menu on nodes & links

### ISSUE THREAD

**Issue by ken-murray** [vasturiano/react-force-graph#262]
What's the best/simplest example of showing a context menu with menu items when clicking on a node or link?  Found a D3 example here: https://gilfink.medium.com/adding-a-context-menu-to-d3-force-graph-def5f197f343 

I'm new to React and that example just seems to have a lot of code to do something basic.  Just want to be sure I'm not missing some obviously better way of doing this.  Thanks.

**Comment by boostpaal** [comment]
I'd recommend just use `onNodeClick` and open a normal React component. Then you don't have to wander outside of Raact.

Something in the lines of;

```javascript
import React, { useState } from "react";
import ForceGraph3D from "react-force-graph-3d";
import ReactDOM from "react-dom";

const ForceComponent = () => {
  const [selectedNodeId, setSelectedNodeId] = useState < number > 0;

  const onNodeClick = (node) => {
    setSelectedNodeId(node.id);
  };

  return (
    <div>
      {selectedNodeId &&
        ReactDOM.createPortal(
          <div style={{ zIndex: 1 }}>
            <div>NODE MENU</div>
            <div>Menu item 1</div>
            <div>Menu item 2</div>
            <button onClick={() => setSelectedNodeId(0)}>Close</button>
          </div>,
          document.body
        )}
      <ForceGraph3D onNodeClick={onNodeClick} />
    </div>
  );
};

export default ForceComponent;
```

**Comment by ken-murray** [comment]
Many thanks again for your help, simple and works great.  My issue with the example solution I mentioned was simply that I don't think every solution needs a factory/abstract solution - except for unit testing.  I might look into just adapting the existing hover label to contain the menu - but I can figure that out myself much later when I'm much more competent with React.  Thank you.
