### ISSUE TITLE
Can I use this module without server-side rendering?

### ISSUE THREAD

**Issue by pstakuu** [vasturiano/react-force-graph#263]
When I try to use this module and sample code, with an app create with 'npx create-react-app demo', and then cd into the directory, install the react-force-graph library and dependencies, and launch the basic sample by copying the dataset for random generator, it seems like the apps loads in latest version of Edge and Chrome, but the page loads blank, although the CSS and data seem to be correct.  

Do I need to be using NextJS or another server-side rendering technique to get the basic example working?  I'm trying to get just the baseline tutorial working in a local environment but I'm failing :(.

Any chance your or someone has a tutorial for getting this running on a Windows 10 with latest VsCode?

**Comment by vasturiano** [comment]
@pstakuu this is probably a question for create-react-app or next. But in any case you can definitely use it for client-side rendering. It's specifically server-side rendering that is not supported, because it requires access to the DOM and several `window` bound attributes.

**Comment by pstakuu** [comment]
Thank you for the response! Okay, I'll keep plugging away at it.  I gotta get the basic example going and then I can continue with this project.

Great looking module!!
