### ISSUE TITLE
Links do not move with nodes

### ISSUE THREAD

**Issue by kim-anhvu** [vasturiano/react-force-graph#264]
Hi, 

First of all, thank you for this amazing library! Currently, I am implementing a feature where you can edit the name of the node by clicking on it. However, whenever I click the submit button after inputting a new name, the only components that move are the nodes or the whole graph. The links are completely frozen. Although, the tooltip that displays the name updates accordingly.

I am quite certain that this is due to my handleSubmit function, which I use to try and update the node name.
```
const handleSubmit = () => {
  setOpenModal(false); 
  const { nodes, links } = data;
  const newLinks = links;
  const newNodes = nodes.map((n)=> n.id === editIdName.id ? {...n, name:editIdName.name} : {...n});        
  setData({ nodes: newNodes, links: newLinks });
};
```

It may be important to note (not sure!) that for all nodes, fx==x and fy==y.

Thank you in advance.

**Comment by JonThom** [comment]
@kim-anhvu if you `console.log' the `graphData` object after rendering you'll see that the library adds rendering-related attributes to your nodes. 
Rendering also replaces the `source` and `target` attributes of each link with copies of the actual source and target node objects. 
Most likely, replacing these node objects in `source` and `target` with just the corresponding node ids would fix the issue.

**Comment by kim-anhvu** [comment]
You are correct! Thank you so much @JonThom
