### ISSUE TITLE
Error: TypeError: selection.interrupt is not a function with version 1.22.1

### ISSUE THREAD

**Issue by barwalker** [vasturiano/react-force-graph#265]
**Describe the bug**
This error happens all the time after re-install react-force-graph-2d:
`TypeError: selection.interrupt is not a function
./node_modules/d3-zoom/src/zoom.js/__webpack_exports__.default/zoom.transform`
I believe it conflicts between d3-zoom dependencies.
`...
  ├─┬ venn.js@0.2.20

  │ ├── d3-selection@1.4.2

  │ ├─┬ d3-transition@1.3.2

  │ │ ├── d3-color@1.4.0

  │ │ ├── d3-dispatch@1.0.6 deduped

  │ │ ├── d3-ease@1.0.6
...
`
`...
  │ ├── d3-selection@2.0.0
  │ ├─┬ d3-zoom@2.0.0
  │ │ ├── d3-dispatch@1.0.6 deduped
  │ │ ├── d3-drag@2.0.0 deduped
...`

**Packages:**
 - "@amcharts/amcharts4": "^4.10.17"
 - "react-force-graph-2d": "^1.22.1"

Please give some advises to avoid this issue.
Thanks

**Comment by vasturiano** [comment]
Most likely the issue is because you have multiple versions of `d3-selection` in your dependency tree. Can you upgrade your dependencies in a way that reconciles this and have a single version of `d3-selection` installed?

**Comment by barwalker** [comment]
Yep, I have to use Amchart and Force graph, it conflicts d3-selection version with each other. So my only choice is finding a older version that has the same d3-selection version?

**Comment by vasturiano** [comment]
Yes, that would work. Or get Amchart to upgrade to `d3-selection` v2.

**Comment by barwalker** [comment]
Thanks

**Comment by Nate-Wessel** [comment]
Sorry if this is a dumb question, I'm relatively new to understanding Node's dependency management. 

It seems that `force-graph` depends now on `d3-selection` v2, but I want to use D3's latest major releases as direct dependencies in my project, and they all depend on `d3-selection` v3. 

Why don't v2 and v3 of `d3-selection` both get bundled separately with `force-graph` depending only on the code for v2?

Do I really have to choose between using this package and upgrading D3 which I depend on directly? Why is this an issue? I will look for other solutions if this package must dictate the other packages I can use in my project.

**Comment by vasturiano** [comment]
@Nate-Wessel thanks for reaching out. I've relaxed the dependency requirements for `force-graph` so it accepts both `v2` and `v3`:
https://github.com/vasturiano/force-graph/blob/08b29732018dd5a8500953d2234e1baf2a34d7ae/package.json#L50

If you upgrade to the latest version of this module you should be able to specify whichever version of `d3-select` you prefer for your project without hitting any conflicts or having to bundle two versions of `d3-select`.

**Comment by Nate-Wessel** [comment]
@vasturiano that's awesome! Thanks for looking into this and making the project more compatible. It's a great project by the way - thanks for your work on this!

**Comment by VishalKhurana** [comment]
@vasturiano I am using react-timeseries-charts library with react-force-graph which is having conflicts with d3-selection as react-timeseries-charts dependent versions are 
    "d3-selection": "^1.1.0",
    "d3-selection-multi": "^1.0.1" 
    Can you suggest me some way so that I can run both without breaking either of the feature in my project?
    Any suggestion/help would be appreciated.

**Comment by vasturiano** [comment]
@VishalKhurana I think that question would be better aimed at the `d3-selection` repo, or even at `react-timeseries-charts`, since they're running on an older version of `d3-selection`. This module is not compatible with `d3-selection` v1 because several breaking changes were introduced in that module from 1 -> 2.
