### ISSUE TITLE
Question: is there a way to get a node's current x, y, z coords without clicking on it?

### ISSUE THREAD

**Issue by jtewright** [vasturiano/react-force-graph#266]
I'd like to be able to center the camera on a specific node but I can't see how to find its current coordinates without it being clicked on.

Thank you.

**Comment by vasturiano** [comment]
@jtewright you can look in your data structure that you pass via `graphData`. Each node item in your structure is constantly updated with its `x`, `y` and `x` attributes.

**Comment by jtewright** [comment]
🤯 Brilliant, thank you @vasturiano! I'd assumed that wasn't getting updated! I'm passing that in via state.
