### ISSUE TITLE
Draw cycle link between nodes: Invalid DAG structure 

### ISSUE THREAD

**Issue by barwalker** [vasturiano/react-force-graph#267]
**Describe the bug**
Recently, I face an issue about circle link, after updating package dependency to the latest version.
`Uncaught Invalid DAG structure! Found cycle in node path: node-10 -> node-11 -> node-10.`
I have a cloud map with several nodes and 2-ways links between them.
Everything used to work fine with this data structure:
`
data_link = [
     {
          "source": "node-10",
          "target": "node-11"
     },
     {
          "source": "node-11",
          "target": "node-10"
     }
]
`

**Use**
```
 <ForceGraph2D
          width={600}
          height={800}
          graphData={data_link}
          enableNodeDrag={true}
          nodeAutoColorBy={'region'}
          enableZoomPanInteraction={true}
          nodeLabel={'id'}
          nodeRelSize={24}
          showNavInfo={true}
          linkWidth={5}
          linkCurvature={0.1}
          linkDirectionalArrowLength={1}
          linkDirectionalParticles={2}
          linkSource="source"
          linkTarget="target"
          dagMode={'radialout'}
          nodeCanvasObject={(node, ctx, globalScale) => {
                    const label = node.name;
                    const fontSize = 12 / globalScale;
                    ctx.font = 'bold ${fontSize}px Sans-Serif';
                    ctx.fillStyle = node.color;
                    ctx.beginPath();
                    ctx.arc(node.x, node.y, 12, 0, 2 * Math.PI);
                    ctx.fill();
                    ctx.strokeStyle = "black";
                    ctx.stroke();
                    ctx.textAlign = 'center';
                    ctx.textBaseline = 'middle';
                    ctx.fillStyle = 'rgba(85, 85, 85, 1)';
                    ctx.fillText(label, node.x, node.y + 45);
          }}
          onNodeClick={this._onClickNode}
          onLinkClick={this._onClickLink}
          onNodeDragEnd={this._onNodeDragEnd}
/>
```

That error doesn’t occur if there’s only 1 link between node, however, I need to draw 2-way link and this issue only happens recently.
Which option should I use to draw 2-way link and fix this error?
Thanks.

**Comment by vasturiano** [comment]
@barwalker that circular link introduces a loop in your data structure. That means you can't use the `dagMode` because your data is not a DAG structure.

So, either remove the loops from your data, or disable dag by removing the `dagMode` prop.
