### ISSUE TITLE
Custom Tooltips

### ISSUE THREAD

**Issue by Justin-W** [vasturiano/react-force-graph#269]
**Is your feature request related to a problem? Please describe.**
I want the user to be able to access (when needed) additional info/properties/context about a Node and/or Link in the graph. This information should only be displayed for a single Node/Link at a time, be displayed within the graph's current view, and preferably be accessed via natural/obvious user interaction (e.g. tooltips).

**Describe the solution you'd like**
I'd like to customize the tooltips for Nodes and/or Links as appropriate for an individual graph's extended data (e.g. data embedded within the graphData, but not necessarily related to the rendering of the graph). Tooltips are a natural, intuitive way for users to access "more info" about a given graph element. I'd like to be able to control both the content and the formatting/appearance of these tooltips.

**Describe alternatives you've considered**
There might already be a way to do what I've described using Three.js. If so, it'd be nice to have 1+ examples of how to do this in the context of using this React component. And if necessary, it would be good to have any new props, methods, etc. added to this React component, to enable App-level customization/control over the Tooltips' rendering.

In a pure D3 graph, I might (as a simplified example) do something like this (which results in a nicely formatted, multi-line tooltip on Node hover):

```
// NOTE: the `d` object below is the actual D3 DOM Node object.
node.append("title")
	.text(d => JSON.stringify(d, undefined, 2))
```

It seems that this component's `nodeLabel` and `linkLabel` props currently affect the tooltips' text content. However, the tooltips displayed by the following () seem to have all newlines stripped, resulting in very poor readability:

```
<ForceGraph3D
	nodeLabel={d => JSON.stringify(d, undefined, 2)}
	linkLabel={d => JSON.stringify(d, undefined, 2)}
	... />
```

**Additional context**

Mike describes several ways of making custom tooltips here:
https://observablehq.com/@d3/learn-d3-interaction?collection=@d3/learn-d3

This is an example focussing on custom appearance/formatting (even though only 1 data value is displayed per tooltip):
http://bl.ocks.org/Caged/6476579

Another simple example:
https://bl.ocks.org/d3noob/a22c42db65eb00d4e369

**Comment by vasturiano** [comment]
@Justin-W thanks for your request.

As you've mentioned, this component already supports tooltips via the `nodeLabel` and `linkLabel` props.

You can use plain text, as well as HTML (in string format, not jsx) in the content of the tooltips. That should allow you to style their content in whichever way you'd like.

So, you can do things like:
```js
nodeLabel={node => `<div><b>${node.label}</b>: <span>${node.value}</span></div>`}

**Comment by Justin-W** [comment]
Thanks. That works perfectly!
