### ISSUE TITLE
Smoother interpolation of centerAt()

### ISSUE THREAD

**Issue by GeoffGodwin** [vasturiano/react-force-graph#27]
I was wondering what the best approach to smoothly moving to a point would be given (x,y,z)?

I'm currently using a 2D graph and when I add a node I'd like to smoothly pan the camera to wherever it ends up being made. I took a look at some underlying d3 code and see you can use interpolators to "tween" from one value to another but I'm not sure how to expose that via this library.

Also, for now I've just added an arbitrary timeout to wait for the graph to stop animating since the location of the new node is unknown/fluid until the animation completes but I'm sure there is a better solution to this.

Thoughts?

**Comment by vasturiano** [comment]
@GeoffGodwin the `centerAt` method actually takes a third argument that specifies the transition time (in ms) to move to the destination. You can use that to animate the transitions.

Here's an example (from `3d-force-graph`) that shows that. Click on a node to center/zoom on it:
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

**Comment by GeoffGodwin** [comment]
Excellent! I will have to try this out. Thanks again.
