### ISSUE TITLE
linkCanvasObject custom link how to detect link hover or click event

### ISSUE THREAD

**Issue by GoFzy** [vasturiano/react-force-graph#271]
When I use linkCanvasObject custom link which different from the default link location, how to listen to the hover click event of the link
![image](https://user-images.githubusercontent.com/46565627/113716877-9a175c00-971d-11eb-83da-79bd08a3afe5.png)

**Comment by vasturiano** [comment]
@GoFzy thanks for reaching out.

I've just added a prop to the component that will allow you to specify your own custom pointer interaction area per link: `linkPointerAreaPaint`.

You just need to paint the same shape on the provided canvas context (and with the provided unique color), as your regular link paint method.

**Comment by GoFzy** [comment]
> @GoFzy thanks for reaching out.
> 
> I've just added a prop to the component that will allow you to specify your own custom pointer interaction area per link: `linkPointerAreaPaint`.
> 
> You just need to paint the same shape on the provided canvas context (and with the provided unique color), as your regular link paint method.

Thanks, it works
