### ISSUE TITLE
Enhancement: add cola force simulation engine

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#277]
The cola library seems to achieve some great layouts. It would be really cool if react-force-graph could use cola as a force simulation engine.

"It also has an adaptor for d3.js that allows you to use cola as a drop-in replacement for the D3 force layout. The layout 
converges to a local optimum unlike the D3 force layout, which forces convergence through a simple annealing strategy."

https://ialab.it.monash.edu/webcola/index.html

**Comment by vasturiano** [comment]
Hi @JonThom, thanks for that interesting pointer. I think it's a great idea to try and integrate the two.

Though, in an effort to prevent this module's API from snowballing by integrating additional layouts internally, I think it may be a better option to run that layout engine externally and plug it into this module for the rendering part. 

Just like it's done in [this example](https://vasturiano.github.io/force-graph/example/dagre/) where it's integrated with [Dagre](https://github.com/dagrejs/dagre). Here's [the example code](https://github.com/vasturiano/force-graph/blob/master/example/dagre/index.html).

**Comment by JonThom** [comment]
@vasturiano I had overlooked this example. This is really cool - I look forward to implementing it with cola!
