### ISSUE TITLE
How to have the label at all times in ForceGraph3D

### ISSUE THREAD

**Issue by Chinmay-k96** [vasturiano/react-force-graph#278]
As of the now i see that nodeCanvasObject works only for 2D please enable it for 3d or please suggest an alternative

**Comment by Chinmay-k96** [comment]
we can see the label only on hover......i want it to be there by default without hover

**Comment by vasturiano** [comment]
https://vasturiano.github.io/react-force-graph/example/text-nodes/index-3d.html

**Comment by Chinmay-k96** [comment]
Is it possible to have text along with the node and not just text. like how it looks when hovered over

![image](https://user-images.githubusercontent.com/62800512/115843426-743bc800-a43c-11eb-91be-b8492fb5657a.png)

**Comment by vasturiano** [comment]
@Chinmay-k96 please read the api docs for this. There is `nodeThreeObjectExtend` that exists for that purpose.

**Comment by Chinmay-k96** [comment]
This description is not clear, how to i use this prop. how can i built a custom node 

![image](https://user-images.githubusercontent.com/62800512/116250169-1a643680-a78b-11eb-8ce6-77deac1cd27a.png)

**Comment by vasturiano** [comment]
@Chinmay-k96 just `nodeThreeObjectExtend={true}` should suffice.

**Comment by Chinmay-k96** [comment]
dont i need nodeThreeObject ?
 
below is what i have done based on a code i saw for javascript but how do i do it in react, what should i import

**code**````

import React, {useEffect, useState, useRef, useCallback} from 'react';
import './App.css';
import ForceGraph3D from 'react-force-graph-3d';
import neo4j from 'neo4j-driver'
import  * as THREE  from 'three'

const extraRenderers = [new THREE.CSS2DRenderer()];

      return (
        <div>
          <ForceGraph3D 
            extraRenderers={extraRenderers}
            graphData={data}
            nodeId="name"
            ref={fgRef}
            nodeVal={node => {return node.size}} 
            linkCurvature={0.2} 
            linkDirectionalArrowRelPos={1} 
            linkDirectionalArrowLength={3}
            linkWidth={'weight'}
            linkAutoColorBy={'type'}
            nodeThreeObject={(node) => {
              const nodeEl = document.createElement('div');
              nodeEl.textContent = node.id;
              nodeEl.style.color = node.color;
              nodeEl.className = 'node-label';
              return new THREE.CSS2DObject(nodeEl);
            }}
            nodeThreeObjectExtend={true}
            nodeColor={node => {return node.color}}
            onNodeDragEnd={node => {
              console.log(node.fx)
              node.fx = node.x;
              node.fy = node.y;
              node.fz = node.z;
            }}
            onNodeClick={handleClick}
          />
        </div>
      ); 


This does not work please help

**Comment by vasturiano** [comment]
Have you looked into [this example](https://vasturiano.github.io/react-force-graph/example/html-nodes/), and is that not working for you?
https://github.com/vasturiano/react-force-graph/blob/6da855e75a61c670d6e101f8f48554d5e6385d67/example/html-nodes/index.html#L33-L45

**Comment by Chinmay-k96** [comment]
I figured out the solution.........Actually the problem was i had installed the three package from npm and imported it in my file and THREE here does not expose CSS2DObject and CSS2DRenderer so i was getting the error that they are not exported from three.  now i have used the script tag instead and access it through window variable an it works now....  But thank you so much for checking and sharing things, it triggered my thought........Great job on this repo. Please keep adding features

**Comment by tarun080698** [comment]
@Chinmay-k96, i want to add a custom menu on node hover and I think you are doing the same.  Can you help me with that? 
here's my code snippet
`<ForceGraph3D
          ref={fgRef}
          graphData={props.signalData}
          backgroundColor={'#1d2124'}
          height={props.heightEle}
          width={props.widthEle}
          nodeId="id"
          nodeLabel={showText}
          linkSource="source"
          linkTarget="target"
          onNodeHover={node => {
            hoverNode(node)
          }}
          onNodeClick={handleClick}
          nodeThreeObject={({ group, field }) => {
            const imgTexture = new THREE.TextureLoader().load(suspect_url)
            const material = new THREE.SpriteMaterial({ map: imgTexture, color: 0xffffff })
            const sprite = new THREE.Sprite(material)
            sprite.scale.set(20, 20)
            return sprite
          }}
          linkColor={() => 'white'}
          linkDirectionalParticles={5}
          linkDirectionalParticleWidth={1}
          linkDirectionalParticleSpeed={d => 10 * 0.001}
          linkDirectionalParticleColor="red"
        />`
