### ISSUE TITLE
LinkDirectionalParticles is not working on 3D

### ISSUE THREAD

**Issue by Chinmay-k96** [vasturiano/react-force-graph#279]
The documentations states that linkdirectionalparticles works on 3D but it dosent even in the latest version
Please help with this

![image](https://user-images.githubusercontent.com/62800512/115681235-f7dcb280-a371-11eb-87ae-a09e0ea50aa2.png)

**Comment by vasturiano** [comment]
@Chinmay-k96 is this example not working for you?
https://codesandbox.io/s/3d-force-graph-directional-particles-36ojv

**Comment by Chinmay-k96** [comment]
is there a difference between ForceGraph3d and ForceGraph3D. I am using <ForceGraph3D /> where D in 3D is caps and linkDirectional particles is not working for me

**Comment by vasturiano** [comment]
You mean in the import?
```js
import ForceGraph3d from "react-force-graph-3d";
```

That's just the variable name, there should be no difference regardless of what you call it.
Perhaps you can make a simple sandbox that reproduces your issue, so we can help you debug it.

**Comment by Chinmay-k96** [comment]
Thank you may be there was some other issue i dint notice, I rewrote the whole thing and its fine........Thank you so much for replying and all the help.........People like you are responsible for growth of developers.......much appriciated
