### ISSUE TITLE
Can i reduce the opacity of other nodes and links on node hover in 3D

### ISSUE THREAD

**Issue by Chinmay-k96** [vasturiano/react-force-graph#280]
I want to highlight the node relations and blur other nodes which are secondary can i do this in the 3D graph. please help with this
I am looking for something like the below attached screenshot. You can see that on hovering over or clicking on the node (both seems fine), the other nodes and links should be blurred. Please help to make this possible

![Screenshot (29)](https://user-images.githubusercontent.com/62800512/115685706-180e7080-a376-11eb-85bf-9f0c061d8563.png)

**Comment by vasturiano** [comment]
Yes, that's certainly possible. It's a simple variation of the highlighting example:
https://vasturiano.github.io/react-force-graph/example/highlight/

**Comment by Chinmay-k96** [comment]
The example you have shared is or 2D, but is it possible with 3D, if yes could you please share the code on how i can add it
