### ISSUE TITLE
How to make selective nodes glow using UnrealBloom?

### ISSUE THREAD

**Issue by mritunjaymusale** [vasturiano/react-force-graph#284]
Can you demonstrate a way to make only set of nodes bloom rather than the whole graph ?
I would like only certain set of nodes to bloom based on certain attribute of a node, like say `"isInfluentialNode":true` then that particular node should glow and the rest shouldn't.

**Comment by vasturiano** [comment]
Related to https://github.com/vasturiano/3d-force-graph/issues/421.
