### ISSUE TITLE
d3Force - Horizontal Layout

### ISSUE THREAD

**Issue by Crcamargo** [vasturiano/react-force-graph#29]
I'm having trouble making the force graph horizontal. (ex: http://d3indepth.com/force-layout/#forcex-and-forcey)

I'm trying to do this using d3Force methods but since there's only the three default ones I don't know how to use forceX or forceY to change the position.

thanks!

**Comment by vasturiano** [comment]
@Crcamargo you can add new forces using the syntax:
```
myGraphRef.d3Force('horizontal', d3.forceX(42));
```

This [example](https://vasturiano.github.io/react-force-graph/example/collision-detection/) may be helpful as it uses a few custom forces.

**Comment by Crcamargo** [comment]
Awesome, thanks!
