### ISSUE TITLE
How to disable the default hover action of the node which displays node info

### ISSUE THREAD

**Issue by Chinmay-k96** [vasturiano/react-force-graph#291]
I have used nodeCanvasObject and made the text appear long with node so i dont need the hover action where the data is displayed. How to i disable it

**Data when hover over node with black background**
![Screenshot (31)](https://user-images.githubusercontent.com/62800512/117165068-cc7eac80-ade2-11eb-8836-dad237bcd99f.png)

Daenerys-Targarynen is appearing on hover with black background. So the same data is seen twice now. How do i disable it ?

**Comment by vasturiano** [comment]
@Chinmay-k96 you must be actively setting that with `nodeLabel`, so just remove that prop.

**Comment by Chinmay-k96** [comment]
I have not set the nodeLabel prop but what i observed is that nodeLabel is set by default if you dont use the prop . so i did this --> nodeLabel={""} and it worked for me. anyways thank you
