### ISSUE TITLE
bug: zoomToFit not working as expected on all devices

### ISSUE THREAD

**Issue by nidhi-tandon** [vasturiano/react-force-graph#296]
**Describe the bug**
`zoomToFit` is not working the same on all devices.

**To Reproduce**
1. Used here https://github.com/SigNoz/signoz/blob/main/frontend/src/modules/Servicemap/ServiceMap.tsx#L96
Computing the zoom values here https://github.com/SigNoz/signoz/blob/main/frontend/src/modules/Servicemap/utils.ts#L77

2. Move to `service-map`, select any value from the dropdown 

https://user-images.githubusercontent.com/6941627/120890776-83f52180-c622-11eb-95c3-ed24878e3827.mov

**Expected behavior**
The padding given to `zoomToFit` is 400 and should behave similarly in all devices with the same resolution and width.
https://www.loom.com/share/b0f7f0b1cf034c94b351616feedb9228

**Desktop (please complete the following information):**
 - OS: macOs Catalina 10.15.7 
 - Browser: Chrome
 - Version: 91.0.4472.7

**Additional context**
The same value is working fine on another laptop of the same model, OS, browser, and resolution.
Open issues related to this: https://github.com/SigNoz/signoz/issues/151

Any help will be appreciated. Thanks

**Comment by vasturiano** [comment]
@nidhi-tandon thanks for reaching out.

Are you able to put together a simple reproducing example on [codesandbox](https://codesandbox.io/) so it can be debugged further?

**Comment by nidhi-tandon** [comment]
Closing this as I have lost context of this issue
