### ISSUE TITLE
Using null over undefined in the type definition for the React.MutableRefObject

### ISSUE THREAD

**Issue by fan-matt** [vasturiano/react-force-graph#297]
Hello, and thank you for your work on this repository!

I am using Typescript, and I am creating a ref to ForceGraph2D.

I create the ref like this,
```js
const graphRef = useRef<ForceGraphMethods>(null);
```
which ideally should cause no issue later on here
```js
<ForceGraph2D 
    ref={graphRef}
    ...
/>
```

However, this produces the following issue:
```
Type 'RefObject<ForceGraphMethods>' is not assignable to type 'MutableRefObject<ForceGraphMethods | undefined>'.
  Types of property 'current' are incompatible.
    Type 'ForceGraphMethods | null' is not assignable to type 'ForceGraphMethods | undefined'.
      Type 'null' is not assignable to type 'ForceGraphMethods | undefined'.ts(2322)
react-force-graph-2d.d.ts(148, 64): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & ForceGraphProps & { ref?: MutableRefObject<ForceGraphMethods | undefined> | undefined; } & { ...; }'
(JSX attribute) ref?: React.MutableRefObject<ForceGraphMethods | undefined> | undefined
```

Currently, as a workaround, I can write as is written in #178 and append `| any` as so:
```js
const graphRef = useRef<ForceGraphMethods | any>(null);
```

Problem is, the use of `any` is heavily discouraged and goes against using TS in the first place.

I got the idea for this issue [here](https://stackoverflow.com/questions/65038611/type-mutablerefobjecthtmlinputelement-undefined-is-not-assignable-to-type), and when I tried it by changing line 148 from react-force-graph-2d.d.ts from 
```js
type FCwithRef<P = {}, R = {}> = React.FunctionComponent<P & { ref?: React.MutableRefObject<R | undefined> }>;
```

to

```js
type FCwithRef<P = {}, R = {}> = React.FunctionComponent<P & { ref?: React.MutableRefObject<R | null> }>;
```

the TS compiler no longer complains. I am not a TS expert (I am only a beginner), but is this a bug? Or is there a better solution to pursue?

Relevant package versions:

```json
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-force-graph-2d": "^1.23.6",
```

**Comment by vasturiano** [comment]
@fan-matt thanks for reaching out.

Why not just instantiate the ref as this?
```js
const graphRef = useRef<ForceGraphMethods | undefined>();
```

**Comment by fan-matt** [comment]
Goodness, of course that works, thanks for pointing it out. Maybe it was getting too late...

Thanks for the quick response!

**Comment by ccarv** [comment]
@vasturiano How would you achieve this in vanilla Javascript? (new to react)

**Comment by vasturiano** [comment]
@ccarv not sure I understand the question. Forward refs are a React concept, and this is specifically about using it in conjunction with Typescript. What are you trying to achieve?
