### ISSUE TITLE
I am using this 2d graph in next js with dynamic import. But not able to use manual zoom. Can you please guide

### ISSUE THREAD

**Issue by skhaide1** [vasturiano/react-force-graph#298]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by skhaide1** [comment]
@vasturiano

**Comment by vasturiano** [comment]
@skhaide1 can you provide a reproducing example of your issue on https://codesandbox.io/ ?

**Comment by skhaide1** [comment]
import React, { useState, useEffect, useCallback, useRef, forwardRef } from 'react';
import * as d3 from 'd3';
//import { ForceGraph3D} from 'react-force-graph';
import styles from './KnowledgeGraph.scss';
import renderIcon from './renderIcon';
import dynamic from 'next/dynamic';
const sample = require('./data.json');

const ForceGraph2D = dynamic(() =>   import('react-force-graph').then((module) =>module.ForceGraph2D),{ ssr: false });
const ForwardRefEditor = forwardRef((props, ref) => (
  <ForceGraph2D {...props} forwardedRef={ ref} />
));

const KnowledgeGraph = () => {
  
 // console.log(this.props);
  const editorRef = useRef(null);
  //const curZoom = forceRef.current.zoom();
  useEffect(() => {
    //console.log("mmm"+forceRef.current.zoom);
    console.log("editorRef", editorRef.current);
  },[]);
  console.log("editorRef1", editorRef.current);
  const zoomIn = ()=>{
    setZoom(( zoom ) => {
     
      return zoom+1;
    });
    //zoom();
  // editorRef.current.zoom;
    
  }
  const zoomOut = ()=>{

    setZoom(( zoom ) => {
     
      return zoom-1;
    });
  }
  const onClick =  function() {
    setData(({ nodes, links }) => {
      const id = nodes.length;
      return {
        nodes: [...nodes, { id: "dog1"   , group: 0, label: "Dogs"   , level: 2 }],
        links: [...links, { target: "dog1"   , source: "cat" , strength: 0.1 },]
      };
    });
  }
    
      //  console.log("now "+curZoom);
        const [data, setData] = useState({ nodes: [{ id: "mammal", group: 0, label: "Mammals", level: 1, color:"RED" },
        { id: "dog"   , group: 0, label: "Dogs"   , level: 2 },
        { id: "cat"   , group: 0, label: "Cats"   , level: 2 },
        { id: "fox"   , group: 0, label: "Foxes"  , level: 2 },
        { id: "elk"   , group: 0, label: "Elk"    , level: 2 },
        { id: "insect", group: 1, label: "Insects", level: 1 },
        { id: "ant"   , group: 1, label: "Ants"   , level: 2 },
        { id: "bee"   , group: 1, label: "Bees"   , level: 2 },
        { id: "fish"  , group: 2, label: "Fish"   , level: 1 },
        { id: "carp"  , group: 2, label: "Carp"   , level: 2 },
        { id: "pike"  , group: 2, label: "Pikes"  , level: 2 }], 
        links: [{ target: "mammal", source: "dog" , strength: 0.7 },
        { target: "mammal", source: "cat" , strength: 0.7, color:'RED' },
        { target: "mammal", source: "fox" , strength: 0.7 },
        { target: "mammal", source: "elk" , strength: 0.7 },
        { target: "insect", source: "ant" , strength: 0.7 },
        { target: "insect", source: "bee" , strength: 0.7 },
        { target: "fish"  , source: "carp", strength: 0.7 },
        { target: "fish"  , source: "pike", strength: 0.7 },
        { target: "cat"   , source: "elk" , strength: 0.1 },
        { target: "carp"  , source: "ant" , strength: 0.1 },
        { target: "elk"   , source: "bee" , strength: 0.1 },
        { target: "dog"   , source: "cat" , strength: 0.1 },
        { target: "fox"   , source: "ant" , strength: 0.1 },
        { target: "pike"  , source: "cat" , strength: 0.1 }] });

        const [zoom, setZoom] =useState(1);
       
       
        return (
        <><span className={styles.graph__dots}></span><div id="jj"><button id="zoom_in" onClick={zoomIn}>+</button>
        <button id="zoom_out" onClick= {zoomOut}>-</button>
        <button id="zoom_init">Init</button><button id="full" onClick={onClick}>add</button> 
        <ForwardRefEditor
        //ref={this.forceRef}
        onZoom = {zoomIn}
        ref={editorRef }
        enableZoomInteraction= {true}
          graphData={data}
          nodeAutoColorBy="group"
          nodeCanvasObject={(node, ctx, globalScale) => {
            const label = node.id;
            const fontSize = 12/globalScale;
            ctx.font = `${fontSize}px Sans-Serif`;
            const textWidth = ctx.measureText(label).width;
            const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding

            ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
            ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);

            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillStyle = node.color;
            ctx.fillText(label, node.x, node.y);

            node.__bckgDimensions = bckgDimensions; // to re-use in nodePointerAreaPaint
          }}
          nodePointerAreaPaint={(node, color, ctx) => {
            ctx.fillStyle = color;
            const bckgDimensions = node.__bckgDimensions;
            bckgDimensions && ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);
          }}
        /></div></>);
      };

export default KnowledgeGraph;

**Comment by vasturiano** [comment]
@skhaide1 thanks for the code, but I meant to create a functional example on codesandbox.io so it's possible to debug.
