### ISSUE TITLE
'CSS2DObject' is not exported from 'three' (imported as 'THREE').

### ISSUE THREAD

**Issue by beulahpt** [vasturiano/react-force-graph#299]
**I am trying to have label inside node**

Used the following code set:

import ForceGraph3D from 'react-force-graph-3d';

import * as THREE from 'three'

import {CSS2DRenderer, CSS2DObject} from 'three-css2drender'

  const extraRenderers = [new CSS2DRenderer()];

 return (
    <div className="dndflow col-12">
      <ForceGraph3D
        extraRenderers={extraRenderers}
        graphData={graphData}
        backgroundColor="#333"
        linkColor={() => "green"}
        linkWidth={1.5}
        linkOpacity={1}
        nodeThreeObject={node => {
          const nodeEl = document.createElement('div');
          nodeEl.textContent = node.id;
          nodeEl.style.color = "black";
          nodeEl.className = 'node-label';
          return new THREE.CSS2DObject(nodeEl);
        }}
        nodeThreeObjectExtend={true}
      />
    </div>`
);

Getting the following error:

`Attempted import error: 'CSS2DObject' is not exported from 'three' (imported as 'THREE').`

**Comment by vasturiano** [comment]
@beulahpt by looking at this line:
```js
import {CSS2DRenderer, CSS2DObject} from 'three-css2drender'
```
did you intend to open an issue in that repo instead?

**Comment by beulahpt** [comment]
Oh Yes. 

The above has been resolved after importing CSS2DObject from jsm

import {CSS2DRenderer, CSS2DObject} from 'three/examples/jsm/renderers/CSS2DRenderer.js';

and used like **new CSS2DObject()** instead of THREE.CSS2DObject()
