### ISSUE TITLE
How to access the utility methods and get click coords relative to node center?

### ISSUE THREAD

**Issue by joostdecock** [vasturiano/react-force-graph#304]
**Describe the bug**
This is almost certainly not a bug, but rather my own ignorance, but it's also not a feature request, so :shrug: 

I want to access a utility method. The `screen2GraphCoords` specifically.
In the README, this method is listed as a prop. I'm not sure what to make of that, since props are passed down.

In my `onClick` handler, I receive the node, and the drawing context. I can't seem to find the `screen2GraphCoords` attached to them either, so I'm a bit at a loss of how to access this method. Clearly it needs to come from the component, since it needs the state of the canvas. But how can I get to it?

**To Reproduce**

I am trying to find out where the user clicked in comparison to the center of the node (did they click more to the right, or more to the left).

**Expected behavior**
Perhaps the docs could be a bit more clear?

**Screenshots**
My use-case is this: I've added a custom shape. When the user clicks, I draw a different shape that has 4 *zones*.
I'd like to use a click on each of these zones differently. But for that, I'd need to know where the user clicked relative to the center o the node.

![Screenshot-20210628161520-738x626](https://user-images.githubusercontent.com/1708494/123651851-1bb5ec00-d82c-11eb-9b64-db7a7a47ea17.png)

**Additional context**
Your work is awesome :heart:

**Comment by JonThom** [comment]
Hi @joostdecock ,
Note that `screen2GraphCoords` is listed as a method, not a prop.
In the library you can use methods with a useRef hook ([example](https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html))
To use the above method, just do `fgRef.current.screen2GraphCoords([x],[y])`

**Comment by vasturiano** [comment]
@joostdecock thanks for reaching out.

In the docs this functionality is listed as a component **method**, not a **prop**. You access methods via React [forward refs](https://reactjs.org/docs/hooks-reference.html#useref). You can see in this example a sample of usage of the component ref:
https://github.com/vasturiano/react-force-graph/blob/e67177b3522e2ffd212f807cbb6b74ed04a39ab6/example/click-to-focus/index.html#L20-L32

**Comment by joostdecock** [comment]
Guess who has two thumbs and feels like a frigin' moron right now.

:+1: :+1: this guy :joy: 

Thanks for that, it's all so obvious now :see_no_evil:
