### ISSUE TITLE
How to implement ondrag event?

### ISSUE THREAD

**Issue by vbrantner** [vasturiano/react-force-graph#305]
Html canvas does not allow ondrag events.
@vasturiano do you know a possible/idea way to implement such a feature?

I want to have an dragable element and drop this element on a node, during node adding I need the information from that particular node where I dropped the element of.

My current approach is that I wrapped the Graph inside a div with a onDrop event.
On a onDrop event, I would retrieve the coordinates and try to find the coordinates from the node state and their x, y positions.

```
const onDrop = (e) => {
    e.preventDefault();
    console.log(fgRef.current.screen2GraphCoords(e.clientX, e.clientY));
};

<div onDrop={(e) => onDrop(e)}>
        <ForceGraph2D
          ref={fgRef}
        ...
        />
</div>
```

Do you have a better idea to implement onDrag events?
The coords from screen2GraphCoords does not represent the x, y coordinates from the node state? Does this have something todo with Zooming?

**Comment by vasturiano** [comment]
@vbrantner I'm wondering if the `x, y` coordinates passed onto `screen2GraphCoords` may not be correct in your case. These should be coordinates relatives to the top-left corner of the canvas. Can you try and console log `e.clientX` and `e.clientY` and make sure that is giving you the numbers you'd expect (f.e. dropping on the top-left corner of the canvas should give you close to 0,0)?

**Comment by vbrantner** [comment]
@vasturiano, unfortunately dropping on the top-left corner does not console log 0,0. It is logging the correct x, y depending on where the canvas is on the screen.

I get different coordinates for the top-left corner depending on screen size, which make sens.

Screen2GraphCoords are different depending on zoom/panning.

Should I provide codesandbox.io or do you have another idea?

thanks in advance

**Comment by vasturiano** [comment]
@vbrantner so you have to make sure that the coordinates you pass on to `screen2GraphCoords` are in reference to the 0,0 of the canvas top-left. 

If you only have the webpage viewport coordinates, you need to convert those to relative to the canvas element, possibly by doing some offset calculation. You should be able to get the graph element offset using the DOM (though it's beyond the scope of this module really).

**Comment by vbrantner** [comment]
@vasturiano Thanks for your response! Thank you also for the quick reply. I would set the issue as close since it is beyond the scope of this module.
