### ISSUE TITLE
Add click event on custom nodeCanvasObject

### ISSUE THREAD

**Issue by jMoulis** [vasturiano/react-force-graph#306]
Hi,
I would like to add a kind of a donut menu composed of 4 slices around the selected node. But I don't know if it is possible to add event on these slices.
What would be your advice?
Thanks for your great work
![Capture d’écran 2021-07-19 à 12 00 11](https://user-images.githubusercontent.com/22916626/126143219-55a28550-e4f1-47b1-96f2-30b20c035236.png)

**Comment by vasturiano** [comment]
@jMoulis thanks for reaching out.

The second argument passed in the `onNodeClick` callback is the native `PointerClick` event itself. This event object includes attributes such as `clientX`, `clientY`, `offsetX`, `offsetY`. 
If you have the canvas screen coordinates of the click, you can convert them to the graph domain via `screen2GraphCoords`.
From there perhaps you can do an intersection into your custom object to find out which section was clicked. 👍

**Comment by jMoulis** [comment]
@vasturiano Thanks for reply, and sorry for my late response. The things that I don't get through the onNodeClick is that as soon as I display my menu and click on it it does't call onNodeClick, which makes sense. To create my menu I used the exemple  `https://vasturiano.github.io/react-force-graph/example/highlight/` through the `nodeCanvasObject`. But then how can I listen a event click on the menu? Sorry you might have given me the answer but I don't get it. I'ma really sorry.

**Comment by vasturiano** [comment]
@jMoulis it's difficult to say without a concrete example. But if you're using `nodeCanvasObject` to draw your node, there's a strong chance that you'd also need to add logic to `nodePointerAreaPaint`, to make sure that the complete painted area of your node is clickable and associated with your node object, otherwise the component just falls back to its default node click area since it doesn't know any better.

**Comment by jMoulis** [comment]
```javascript
import React, { useCallback, useEffect, useState } from 'react';
import { ForceGraph2D } from 'react-force-graph';
import { v4 as uuid } from 'uuid';
import { getPrunedTree } from './utils';

function App() {
  const [graphData, setGraphData] = useState<{ nodes: any[]; links: any[] }>({
    nodes: [],
    links: [],
  });
  const [selectedNode, setSelectedNode] = useState<any | null>(null);
  const [selectedLink, setSelectedLink] = useState<any | null>(null);
  const [prunedTree, setPrunedTree] = useState<any>({ nodes: [], links: [] });

  useEffect(() => {
    fetch('data/dataset.json')
      .then((payload) => payload.json())
      .then(({ nodes, links }) => {
        setGraphData({ nodes, links });
      });
  }, []);

  useEffect(() => {
    if (graphData) {
      setPrunedTree(getPrunedTree(graphData));
    }
  }, [graphData]);

  const handleAddNode = useCallback(() => {
    const nodeID = uuid();
    const nodeID2 = uuid();
    const newNode = {
      id: nodeID,
      collapsed: false,
      childLinks: [],
    };
    const newNode2 = {
      id: nodeID2,
      collapsed: false,
      childLinks: [],
    };
    const newLink = {
      source: selectedNode.id || '1',
      target: nodeID,
    };
    const newLink2 = {
      source: selectedNode.id || '1',
      target: nodeID2,
    };
    selectedNode.collapsed = false;
    const newNodes = graphData
      ? [...graphData.nodes, newNode, newNode2]
      : [newNode, newNode2];
    const newLinks = graphData
      ? [...graphData.links, newLink, newLink2]
      : [newLink, newLink2];
    setGraphData({
      nodes: newNodes,
      links: newLinks,
    });
  }, [graphData, selectedNode]);

  const handleSelectNode = (node: any) => {
    setSelectedNode(node);
  };

  const handleExpandNode = () => {
    selectedNode.collapsed = !selectedNode.collapsed; // toggle collapse state
    setPrunedTree(getPrunedTree(graphData));
  };

  const handleDragEnd = (node: any) => {
    node.fx = node.x;
    node.fy = node.y;
    node.fz = node.z;
  };

  const handleDeleteRelation = () => {
    if (selectedLink) {
      const newLinks = graphData.links.filter((link) => link !== selectedLink);
      setGraphData((prev) => ({
        ...prev,
        links: newLinks,
      }));
    }
  };

  const handleSelectLink = (link: any) => {
    setSelectedLink(link);
  };

  const handleFilter = () => {
    const relations = ['PROCESS'];
    const newLinks = graphData.links.map((link) => ({
      ...link,
      filtered: relations.includes(link.type),
    }));
    setGraphData((prev) => ({
      ...prev,
      links: newLinks,
    }));
  };

  const drawMenu = useCallback((node, ctx) => {
    const R = 17;
    const startAngle = Math.PI;
    const endAngle = 0;
    ctx.beginPath();
    ctx.arc(node.x, node.y, R, startAngle, endAngle, false);
    ctx.fillStyle = 'red';
    ctx.fill();
  }, []);

  return (
    <div>
      <button onClick={handleAddNode}>Add</button>
      <button onClick={handleExpandNode}>Expand</button>
      <button onClick={handleDeleteRelation}>Delete relation</button>
      <button onClick={handleFilter}>Filter Process</button>
      <div
        style={{
          display: 'flex',
        }}>
        <ForceGraph2D
          nodeRelSize={8}
          graphData={prunedTree}
          nodeLabel='name'
          width={640}
          nodeColor='color'
          linkDirectionalParticles={2}
          linkCurvature='curvature'
          linkColor={(link) => ((link as any).filtered ? 'gray' : 'orange')}
          nodeCanvasObjectMode={(node) =>
            selectedNode === node ? 'before' : (undefined as any)
          }
          // nodePointerAreaPaint={(node, _, ctx) => drawMenu(node, ctx)}
          onNodeClick={handleSelectNode}
          onLinkClick={handleSelectLink}
          onNodeDragEnd={handleDragEnd}
          linkDirectionalParticleWidth={2}
          nodeCanvasObject={(node, ctx) => drawMenu(node, ctx)}
        />
        <div style={{ width: '300px', backgroundColor: 'gray' }}>
          <span>{selectedNode?.name}</span>
          <p>{`Target: ${
            selectedLink ? JSON.stringify(selectedLink.target?.id) : null
          }, Source ${
            selectedLink ? JSON.stringify(selectedLink.source?.id) : null
          }`}</p>
        </div>
      </div>
    </div>
  );
}

export default App;

```

**Comment by jMoulis** [comment]
@vasturiano It is just a dummy file. Based on example you've made. I do create a semi circle on node click, but when I set the nodePointerAreaPaint (which I commented out). I don't get any onClick event anymore. I thank you very much for the wonderful work you've done and your help.

**Comment by vasturiano** [comment]
@jMoulis when using `nodePointerAreaPaint` you should use the provided color to fill in the shape of your click area, as explained in the docs:

> Callback function for painting a canvas area used to detect node pointer interactions. The provided paint color uniquely identifies the node and should be used to perform drawing operations on the provided canvas context. This painted area will not be visible, but instead be used to detect pointer interactions with the node. The callback function has the signature: `nodePointerAreaPaint(<node>, <color>, <canvas context>, <current global scale>)`.

**Comment by jMoulis** [comment]
@vasturiano Ok thanks a lot. I only have one thing to do. I have two arcs around the node and each of them have a different event so I need to keep track of the clcikable area. Thanks a lot again.

**Comment by SilvaLucas92** [comment]
HEYY im working on something similar. Could you resolve the click on the menu?
