### ISSUE TITLE
'Bezier' is not exported from 'bezier-js'

### ISSUE THREAD

**Issue by Caitlin2694** [vasturiano/react-force-graph#307]
Hi there,

I'm having an issue installing react-force-graph into my React app. I am getting the following compilation error:

./node_modules/force-graph/dist/force-graph.module.js
Attempted import error: 'Bezier' is not exported from 'bezier-js'.

*** to reproduce
create new app with npx create-react-app. Install react-force-graph and import with:
import { ForceGraph2D, ForceGraph3D, ForceGraphVR, ForceGraphAR } from 'react-force-graph';

Any help would be appreciated. Let me know if you need more information.

Kind Regards,
Caitlin

**Comment by jediswear** [comment]
Hello, same issue [#282](https://github.com/vasturiano/react-force-graph/issues/282)

**Comment by vasturiano** [comment]
@Caitlin2694 please see https://github.com/vasturiano/react-force-graph/issues/282#issuecomment-829112901
