### ISSUE TITLE
onDrag detection

### ISSUE THREAD

**Issue by GeoffGodwin** [vasturiano/react-force-graph#31]
While the API shows methods for onHover and onClick of both nodes and links, there doesn't readily appear to be a way of detecting drag events. In my own project I save the locations of elements and would like to do this at the end of a drag event. Are there plans / an existing strategy to accomplish this detection of drag states?

**Comment by vasturiano** [comment]
@GeoffGodwin thanks for mentioning. Just added two event methods to handle this: `onNodeDrag` and `onNodeDragEnd`. Let me know if it works for you.

**Comment by GeoffGodwin** [comment]
Looks great, I'll try it out ASAP. I did notice that it doesn't appear to be published in NPM though. Not sure if you meant to push it out.

**Comment by GeoffGodwin** [comment]
Nevermind, it is published, I'm having my own NPM problems locally.

**Comment by GeoffGodwin** [comment]
Works like a charm! Thank you again.
