### ISSUE TITLE
React 3D & 2D Graphs - How to pause animation when component not displayed?

### ISSUE THREAD

**Issue by ken-murray** [vasturiano/react-force-graph#311]
Hi, I have a React class component and need to reference the Graph within componentDidUpdate() to pause or resume the opening animation/simulation depending on whether the browser tab window and the tab in App.s within which the Graph is displayed are visible or not.  Any suggestions on how I can reference the Graph in that method so I can call pauseAnimation() and resumeAnimation() on the graph?  Or any other suggestions on the best approach.  Thanks.

..Includes

//Included in one of App.js tabs - other tabs may be clicked on while this Graph starts it's animation.
export default class Graph extends Component {
	constructor(props) {
		...
	}

	...

	componentDidUpdate(prevProps) {
		... pause Force Graph when this Tab is not shown, or when another browser tab/window has the focus
		... resume Force Graph when this Tab is shown and this browser tab/window has the focus
	}

	render() {
		return (
			<>
				...

				<ForceGraph3D
					id="forceGraph3D"
					...
				/>

			</>
	}
  }
  
  ReactDOM.render(<Graph />, document.getElementById("root"));

**Comment by ken-murray** [comment]
Note: adding this within the ForceGraph3D tag doesn't pause the opening (expanding/charge repulsion) animation.

<ForceGraph3D
	id="forceGraph3D"
	pauseAnimation={() => {
		return true;		//Has no effect
	}}
</>

**Comment by vasturiano** [comment]
@ken-murray `pauseAnimation` is a component **method**, not **prop**.
You invoke it via a forward ref, created using `useRef`, like in this example:
https://github.com/vasturiano/react-force-graph/blob/e67177b3522e2ffd212f807cbb6b74ed04a39ab6/example/camera-auto-orbit/index.html#L27

**Comment by ken-murray** [comment]
Thank you, I modified the code accordingly but I think I've misunderstood what Pause and Resume do.  After the nodes and links data has been loaded the repulsive charges start the expansion animation to push the nodes to their eventual settled positions in the 3D space.

If the user interrupts this opening expansion animation by switching to another tab in the React web application or to another tab in their browser, the expansion will pause.  But when they do return to this tab the expansion will not continue/resume and they'll just see a glob of nodes that were stalled in flight somewhere near the centre of their screen.

The console log confirms the resumeAnimation() method was called when the tab gained focus again, so maybe I'm just misunderstanding the purpose of pause/resume and whether it relates to the opening expansion animation in any way.

**Comment by vasturiano** [comment]
@ken-murray that is because of the `cooldownTime` which defaults to `15s`.

For your use case I would recommend setting that to `Infinity` and switch to a reasonable value in the `cooldownTicks` (say `100` is a good starting point) as a driver for the cooldown period.

**Comment by ken-murray** [comment]
Thanks again @vasturiano, you just solved the issue I spent days trying to fix the wrong way :-)

**Comment by ken-murray** [comment]
:-)
