### ISSUE TITLE
Memoization for data update

### ISSUE THREAD

**Issue by corbin-c** [vasturiano/react-force-graph#319]
Hi,

first of all, thank you for the great work.

I'm using react-force-graph with react-redux, which keeps my data store, including the graph data. This data is updated regularly by API calls.

I'm facing a problem: if I use the following pattern, react-force-graph wants to modify the data in my store:

```
  const [graphData, setGraphData] = useState({ nodes: [], links: [] });
  const nodes = useSelector(state => state.graph.nodes);
  const edges = useSelector(state => state.graph.edges);
  useEffect(() => {
    setGraphData({
         nodes,
         links: edges
    });
  }, [nodes, edges]);

  return (<ForceGraph3D graphData={ graphData } />
```

Obviously, I don't want react-force-graph to modify the data in my store. (Anyway, if I use slices from redux-toolkit (based on Immer), which freeze the data objects, react-force-graph won't work.)

On the other hand, if I entirely build new arrays (cloning) before passing them to the ForceGraph3D, I have the "heartbeat/re-render" issue mentionned several times in this repo issues (eg <https://github.com/vasturiano/react-force-graph/issues/229> or <https://github.com/vasturiano/react-force-graph/issues/226>).

To all these issues, you adviced to used memoization to solve the problem. Could you provide a simple example of how to achieve this? (avoiding useless re-render but without modifying the original dataset)

Thanks for your time and congrats again for creating & maintaining this awesome lib

**Comment by vasturiano** [comment]
@corbin-c thanks for reaching out.

I would try to do the memoization as you're cloning the original data, possibly using `useMemo`. Something like:
```js
const graphData = useMemo(
  () => ({
    nodes: cloneNodes(originalNodes),
    links: cloneEdges(originalEdges)
  }), 
  [originalNodes, originalEdges]
);
```

That way `graphData` will remain the same across re-renders, and the cloning will only re-occur when your original data has changed.

Naturally, the implementation of `cloneNodes` and `cloneEdges` is up to you. 😄

**Comment by corbin-c** [comment]
Thank your for the tip
