### ISSUE TITLE
How to get the Graph instance in React

### ISSUE THREAD

**Issue by bt2414** [vasturiano/react-force-graph#32]
In Javascirpt verions, we can have:

const Graph = ForceGraph3D()

I want to access the Graph in React so I can do some changes. 

I found this link and know someone has already implemented the feature:

https://github.com/vasturiano/react-force-graph/issues/21

In the issue, we can have: Graph.nodeRelSize(this.relSize);

Can anyone tell me a method to do it? Thanks

**Comment by vasturiano** [comment]
@bt2414 you need to get the `ref` to the element from React, like in this example:
https://github.com/vasturiano/react-force-graph/blob/master/example/dynamic/index.html#L59

**Comment by bt2414** [comment]
@vasturiano Hi, I think I have already used the this.ref, in my code I just used:

this.fg.nodeRelSize(4);

But it gives me the function is not found problem:

app.js:92041 Uncaught TypeError: this.fg.nodeRelSize is not a function
    at GraphCom.clickChangeColor (app.js:92041)
    at onClick (app.js:92089)
    at Button._this.handleClick (app.js:92227)
    at HTMLUnknownElement.boundFunc (app.js:56065)
    at Object.ReactErrorUtils.invokeGuardedCallback (app.js:56071)
    at executeDispatch (app.js:55856)
    at Object.executeDispatchesInOrder (app.js:55879)
    at executeDispatchesAndRelease (app.js:5018)
    at executeDispatchesAndReleaseTopLevel (app.js:5029)
    at Array.forEach (<anonymous>)

Could you give me an idea about where goes wrong?

Thanks so much.

**Comment by vasturiano** [comment]
@bt2414 `nodeRelSize` is a prop, not a method. So, you can use it the conventional way in your React component, no need to invoke it on the ref:
```
<ForceGraph3D
  graphData={data}
  nodeRelSize={4}
/>
```

**Comment by bt2414** [comment]
@vasturiano I need to use it for future updating the graph.

As I mentioned in:

https://github.com/vasturiano/react-force-graph/issues/21

It can access the function by using:

Graph.nodeRelSize(this.relSize);

Do you have any idea about how to do it?
