### ISSUE TITLE
Adding a new 2D Forcegraph  component to page messes up links in existing canvas

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#320]
**Describe the bug**
In a multi-tab application, adding a new tab with an empty 2D Forcegraph component disconnects links from nodes in previously rendered Forcegraph components.

**To Reproduce**

1. Create a multi-tab application where each tab contains a Forcegraph 2D component
2. Initialize a tab and add some graphData to the Forcegraph 2D component
3. Open a new tab with an empty Forcegraph 2D component
4. Return to first tab and see that links and nodes are disconnected

**Expected behavior**
Different Forcegraph 2D components function independently

**Observed behavior**
Instantiating new Forcegraph 2D components interferes with existing

**Screenshots**

https://user-images.githubusercontent.com/30726223/134673589-4a292362-580f-4f9d-93a7-9a3cf3851002.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox
 - Version: latest

**Comment by vasturiano** [comment]
@JonThom possibly you are using a shared data structure between the two graphs, which is leading to the interference. If so, I would recommend deep cloning the data before using it in another component.

**Comment by JonThom** [comment]
@vasturiano thanks for the feedback. 
The shared data structure possibility occurred to me as well, but that doesn't seem to be the case. As the video shows, it happens even when just instantiating a new component where `graphData={"nodes":[], "links":[]}`

**Comment by JonThom** [comment]
Update: It seems the problem arises when the component is un-rendered and re-rendered when changing tabs. 
This leads to the issue where the link source and target are replaced with the full node objects, leading to the issue shown in the video.
In case this is of use to anyone else the kludge I have implemented is
* When the user leaves a tab, make nodes and links invisible
* When a tab is opened, we replace source and target in links with the node ids, and restore node and link visibility. 

(the point of making the nodes and links invisible when the tab is hidden is that otherwise, when the user switches back to the tab, the link source and target take a bit of time to get updated, so the user will see the disconnected links)

The tabs component is from Antd design.

If no one adds anything else within the next few days, I'll close the issue.
