### ISSUE TITLE
How to prevent node with fixed position from losing their force ?  

### ISSUE THREAD

**Issue by slechanii** [vasturiano/react-force-graph#322]
Hi, I have a graph where nodes have their position fixed after being dragged (with f.x and f.y), it works great but I also found out that any fixed node seem to no longer apply any force to others (as if a fixed node doesn't exist from the simulation viewpoint).

Is my assumption correct ? If it is, is there something I can do to make it so that fixed nodes still apply their force to other nodes ?

I came to this conclusion when I saw that : 
1) Nodes that are linked to a "fixed" node that is dragged away from them will pack together closely and drift in the opposite direction of where the fixed node is
2) Double clicking on a node in my graph can spawn multiple nodes at once all linked to the clicked node, when doing that on a non fixed node the father node will be at the center of the new nodes, but when the father node has a fixed position the new nodes will pack together and drift away from the father as in my first problem

Here are images to illustrate the problem :
       This is what happens when adding nodes to a non fixed node
![Screenshot from 2021-09-30 11-06-12](https://user-images.githubusercontent.com/57493247/135423099-13694e99-f576-407d-9d3d-4d81e008a24e.png)
 
This is what happens when adding nodes to a fixed node (I would like it to work like in the first image) 
![Screenshot from 2021-09-30 11-05-54](https://user-images.githubusercontent.com/57493247/135423253-dea45bc5-0744-4b5b-8d67-fc652aa290f6.png)

 Thanks for your help.

**Comment by vasturiano** [comment]
>  I also found out that any fixed node seem to no longer apply any force to others (as if a fixed node doesn't exist from the simulation viewpoint).

No, a fixed node will still contribute to the "charge" force that affect others nodes, just like any regular node.

Normally, this drifting artifact is caused by the "center" force which tries to equalise the center of gravity of the chart. Since it can't move the fixed nodes, it will move the free ones much more drastically in the opposite direction to compensate. 

You can try switching off this force to see if the artifact disappears:
```js
myChart.d3Force('center', null);
```

**Comment by slechanii** [comment]
Thanks a lot for your help it works properly now!

As a side question I am trying to also change the "charge" strenght from the default value of -30 to -50, i think I don't understand how to properly do it as it throws an error could you explain to me the proper way of doing it ? I think I misunderstood the doc.

Here's what I'm doing :
` myGraphRef.current.d3Force('charge', () => {return -50});`   

Thanks a lot for your help and this great library :+1:

**Comment by vasturiano** [comment]
@slechanii it should be the `strength`: property of the charge force, like so:
```js
myGraphRef.current.d3Force('charge').strength(-50)
```

**Comment by slechanii** [comment]
Thanks a lot it works
