### ISSUE TITLE
Dynamic import breaks graph method calling through a ref

### ISSUE THREAD

**Issue by Docter60** [vasturiano/react-force-graph#324]
**Describe the bug**
&nbsp;&nbsp;&nbsp;&nbsp;Dynamic importing of ForceGraph3D breaks usage of component methods through a ref.  

> #### Unhandled Runtime Error
> ##### TypeError: fgRef.current.cameraPosition is not a function

&nbsp;&nbsp;&nbsp;&nbsp;The main difference here is usage of Next.js and Typescript.  In order for the graph to display correctly, the ForceGraph3D component must be dynamically imported. However, this breaks calling the graph's cameraPosition method. Making the forward ref component results in identical behavior.
&nbsp;&nbsp;&nbsp;&nbsp;I should also note that NOT dynamically importing results in the ssr broken graph problem. In this case, calling the cameraPosition method DOES work when you click on the broken graph's node.

**To Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/nextjs-typescript-react-force-graph-3d-o41ty) example
2. Click on src/FocusGraph.tsx
3. Scroll down to cameraPosition call
4. See error in preview/console

**Expected behavior**
&nbsp;&nbsp;&nbsp;&nbsp;Essentially the same behavior as the [Click to focus on node](https://vasturiano.github.io/react-force-graph/example/click-to-focus/) ([source](https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html)) example.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/11632779/137010363-10429abf-74ac-425d-ba46-93800ed48e63.png)

**Desktop:**
 - OS: Fedora 34
 - Browser Brave (fork of chromium)
 - Version Brave: 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)

**Additional context**
This may not be a bug, so I may be doing something wrong here. Any advice is appreciated.

**Comment by Docter60** [comment]
Oh wow, brilliant!  Thank you for your reply and showing me a work-around.

**Comment by srivsaks** [comment]
Works now!Thanx :)

**Comment by SayedMajid** [comment]
This doesn't work in next.js, I've tried the exact steps
