### ISSUE TITLE
Change Link Distance Dynamically Using a Selector

### ISSUE THREAD

**Issue by DanaKailani** [vasturiano/react-force-graph#329]
I'm reporting a bug and also asking if you could help me fix it.

What I need:
I need to let the user change the link distance dynamically from a dropdown selector depending on the selector state using this line of code:

`useEffect(() => { 
      fgRef.current.d3Force('link').distance((link) => link.source[params.distance]
}, [params.distance])
`

Problem:
It only works for the first 4 seconds after the page loads for the first time (you have to quickly test changing selection), but then the distance stops changing no matter what you select.

**Comment by vasturiano** [comment]
@DanaKailani thanks for reaching out.

It's hard to say without wider context. Do you have a reduced example on [codesandbox](https://codesandbox.io/) that consistently reproduces your issue?

**Comment by DanaKailani** [comment]
Thank you for your fast response!

Here is the reduced code on codesandbox:
https://codesandbox.io/s/3d-react-graph-r8lcv?file=/src/App.js:1806-1812

For testing: please change the "Distance" selector the second the page
first loads. If you keep changing quickly, you can see distance changing
until it slowly stops. But if you wait a few seconds after the page loads,
you'll never see a change!

Note: The Size and Thickness Selectors work perfectly because they are
changing the value in nodeColor and linkWidth props. But the only issue is
manipulating the link distance because it's not a prop.

Many Thanks!

**Comment by DanaKailani** [comment]
Thank you for your fast response!

Here is the reduced code on codesandbox:
https://codesandbox.io/s/3d-react-graph-r8lcv

For testing: please change the "Distance" selector the second the page first loads. If you keep changing quickly, you can see distance changing until it slowly stops. But if you wait a few seconds after the page loads, you'll never see a change!

Note: The Size and Thickness Selectors work perfectly because they are changing the value in nodeColor and linkWidth props. But the only issue is manipulating the link distance because it's not a prop.

**Comment by DanaKailani** [comment]
@vasturiano  Thank you for your fast response!

Here is the reduced code on codesandbox: [https://codesandbox.io/s/3d-react-graph-r8lcv](url)

For testing: please change the "Distance" selector the second the page first loads. If you keep changing quickly, you can see distance changing until it slowly stops. But if you wait a few seconds after the page loads, you'll never see a change!

Note: The Size and Thickness Selectors work perfectly because they are changing the value in nodeColor and linkWidth props. But the only issue is manipulating the link distance because it's not a prop.

**Comment by DanaKailani** [comment]
@vasturiano Thank you for your fast response!

Here is the reduced code on codesandbox: [link](https://codesandbox.io/s/3d-react-graph-r8lcv)

For testing: please change the "Distance" selector the second the page first loads. If you keep changing quickly, you can see distance changing until it slowly stops. But if you wait a few seconds after the page loads, you'll never see a change!

Note: The Size and Thickness Selectors work perfectly because they are changing the value in nodeColor and linkWidth props. But the only issue is manipulating the link distance because it's not a prop.

**Comment by vasturiano** [comment]
Also, you might want to reheat the simulation engine at every change of link distance (using the component method `.d3ReheatSimulation()`), if you'd like the effect to be noticeable.

**Comment by DanaKailani** [comment]
@vasturiano Yes it actually works after reheating the simulation! I guess I just couldn't figure out the problem at first.
Thank you so much!
