### ISSUE TITLE
Get node viewport absolute position

### ISSUE THREAD

**Issue by sergey-chuvayev** [vasturiano/react-force-graph#33]
I need to open a context menu when clicking on the node. The problem is that the onNodeClick callback parameter gives me the values which don't look like absolute position:

`fx: undefined,
fy: undefined,
vx: 0,
vy: 0,
x: 12.152664474162155,
y: 12.520373695711815`

**Comment by vasturiano** [comment]
@sergey-chuvayev assuming you are using the 2D version, those coordinates are relative to the current scale and translate of the canvas (changed by zooming and panning). If you wish to get the absolute screen positions you can just get the current mouse coordinates.
