### ISSUE TITLE
Overlapping linked nodes 

### ISSUE THREAD

**Issue by ioanachi** [vasturiano/react-force-graph#332]
Hi,

I am using force graph 2d and I have an issue. The diameter of the nodes  varies they overlap when are linked because the length of the link is too short.  I know  the length of the link can be increased but that would require looping through all the nodes and increasing the length according to the diameter of the linked nodes which would affect the speed of the rendering especially when having lots of data. Is there another way to solve this ?

Thank you!

![Screen Shot 2021-11-25 at 5 46 14 PM](https://user-images.githubusercontent.com/30567873/143471675-dc2037d1-0839-43ab-8186-adab971101ed.png)
e?

**Comment by JonThom** [comment]
@ioanachi if the nodeVal node prop corresponds to node size how about something like 
```
const LINK_LENGTH_CONSTANT = 123;
fgRef.current
    .d3Force("link")
    .distance((link) => LINK_LENGTH_CONSTANT * Math.max(link.source.nodeVal, link.target.nodeVal );
```

**Comment by ioanachi** [comment]
@JonThom thank you very much, that solves the problem of the link, but unfortunately the neighboring nodes that have similar width still overlap, especially when there are multiple with the same width.
Making the LINK_LENGTH_CONSTANT random or equal to the index of the link makes the modes overlap others from the graph.
