### ISSUE TITLE
Ref has only retry function

### ISSUE THREAD

**Issue by veselinn** [vasturiano/react-force-graph#333]
I'm trying to add an additional [force collide](https://github.com/d3/d3-force#forceCollide) with the following code (inspired by the [node collision detection example](https://github.com/vasturiano/react-force-graph/blob/master/example/collision-detection/index.html)):

```
export default function Funds({ data }) {
  const fgRef = useRef();

  useEffect(() => {
    const fg = fgRef.current;

    const collision = forceCollide()
      .strength(0.7)
      .radius((d) => scale(d.val))
      .iterations(2);

    console.log("useEffect", { fg });

    fg.d3Force("collide", collision);
  }, [scale]);

  return (
    <div>
      <ForceGraph2D ref={fgRef} graphData={data} width={1200} height={800} />
    </div>
  );
}
```

but I fail with the following error:

```
Unhandled Runtime Error
TypeError: fg.d3Force is not a function
```

The value of the ref is:

![image](https://user-images.githubusercontent.com/1181957/145416238-9fabfb7a-af91-4108-a580-f34a2ad569a0.png)

Am I doing something wrong? Please help :pray:

**Comment by Tylerpfarris** [comment]
facing the same problem-- Im using Next.js and dynamically importing ForceGraph3D to disable server side rendering. Assuming this is where the issue lies. Haven't found a solution as of yet-- but its early.

**Comment by Tylerpfarris** [comment]
[This fixed it for me](https://github.com/vasturiano/react-force-graph/issues/324#issuecomment-942725048)

**Comment by veselinn** [comment]
@Tylerpfarris Thank you for the link with the workaround! Really appreciated! Works for me too.

Closing the issue.
