### ISSUE TITLE
Support for context menus, and menus in general I guess

### ISSUE THREAD

**Issue by duhmojo** [vasturiano/react-force-graph#335]
Hi. I'm trying to add right click context menu support to a 2D graph I'm working on, but the onNodeRightClick property only provides me with a copy of the node (with some x/y properties that I can't seem to figure out how to use) and the event. In my React component I have a simple menu <div> where I set the style top/left based on coordinates from the onNodeRightClick function, that also sets the menu to be visible.

I want to show a context menu when I right click on a graph node. From what I can tell, I need to know the node position within the browser window (or relative from within the canvas), so I can set the menu's top/left and have it appear next to the node.

Any tips? Should I be trying to track the user's mouse/click position on the page? Thanks and great work on the module!

**Comment by JonThom** [comment]
```
   const [nodeRightClickedCoordinates, setNodeRightClickedCoordinates] = useState(null);
   const fgRef = useRef(null);

   const handleNodeRightClick = (node, event) => {

        if (node) {

            setNodeRightClickedCoordinates(fgRef.current
                    ? fgRef.current.graph2ScreenCoords(
                        node.x,
                        node.y
                    )
                    : null);

        }

    };

```
...
```
   return (
        <div id={props.id}>
                <ForceGraph2D
                    ref={fgRef}
                    // OTHER PROPS
        </div>
    );


```

**Comment by duhmojo** [comment]
Thanks JonThom. I'm using a Component but I'll give graph2ScrenCoords a try. I managed to make it work last night using the event target offset and clientX/Y:

```
                    onNodeRightClick={
                        (node, event) => {
                            this.setState({ 
                                contextMenuShow: true, 
                                contextMenu: {
                                    ...this.state.contextMenu,
                                    selectedId: node.id,
                                    top: event.clientY - event.target.offsetTop,
                                    left: event.clientX - event.target.offsetLeft
                                }
                            })
                        }
                    }
```

One thing everyone that tries to add this should know, you'll want to handle off clicks to auto close the context menu (and unless you want to updated the menu position when zoom/pan occurs, you'll want to close during those events as well) by both attaching the mouse down event listener on mount (and remove it on unmount), but also when any other graph event fires. If don't do both (detect changes inside and outside of the graph area) when the background, node/edge single, double and right clicks occur, the menu will stay open. Last you'll want to do it onZoom as well, so if the user opens the menu, then zooms/pans the menu will close as well.

```
    closeContextMenu(event) {
        if(this.state.contextMenuShow) {
            if(event) {
                // if click was outside canvas...
                if(this.contextMenu && !this.contextMenu.contains(event.target)) {
                    this.setState({
                        contextMenuShow: false
                    });
                }
            } else {
                // manual call to close, no click event
                this.setState({
                    contextMenuShow: false
                });
            }
        }
    }

    componentDidMount() {
        // listen for outside graph events
        document.addEventListener('mousedown', this.closeContextMenu)
    }

    componentWillUnmount() {
        document.removeEventListener('mousedown', this.closeContextMenu)
    }
    ...
                <ForceGraph2D
                    ...
                    onBackgroundClick={
                        (event) => {
                            this.closeContextMenu();
                        }
                    }

                    onBackgroundDoubleClick={
                        (event) => {
                            this.closeContextMenu();
                        }
                    }

                    onZoom={ //zoom/pan
                        ({k,x,y}) => {
                            this.closeContextMenu();
                        }
                    }
```

It all seems messy and maybe there's a better way to track an off click (like layering a, invisible div behind the menu but that would block natural pan/zoom, you would have to click off first to then zoom/pan and if the click was to an actionable control, the user would have to click twice to make it work) but this works for me after a night of messing around.

**Comment by oneillsp96** [comment]
@duhmojo is onBackgroundDoubleClick a legitimate prop? I don't see it in the docs anywhere?
