### ISSUE TITLE
Multiple instances of Three.js being imported.

### ISSUE THREAD

**Issue by ceiphr** [vasturiano/react-force-graph#340]
**Describe the bug**
Creating a new `nodeThreeObject` using Three.js results in this warning being emitted in the browser:

```
WARNING: Multiple instances of Three.js being imported.
```

**To Reproduce**
See img-nodes example: https://vasturiano.github.io/react-force-graph/example/img-nodes/

**Expected behavior**
There should be some way to avoid multiple instances of Three.js.

**Screenshots**
![Warning Screenshot](https://i.imgur.com/Ia2rqri.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Chrome, Firefox
 - Version: 96.0.4664.110, 96.0b10

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Browser: Chrome, Firefox
 - Version: Latest

**Comment by vasturiano** [comment]
That warning shouldn't be causing any issues with the behaviour of the component. Are you observing any problems related to it?

**Comment by ceiphr** [comment]
No issues. But given that it is warning me, I'm assuming there is some sort of problem with having multiple instances. Could this be a performance concern?

**Comment by vasturiano** [comment]
I think it's only informative. Yet I haven't noticed any problems arising from it.

**Comment by ceiphr** [comment]
Happy to hear that. I'll close this issue. Thank you!
