### ISSUE TITLE
Prevent re-renders on state change.

### ISSUE THREAD

**Issue by ceiphr** [vasturiano/react-force-graph#341]
**Describe the bug**
How can I prevent re-renders while also updating parts of the graph with state?

Example: Change the color of a nodeThreeObject with useState.
https://codesandbox.io/s/react-force-graph-statechange-tb2q5?file=/src/App.js
(Based on the [Image nodes](https://vasturiano.github.io/react-force-graph/example/img-nodes/) example)

**To Reproduce**
1. Create a nodeThreeObject sprite
2. Update its color based on useState
3. Graph is re-rendered.

**Expected behavior**
Graph doesn't get re-created. Instead, it simply changes the color of the nodeThreeObject.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Firefox
 - Version: 96.0b10 (64-bit)

**Comment by ceiphr** [comment]
To narrow down my issue further, is there someway to prevent the nodeThreeObject sprites from being re-fetched? 

I'm working with it here: https://ari.gg/

Anytime I highlight some nodes, there is a flicker and all sprites are re-fetched.

**Comment by vasturiano** [comment]
@ceiphr seems like there's two separate issues here:

1 - Graph gets re-initialized on every update: This doesn't have to do with your use of `nodeThreeObject` but with the fact that you're re-creating a new data object (`graphData`) every time. The component interprets this as a completely new data set and thus re-initializes every node. If you want continuity between renders you should memoize your data object across updates. This is a common React pattern.

2 - Your images get re-fetched at every update. You can move the result of`TextureLoader` out of the `nodeThreeObject` method and index/cache it per object so it can be used by the Sprites across re-renders without needing to reload the images.

**Comment by ceiphr** [comment]
> 1 - Graph gets re-initialized on every update: This doesn't have to do with your use of `nodeThreeObject` but with the fact that you're re-creating a new data object (`graphData`) every time. The component interprets this as a completely new data set and thus re-initializes every node. If you want continuity between renders you should memoize your data object across updates. This is a common React pattern.

This helped with state related stuttering!

> 2 - Your images get re-fetched at every update. You can move the result of`TextureLoader` out of the `nodeThreeObject` method and index/cache it per object so it can be used by the Sprites across re-renders without needing to reload the images.

I'm storing the result of TextureLoader in a map state. It works perfectly now, thank you!
