### ISSUE TITLE
Reorder Node layering in 2D

### ISSUE THREAD

**Issue by majulahsingapuri** [vasturiano/react-force-graph#342]
Is there any way to reorder the nodes and force the expanded node to be on top of the children nodes? As shown below the central expanded node hides behind the children when zooming out.

<img width="474" alt="Screenshot 2022-01-20 at 10 10 50 AM" src="https://user-images.githubusercontent.com/13448687/150256012-a4df6891-dc8e-4f13-98b4-c61bdad8198d.png">
<img width="474" alt="Screenshot 2022-01-20 at 10 11 00 AM" src="https://user-images.githubusercontent.com/13448687/150255786-06bd343d-1a5b-4292-9c7a-e66b6b923bc7.png">

**Comment by vasturiano** [comment]
@majulahsingapuri the nodes are drawn in the order that they appear in the `nodes` array. So if you'd like a particular to appear "on top" compared to the others, you can just place it as last element in the array.

**Comment by majulahsingapuri** [comment]
Got it thanks!
