### ISSUE TITLE
Enable more than one link in the same direction between pair of nodes

### ISSUE THREAD

**Issue by JonThom** [vasturiano/react-force-graph#347]
**Is your feature request related to a problem? Please describe.**
I am using this (really great) library to visualize a datamodel where two nodes may be connected by two links, in the same direction. When rendering the links in the library, only one shows, however.

**Describe the solution you'd like**
It would be nice if the library would show more than one link between pairs of nodes as long as the links have different ids.  
No change in forces would be needed for my purposes - so fine either way if the links were to each contribute to the force layout or not.
The user could also decide how to deal with the overlap, e.g. by curving the links so the links don't overlap.

**Describe alternatives you've considered**
Using a single link with multiple labels. However this becomes difficult to manage in the application

**Comment by vasturiano** [comment]
@JonThom have you seen the [curved/multi links example](https://vasturiano.github.io/react-force-graph/example/curved-links/)?

**Comment by JonThom** [comment]
Thanks!
