### ISSUE TITLE
VR force graph crashes when `onNodeClick` is used on text sprite nodes.

### ISSUE THREAD

**Issue by epiqueras** [vasturiano/react-force-graph#356]
Amazing work on this lib! 👏  

Posting this bug I found, because I don't have time to debug it right now, in case someone else knows what causes it.

**Describe the bug**

The VR component crashes when a function is provided for the `onNodeClick` prop and text sprites are being used as node objects.

```
THREE.Sprite: "Raycaster.camera" needs to be set in order to raycast against sprites.
Uncaught TypeError: Cannot read properties of null (reading 'matrixWorld')
```

**To Reproduce**

Run this:

```html
<head>
  <style>
    body {
      margin: 0;
    }
  </style>

  <script src="//unpkg.com/react/umd/react.production.min.js"></script>
  <script src="//unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
  <script src="//unpkg.com/babel-standalone"></script>

  <script src="//unpkg.com/three"></script>
  <script src="//unpkg.com/three-spritetext"></script>
  <script src="//unpkg.com/react-force-graph-vr"></script>
</head>

<body>
  <div id="graph"></div>

  <script type="text/jsx">
    function genRandomTree(N = 300, reverse = false) {
      return {
        nodes: [...Array(N).keys()].map(i => ({ id: i })),
          links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          [reverse ? 'target' : 'source']: id,
          [reverse ? 'source' : 'target']: Math.round(Math.random() * (id-1))
        }))
      };
    }
    ReactDOM.render(
      <ForceGraphVR
        graphData={genRandomTree()}
        nodeAutoColorBy="id"
        onNodeClick={console.log}
        nodeThreeObject={node => {
          const sprite = new SpriteText(node.id);
          sprite.color = node.color;
          sprite.textHeight = 8;
          return sprite;
        }}
      />,
      document.getElementById('graph')
    );
  </script>
</body>
```

Removing `onNodeClick` fixes it.

**Comment by vasturiano** [comment]
@epiqueras thanks for the report.

More background on the reason behind this: https://github.com/vasturiano/3d-force-graph-vr/issues/21#issuecomment-929735516

**Comment by epiqueras** [comment]
Thanks for the info 😄 

What would you recommend doing if one needs to render clickable text like in the example above?

**Comment by vasturiano** [comment]
As far as I'm aware, I think that's just not possible currently. Most likely this needs to be fixed inside Aframe first, possibly in the `raycaster` component: https://github.com/aframevr/aframe/blob/master/src/components/raycaster.js

**Comment by epiqueras** [comment]
https://threejs.org/docs/index.html#api/en/objects/Sprite.raycast

>The raycaster must be initialized by calling [Raycaster.setFromCamera]()() before raycasting against sprites.

Is this something that needs to be done in Aframe?

**Comment by epiqueras** [comment]
Do you think I should close this and open an issue there?

**Comment by vasturiano** [comment]
@epiqueras yes that makes sense. Feel free to do so.

**Comment by epiqueras** [comment]
Done :)
