### ISSUE TITLE
Question: Is it possible to specify the order for children nodes

### ISSUE THREAD

**Issue by kyleAtQuantifind** [vasturiano/react-force-graph#361]
Assuming the parent node has 10 children nodes, and I want children node 2 to be next to children node 1. It seems the children nodes are placed randomly around the parent node now.

**Comment by vasturiano** [comment]
@kyleAtQuantifind the position of the nodes on the canvas is purely determined by the forces active in the system. And their starting position is not random, but instead follows a [phyllotaxis arrangement](https://observablehq.com/@d3/force-layout-phyllotaxis).

So, if you'd like node 2 to be attracted to node 1 you'd need to add an attraction force to the system that encodes that logic.

**Comment by kyleAtQuantifind** [comment]
Thank you!
