### ISSUE TITLE
Performance problems caused by NodeCanvasObject

### ISSUE THREAD

**Issue by slechanii** [vasturiano/react-force-graph#363]
Hello, I am currently using a 2D graph with custom svgs and I noticed big performance drops when rendering a lot of nodes so I started investigating.

I noticed that the NodeCanvasObject callback is called approximatively 900 times per node rendered (Moving something on the graph will trigger the call 900 * number of nodes)

I think my performance problems come from this callback, I do a lot of things in this callback and its not very well optimized.

What I'd like to know is if it's normal behaviour to get called ~900 times and I should just optimize the callback or if getting called this much is not normal and there's something I can do to decrease the call count (on top of optimizing what the callback does)

Thanks a lot for the help.

**Comment by vasturiano** [comment]
@slechanii it is expected that these methods are called very frequently. Essentially they're called once per frame and per node. The Canvas redraws at every frame and that is how the nodes/links animation is perceived.
So, it is important to keep this method as optimized as possible. If there are sections of it that can be cached or pre-computed it's better to do so, and have there only the necessary canvas draw operations.

**Comment by FatmaAkram** [comment]
@slechanii Could you please state what kind of optimization you exactly did to come over the performance problem?

I'm overriding both `nodeCanvasObject` and `linkCanvasObject` to have customized hover & click styles, and it is super slow when navigating within the graph (styles don't append immediately on user actions)

**Comment by anyuruf** [comment]
@slechanii I think like useCallBack  and useEffect hooks
