### ISSUE TITLE
How to update one specific node or edge?

### ISSUE THREAD

**Issue by bt2414** [vasturiano/react-force-graph#37]
If I want to change a specific node(or edge), how can I do it?

For example, suppose every node has an id, after drawing the graph, I want to change node one(id: node1)'s color if I click a button outside the graph.

After clicking the button, what I did is to iterate the node list of the graph, and find the id to change the graph's color. However, how can I update the graph? I don't want to redraw the layout. Only change the node's color is enough.

Thanks in advance.

**Comment by qianlongwuyong2018** [comment]
@vasturiano Thanks so much.
I am just wondering if we can have a way to directly change to the whole graph instance after initializing the ForceGraph3D?
For example, if I want to add one edge from node1 to node2, how can I achieve that?

**Comment by vasturiano** [comment]
@qianlongwuyong2018 you can just change your graphData prop to reflect the changes you want, like dynamically adding/removing nodes/links. Here's an example:
https://vasturiano.github.io/react-force-graph/example/dynamic/

**Comment by bt2414** [comment]
@vasturiano Thanks for your reply. If I am using the dynamic graph method to do the update, I think the layout of the graph will be changed. Could you provide a way we can change the graph without changing the layout?

**Comment by vasturiano** [comment]
@bt2414 normally you want the force engine to reheat when changing data so that it adjusts spatially to the new topology. If you wish to bypass that, just set `cooldownTicks={0}` when updating the data to prevent the engine from reheating.
