### ISSUE TITLE
Trying to render 900,000 + nodes

### ISSUE THREAD

**Issue by cober2019** [vasturiano/react-force-graph#370]
**Describe the bug**
I'm trying to run a simulation for internet routing which includes 900,000 + nodes. The simulation launches fine and runs at 60 fps , but the simulation  hangs.

**Expected behavior**
I want the simulation to run smooth with no issues.

**Screenshots**
You can find the simulation here, http://20.121.26.153:3000/layer_three

**Desktop (please complete the following information):**
Backend is Ubuntu, client side is Windows w/ Browser=Chrome. 
GPU 1080TI 32G ram.
I'm using React for web

**Additional context**
I expect the simulation to drag with this many nodes, but I would think there would be a way to smooth it out. I've tried to use  rendererConfig(), change Chrome settings, and even look into GPU.js. Any ideas to lead me into the right direction would be great.

** You can get the data via API, curl http://20.121.26.153:5000/get_bgp_info**

**Comment by owen-duncan-snobel** [comment]
I am not sure if you have already looked at these but here are some conversations and threads from when people had tried to do "big data" visualizations in the past. 

[Big data performance enhancement #181 ](https://github.com/vasturiano/react-force-graph/issues/181)
[Improving performance for extremely large datasets #202 ](https://github.com/vasturiano/react-force-graph/issues/202)

**Comment by cober2019** [comment]
> I am not sure if you have already looked at these but here are some conversations and threads from when people had tried to do "big data" visualizations in the past.
> 
> [Big data performance enhancement #181 ](https://github.com/vasturiano/react-force-graph/issues/181) [Improving performance for extremely large datasets #202 ](https://github.com/vasturiano/react-force-graph/issues/202)

I have looked in to these threads. It appears they had trouble even rendering. I have no issues rendering, just the choppy scene. At 200Knodes its ok, 500K a little choppy. Beyond that it takes about 3 seconds to request animation frame.
