### ISSUE TITLE
Changing the properties of default DirectionalLight in 3D

### ISSUE THREAD

**Issue by xiaoxiaobt** [vasturiano/react-force-graph#374]
Hello, I would like to change the default position of the DirectionalLight, but I could not find a way to pass it when initializing the react-force-fraph-3d component, and I am unsure about the correct way of doing it. Could you provide some suggestions of doing it? Thank you in advance :D

**Comment by vasturiano** [comment]
@xiaoxiaobt by accessing the ThreeJS scene (via the `scene` component method) you should be able to browse the scene and access the existing light objects. From there you can either modify, replace or add lights in the way you prefer.

**Comment by xiaoxiaobt** [comment]
I see, thank you for your answer!
