### ISSUE TITLE
Measuring and improving performance

### ISSUE THREAD

**Issue by xiaoxiaobt** [vasturiano/react-force-graph#380]
Hello, I am working on a scene that has multiple sets of identical 3D objects with `react-force-graph-3d`, and the performance is still not great after trying some suggestions in other Issues. Therefore, I have two questions:

1. Would it be possible to use [Three.js InstancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh) with this library?
2. Is there a way to display FPS of the graph? I've tried Three.js Stats module (`three/examples/jsm/libs/stats.module`) but it does not show the value.

Thank you in advance!

**Comment by maui-r** [comment]
Some stats like FPS would be great!
