### ISSUE TITLE
Support React Strict Mode

### ISSUE THREAD

**Issue by noverby** [vasturiano/react-force-graph#390]
react-force-graph does not currently support react strict mode.

Enabling react strict mode results in an empty graph canvas.

**Comment by mocurin** [comment]
It works really weird.
For some time it was rendering fine even with a strict mode, then, after some minor changes, it stopped. But sometimes, after a few minutes of switching tabs around graph somehow renders

**Comment by vasturiano** [comment]
This is now fixed and `react-force-graph` can safely be used with React 18 in strict mode.
