### ISSUE TITLE
Tooltip on hover does not disappear 

### ISSUE THREAD

**Issue by chrisby** [vasturiano/react-force-graph#399]
**Describe the bug**
For *ForceGraph2D*, the tooltip that appears when we hover over a node does not disappear when the mouse leaves the node. 

**Expected behavior**
Tooltip should disappear once the node is not under the pointer. 

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Chome and Safari

**Comment by vasturiano** [comment]
@chrisby could you provide an online example that reproduces your issue?

And do you see it also happening on the included 2D example?
https://vasturiano.github.io/react-force-graph/example/tree/

**Comment by chrisby** [comment]
> @chrisby could you provide an online example that reproduces your issue?
> 
> And do you see it also happening on the included 2D example? https://vasturiano.github.io/react-force-graph/example/tree/

Indeed, it does not happen in the example. I see if I can get reproduce the problem and share it.

**Comment by chrisby** [comment]
So, I just created a react app with `npx create-react-app` (`npm` version = 8.19.2) and the only npm module I added was `react-force-graph`. I implement the basic example

```
import logo from './logo.svg';
import './App.css';

import {ForceGraph2D} from 'react-force-graph';
import genRandomTree from './random-data.js';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
      <ForceGraph2D graphData={genRandomTree()} nodeLabel='id'/>
    </div>
  );
}

export default App;
```

One warning I get and could be the cause is the following:
`WARNING: Multiple instances of Three.js being imported.`

Do think this could be the problem?

**Comment by chrisby** [comment]
Here in a sandbox:

https://codesandbox.io/embed/hidden-meadow-oi7v4c?fontsize=14&hidenavigation=1&theme=dark

**Comment by chrisby** [comment]
@vasturiano in the above codesandbox, do you also have the behavior that the tooltip does not disappear when leaving the node?

**Comment by vasturiano** [comment]
@chrisby this issue appears to be related to React18's strict mode. It is causing the Force Graph to malfunction. If you disable strict mode you'll notice that the component will behave fine. You can do that by removing the `<StrictMode>` tag in the `index.js` app root file.

**Comment by chrisby** [comment]
Thanks for the advice!
