### ISSUE TITLE
Add possibility to set link MeshMaterial

### ISSUE THREAD

**Issue by Benkevych** [vasturiano/react-force-graph#4]
I need the same functionality as `nodeThreeObject` , but for links, as i need to change it's material to `MeshBasicMaterial`. Thanks

**Comment by Benkevych** [comment]
i need something like this but with **gradient** color for links from source color to target color.
![screen shot 2018-04-13 at 17 03 47](https://user-images.githubusercontent.com/24266732/38739185-d6afb608-3f3c-11e8-8d88-8197f660d0a7.png)

**Comment by vasturiano** [comment]
@Benkevych from `v1.3.0` I've added a new prop that allows you to specify custom materials for the lines: `linkMaterial`. It works in a similar fashion as `nodeThreeObject`. You should be able to add a gradient to the links using material textures, something like:
```
<ForceGraph3D
  ...
  linkWidth={1}
  linkMaterial={link => new THREE.MeshBasicMaterial({ map: <gradientTexture>, transparent: true })}
>
```
