### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by SukPavel** [vasturiano/react-force-graph#41]
Hi I cannot load graph because of **Uncaught TypeError: selection.interrupt is not a function** in my react app.
I tried:
import { ForceGraph2D} from 'react-force-graph';
or
const{ ForceGraph2D} = require('react-force-graph');
...

return (
                        <ForceGraph2D
                            graphData={data}
                            nodeLabel="id"
                            nodeAutoColorBy="group"
                        />
        )

Detail error:
Uncaught TypeError: selection.interrupt is not a function
    at Function../node_modules/force-graph/node_modules/d3-zoom/src/zoom.js.__webpack_exports__.default.zoom.transform (zoom.js:90)
    at Function../node_modules/force-graph/node_modules/d3-zoom/src/zoom.js.__webpack_exports__.default.zoom.translateBy (zoom.js:119)
    at adjustCanvasSize (force-graph.module.js:605)
    at Function.init (force-graph.module.js:852)
    at u (kapsule.min.js:1)
    at Object.r [as comp] (kapsule.min.js:1)
    at FromKapsuleComp.componentDidMount (react-kapsule.module.js:85)
    at commitLifeCycles (react-dom.development.js:14685)
    at commitAllLifeCycles (react-dom.development.js:15905)
    at HTMLUnknownElement.callCallback (react-dom.development.js:145)

I have newest version of package.

What's wrong with my code?

**Comment by Cygnusfear** [comment]
This change to d3-zoom/src/zoom.js will fix the issue
https://github.com/d3/d3-zoom/pull/161/commits/0a942f763afc7813d4b1186a1928fcd8f276cf84

**Comment by SukPavel** [comment]
I already find the solution. Thank you ;)

**Comment by qasimalbaqali** [comment]
@Cygnusfear I have the latest version of `react-force-graph` which all sub dependencies are up to date, precisely `force-graph` has the `d3-zoom` version with the mentioned commit that fixes the issue, but I am still running into it. Any ideas?

**Comment by vasturiano** [comment]
@qasimalbaqali this sounds like a problem that happens when you have more than one version of `d3-selection` in your bundle. Can you check that?

**Comment by qasimalbaqali** [comment]
@vasturiano Thank you for your reply and amazing work! The project that I am working indeed has another `d3-selection` since we are using `d3` library for another part of the project, so I am guessing  you are right. Any ideas that you might have to guide me on how to solve an issue like this? The current version of `d3` that we are using is `@5.70`. 

I tried the fix that @Cygnusfear suggested, which means I have to tap into the node_modules folder to do this, which isn't a feasible solution for me. Any help would be highly appreciated Vasco :)

**Comment by vasturiano** [comment]
@qasimalbaqali if you have a dependency lock file (`yarn.lock` or `package-lock.json`) deduplicate the entries in that file so that you have a single instance/version of `d3-selection`. Then re-install the `node_modules`. That generally solves it.

**Comment by qasimalbaqali** [comment]
Vasco, can't thank you enough! It worked.

Tapped into the `yarn.lock` saw that d3-selection is indeed duplicated, but with different versions, 1.4.0 for react-force-graph and 1.1.0 for `d3@5.7.0`. The file looked like this


```
d3-selection@1, d3-selection@^1.1.0:
  version "1.3.2"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.3.2.tgz#6e70a9df60801c8af28ac24d10072d82cbfdf652"
  integrity sha512-OoXdv1nZ7h2aKMVg3kaUFbLLK5jXUFAMLD/Tu5JA96mjf8f2a9ZUESGY+C36t8R1WFeWk/e55hy54Ml2I62CRQ==

d3-selection@^1.4.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.0.tgz#ab9ac1e664cf967ebf1b479cc07e28ce9908c474"
  integrity sha512-EYVwBxQGEjLCKF2pJ4+yrErskDnz5v403qvAid96cNdCMr8rmCYfY5RGzWz24mdIbxmDf6/4EAH+K9xperD5jg==
```

I merged them together like so
```
d3-selection@1, d3-selection@^1.1.0, d3-selection@^1.4.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.0.tgz#ab9ac1e664cf967ebf1b479cc07e28ce9908c474"
  integrity sha512-EYVwBxQGEjLCKF2pJ4+yrErskDnz5v403qvAid96cNdCMr8rmCYfY5RGzWz24mdIbxmDf6/4EAH+K9xperD5jg==
```

Delete `node_modules` and ran `yarn install` and it all worked out!
