### ISSUE TITLE
Truly custom tooltips

### ISSUE THREAD

**Issue by AllysonPemberton-UnlikelyAI** [vasturiano/react-force-graph#413]
In particular I would like to have a persistent tooltip so that I could interact with the content on the tooltip without it disappearing. Beyond that, I would like to have custom tooltip content such as stylized buttons, scrollbars, etc. Ideally I'd like to inject something like a Popover (https://ant.design/components/popover) that shows up instead of the tooltip. 

`nodeLabel` doesn't achieve this because the tooltip is not persistent. If you try to mouse over the content it disappears because you are no longer hovering over the node. 

I thought of trying to use onNodeHover is some way, but as mentioned in https://github.com/vasturiano/3d-force-graph/issues/14#issuecomment-744185233 it's not possible to utilize this without details on where the node is.

**Comment by vasturiano** [comment]
@AllysonPemberton-UnlikelyAI `onNodeHover` provides you with the node being hovered, which includes the coordinates of the node in the 3D space (`x`, `y` and `z` attributes).  
You can convert those the screen domain using `graph2ScreenCoords`. That should give you all you need to be able to position your custom elements.

**Comment by AllysonPemberton-UnlikelyAI** [comment]
I see, thanks. I ended up going a different route, but hopefully this works for others :)
