### ISSUE TITLE
LinksLabels not showing up

### ISSUE THREAD

**Issue by Nejdro** [vasturiano/react-force-graph#414]
My ForceGraph3D: 
<ForceGraph3D
      graphData={data}
      nodeLabel="name"
      nodeAutoColorBy="group"
      linkThreeObjectExtend={true}
      linkLabel="name"
      linkThreeObject={(link: any) => {
        // extend link with text sprite
        const sprite = new SpriteText(`${link.source} > ${link.target}`);
        sprite.color = 'white';
        sprite.textHeight = 2.5;
        return sprite;
      }}
      showNavInfo={false}
    />

Graph being display and for example I have links between 'id1' to 'id2' and from 'id2' to 'id3', but in my graph I can see only one link label 'id1' to 'id2'.

My data: 
{
  "nodes": [
    {
      "id": "id1",
      "name": "name1",
      "val": 1
    },
    {
      "id": "id2",
      "name": "name2",
      "val": 2
    },
    {
      "id": "id3",
      "name": "name3",
      "val": 12
    },
    {
      "id": "id4",
      "name": "name4",
      "val": 10
    },

    {
      "id": "id8",
      "name": "name8",
      "val": 40
    }
  ],
  "links": [
    {
      "source": "id1",
      "target": "id2"
    },
    {
      "source": "id1",
      "target": "id3"
    },
    {
      "source": "id1",
      "target": "id4"
    },
    {
      "source": "id2",
      "target": "id3"
    },

    {
      "source": "id1",
      "target": "id8"
    },
    {
      "source": "id2",
      "target": "id3"
    }
  ]
}

**Comment by vasturiano** [comment]
@Nejdro please provide a simple example on https://codesandbox.io/ that reproduces your issue.

**Comment by Nejdro** [comment]
Here it is: codesandbox.io/s/zealous-bose-6zdv1n?file=/src/App.tsx

Also as you can see in that example, link label is [object object] - should be id1>id2
I build that based on https://github.com/vasturiano/react-force-graph/blob/master/example/text-links/index-3d.html 
but without linkPositionUpdate - can't figure it out how to use it in Typescript

**Comment by vasturiano** [comment]
You want to change this line use the `name` attributes of `source` and `target`:
```js
const sprite = new SpriteText(`${link.source.name} > ${link.target.name}`);
```

Because, the link `source` and `target` attributes get overwritten in place from the ids to the real objects they point to. This is done at the [d3-force-3d link force](https://github.com/vasturiano/d3-force-3d#link_links) level.

**Comment by Nejdro** [comment]
Thanks for that advice, but right now the link labels are in the same place, not like near actuall link and when I use 'linkPostionUpdate' just like in your example typescript throws an error: 

'Type '(sprite: Object3D, { start, end }: { start: Coords; end: Coords; }) => void' is not assignable to type 'LinkPositionUpdateFn'.
  Type 'void' is not assignable to type 'boolean | null'.ts(2322)
react-force-graph.d.ts(356, 3): The expected type comes from property 'linkPositionUpdate' which is declared here on type 'IntrinsicAttributes & ForceGraphProps$1 & { ref?: MutableRefObject<ForceGraphMethods$1 | undefined> | undefined; }''

and: 

Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Coords'.
  No index signature with a parameter of type 'string' was found on type 'Coords'

Do I need some additional params, props or maybe something else to make it work?

**Comment by vasturiano** [comment]
The types are now updated in the latest version to accomodate for the void return type.
