### ISSUE TITLE
Incorrect type for CanvasCustomRenderMode

### ISSUE THREAD

**Issue by process0** [vasturiano/react-force-graph#417]
**Describe the bug**

According to https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html `nodeCanvasObjectMode` should support a function which returns `undefined`.  The type is `  nodeCanvasObjectMode?: string | ((obj: NodeObject) => CanvasCustomRenderMode);` where `type CanvasCustomRenderMode = 'replace' | 'before' | 'after';`.

The example will not pass. Adding `//@ts-ignore` produces the expected behavior.

**To Reproduce**
1. Use Typescript
2. Run https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html 

**Expected behavior**

Compile successfully

**Screenshots**

Error message:
```
TS2322: Type '(node: NodeObject) => "before" | undefined' is not assignable to type 'string | ((obj: NodeObject) => CanvasCustomRenderMode) | undefined'.
  Type '(node: NodeObject) => "before" | undefined' is not assignable to type '(obj: NodeObject) => CanvasCustomRenderMode'.
    Type '"before" | undefined' is not assignable to type 'CanvasCustomRenderMode'.
      Type 'undefined' is not assignable to type 'CanvasCustomRenderMode'.
    192 |                     autoPauseRedraw={false}
    193 |                     // @ts-signore
  > 194 |                     nodeCanvasObjectMode={(node) => (highlightNodes.has(node) ? 'before' : undefined)}
        |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    195 |                     nodeCanvasObject={paintRing}
    196 |                     onNodeHover={handleNodeHover}
```

**Comment by vasturiano** [comment]
Thanks @process0. Types should be fixed now.
