### ISSUE TITLE
Canvas2d - willReadFrequently

### ISSUE THREAD

**Issue by JarnDev** [vasturiano/react-force-graph#419]
**Describe the bug**
Hey there, I'm using the react-force-graph-2d, and on the node I'm rendering images, but the console give me a warning from Canvas2d saying that to be more performant I sould enable the willReadFrequently attribute on the canvas context.

```Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently```

Is there a way to enable this attribute?

**To Reproduce**
Load an image on the node.

**Screenshots**
![image](https://user-images.githubusercontent.com/20113585/214335046-2188ed0f-a7f4-4cfe-8ed3-ffc899327673.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 109.0.1518.61 (Official build) (64-bit)

But this occurs on all major browsers too

**Additional context**
A way to enable the attribute and increase graph loading performance when using images as nodes in 2d.
Link for the Canvas2d provided on the warning: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

**Comment by vasturiano** [comment]
@JarnDev thanks for reaching out?

Can you check which version of `force-graph` do you have in your dependency tree?

I'm mentioning this because this has recently been fixed and is present in `v1.42.18` of `force-graph`:
https://github.com/vasturiano/force-graph/commit/30d734e7d1f0c3803abe781259721687dc8da8e0

So you just may need to upgrade things to latest.

**Comment by JarnDev** [comment]
react-force-graph-2d: ^1.23.10

Gonna update the lib and let you guys know, think you for the reply.

**Comment by JarnDev** [comment]
Ok, the react-force-graph-2d (1.23.17) is up to date, and it uses force-graph as a dependency that is on version 1.42.18.

This fixed the warnings!
