### ISSUE TITLE
Can't import 'Box3' from non EcmaScript module

### ISSUE THREAD

**Issue by Magesh2022** [vasturiano/react-force-graph#421]
First of all thanks for creating the package, it really cool.
I'm facing two issue while using this package( "react-force-graph-3d": "^1.21.19")

1. In chrome 3d render of the graph is too slow(tested the same graph in firefox, safari browser it works fine) and in my local dev environment render of the graph is really fast. 3d graph was tested with **1K nodes and 22k links** in all.

2. it was working fine but I got stuck in this error
```
./node_modules/three-forcegraph/dist/three-forcegraph.mjs
Can't import the named export 'Box3' from non EcmaScript module (only default export is available)
```

Code which i used
```
<ForceGraph3D
    width={500}
    height={500}
    showNavInfo={false}
    graphData={{
      "nodes": nodes,
      "links": edges
    }}
    backgroundColor={"#fff"}
    nodeAutoColorBy={"group"}
    linkAutoColorBy={"group"}
    onNodeDragEnd={(node) => {
      node.fx = node.x;
      node.fy = node.y;
      node.fz = node.z;
    }}
    nodeResolution={4}
    linkResolution={1}
    nodeOpacity={0.8}
    linkOpacity={0.2}
    nodeVisibility={this.nodeVisibilityEvent}
    linkVisibility={this.linkVisibilityEvent}
    nodeColor={this.nodeColorEvent}
    linkColor={this.linkColorEvent}
    warmupTicks={100}
    cooldownTicks={0}
 
  />
```

**Comment by vasturiano** [comment]
Could you please make a simple example on https://codesandbox.io that reproduces your issue?

**Comment by Magesh2022** [comment]
In codesandbox its working fine with 1K nodes and 22k links, empty data, plain import.

I did try with plain import and empty data in local, if its a empty data atleast it will show a blank canvas previously.
but importing this raise the exception `./node_modules/three-forcegraph/dist/three-forcegraph.mjs
Can't import the named export 'Box3' from non EcmaScript module (only default export is available)`
```
<ForceGraph3D  />
```
```
<ForceGraph3D
    graphData={{
      "nodes": [],
      "links": []
    }}
/>
```

**Comment by matejsoroka** [comment]
Having same issue here.

**Comment by vasturiano** [comment]
Likely there is something in your build process that is leading to this issue. Are you by chance trying to import the module as a commonJs (ie for use in node) module?

**Comment by sumitwalmiki1** [comment]
Here is an example for your reference, 
https://github.com/sumitwalmiki1/react-force-graph-example

Here are the general steps to follow when setting up a example:

Clone the repository.
Install the necessary dependencies for the backend, such as express or nodemon, using npm install.
Start the application by running npm run dev.
Test the application in your browser to make sure everything is working as expected.
you can check console for logs where you will find the errors.

**Comment by Magesh2022** [comment]
upgrading these to latest version resolves the issue
`react, react-dom, react-scripts`

**Comment by Magesh2022** [comment]
issue resolved by add this to webpack config file
```
{
      test: /\.mjs$/,
      include: /node_modules/,
      type: "javascript/auto"
}
```

https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo
