### ISSUE TITLE
Get size node on click

### ISSUE THREAD

**Issue by jMoulis** [vasturiano/react-force-graph#422]
Hi,
is it possible de get the actuel size of a node onNodeClick event?

Thanks

**Comment by vasturiano** [comment]
@jMoulis the radius of the nodes (in their default representation) is calculated from the `nodeVal` property, and multiplied by the constant `nodeRelSize`. So you can extract it from those settings.

**Comment by jMoulis** [comment]
Ok 👍, and if there is a zoom, do I have to use le globalscale to multiple the result of nodeVal and nodeRelSize?

**Comment by vasturiano** [comment]
Yes, if you're interested to know px distances you can use `graph2ScreenCoords` to translate between domains.

**Comment by PatrickF-mbse** [comment]
Hi

I discovered this great library on GitHub and after checking the demo, I
was wondering if could be possible to mix 2D diagrams and 3 d nodes in the
same viewpoint?

The picture attached show an example of what I would be interested to
reproduce using this library.

I was curious to get your opinion about feasabiility?

Thank you very much
Regards
