### ISSUE TITLE
window add mouse event listener doesn't work on 2d graphs 

### ISSUE THREAD

**Issue by ethanplee14** [vasturiano/react-force-graph#423]
**Describe the bug**

Can't add an event listener to window or document for left mouse events. window.addEventListener("mousedown, listener) it doesn't register for left clicks. This only happens in the 2d force graphs. Right clicks will trigger the event, left clicks won't. This problem only exists in the force-graph container, if i click outside of it, works just fine. 

**To Reproduce**
1. Open any 2d graph 
2. Register event listener "window.addEventListener("mousedown, () => console.log("test"));"
3. Click window, no results.

**Expected behavior**
Expect to be able to add listeners to the window or document 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 109.0.5414.120

**Comment by vasturiano** [comment]
@ethanplee14 thanks for reaching out. This is intentional, the graph canvas had event listeners setup for pointer clicks, so that interaction functionality is available via methods like `onNodeClick`.
Since the graph dom element is "in front" of the window, the events setup on elements behinds shouldn't get triggered. This is common behaviour on UI components.

**Comment by ethanplee14** [comment]
@vasturiano Hmm i guess that's 1 way of thinking of it. Haven't seen a UI component behave like this yet. Usually if i have a ui component that's inside a container i can still target the container and have the child component work as expected. I suspected that it was blocked for interaction functions, but found that graph 3d behaves as what I expected where i can still use the window and document event listeners. But alright i'll work around it thank you.
