### ISSUE TITLE
Import and package only the 2D component

### ISSUE THREAD

**Issue by bbeaumatin** [vasturiano/react-force-graph#44]
Hi,

and thanks for this great package you made available here.

Everything is working well for us but optimization wise, I'd like to know if there is a way to only import the `<ForceGraph2D>` component without having to load and embed in my package the VR and the 3D components and underlying libraries.

For know webpack produces builds with everything and I end up having to load AFrame and Three.js in the browser, even though I don't use them.

Thanks in advance for informations around that matter.

**Comment by vasturiano** [comment]
Hi @bbeaumatin , if you use a build framework that has tree-shaking abilities, you should not be bundling code that is not being imported. I know `rollup` does tree-shaking. I thought `webpack` could do it too?

**Comment by bbeaumatin** [comment]
Hi, thanks to both of you for the answers. @tomazy's first trick worked instantly and was easy to implement. But I will for sure investigate in why webpack tree shaking didn't work in my initial case.
And i'll take a look also into react-kapsule.

Again... great work, really easy to use components. Thank you very much!

**Comment by bbeaumatin** [comment]
@vasturiano **Thanks a lot** for that splitting, in the end the result is close to using `import ForceGraph from 'react-force-graph/src/ForceGraph2D'` but it **saves a lot of time during the** `npm install` since it doesn't need anymore all the dependencies used in the VR and the 3D components. Not something we do everyday on our local dev environments but multiple times a day on our CI pipeline.
