### ISSUE TITLE
Node position

### ISSUE THREAD

**Issue by Jaymeen1712** [vasturiano/react-force-graph#454]
problem : How can I update the label of a node by modifying its associated data when I click on the node?

result: position of node is changing when I am changing the data(label) of the node

expected: node position should not be changed

**Comment by jianglanke** [comment]
Hi there! how to you fix it with fixed position data? thx

**Comment by vasturiano** [comment]
@jianglanke you can set `fx`, `fy` and `fz` attributes in the nodes themselves, like in [this example](https://vasturiano.github.io/react-force-graph/example/fix-dragged-nodes/):
https://github.com/vasturiano/react-force-graph/blob/b775c43dc54101526448f24a5edf33b8d0df661b/example/fix-dragged-nodes/index.html#L23-L25
