### ISSUE TITLE
Why Doesn't 'onNodeClick' Event Trigger When Nodes Are Moving 

### ISSUE THREAD

**Issue by shape1541** [vasturiano/react-force-graph#459]
react-force-graph-2d

In the situation where enableNodeDrag is set to false, the onNodeClick event doesn't work when nodes are moving. It functions correctly when the nodes come to a stop, but during the initial rendering when nodes are gradually spreading out, the click event doesn't seem to work. Is it possible to make it work even while the nodes are in motion, perhaps by triggering it in a manner similar to 'mouseup'?

**Comment by vasturiano** [comment]
@shape1541 thanks for reaching out.

I'm unable to reproduce your issue. Could you make a simple example on https://codesandbox.io/ ?

`onNodeClick` should be triggered regardless of whether node dragging is enabled and/or the nodes are moving. Though it may be difficult interaction wise to actually click on a node while it's in motion.

**Comment by shape1541** [comment]
Thank you for your answer!
