### ISSUE TITLE
Feasibility of Group-Based Color and Position Assignment for Nodes

### ISSUE THREAD

**Issue by shape1541** [vasturiano/react-force-graph#460]
I have a question regarding its capabilities. Is it possible to implement the following feature when displaying data from the react-force-graph2d library: Can we arrange the nodes based on their groupId so that nodes with the same groupId are grouped together? There could be a maximum of three colors, like red, orange, and green, or just two or even one color representing the nodes. The number of nodes with a specific groupId can vary, some groups might have fewer nodes while others have more. Currently, the nodes are appearing automatically without specifying x or y values in the data. Is there a way to address this issue? I would greatly appreciate it if you could provide any guidance on how to solve this problem.
 
![image](https://github.com/vasturiano/react-force-graph/assets/47061189/287a26bf-87f2-4d23-8840-e837687507b7)

```javascript
data:[ 
  {  id: 320 , group:1 }   // TOP
  {  id: 315 , group:1 }  // TOP
  {  id: 318 , group:1 }  // TOP
...

  { id: 308, group: 2 } // RIGHT
...
  { id: 303, group: 3 } // LEFT
  { id: 306, group: 3 } // LEFT
  { id: 307, group: 3 } // LEFT
...
]
```

I used the sort() method to arrange the data by groupId, but it seems like the index values are positioned towards the center of the array, and values towards the end are on the outside. Is it possible to arrange the data by categories rather than having the center as the reference point?

**Comment by shape1541** [comment]
I understand that you are currently exploring the "d3-force-graph" library and the "d3-force-cluster" library and are unsure about how to work with them in a React-based project. You provided an example of your code. Here's the translation of your question into English:

"I am currently trying out the "d3-force-graph" library and the "d3-force-cluster" library and I'm not sure how to work with them in a React-based project. 

```javascript
useEffect(() => {
    forceRef.current
      .d3Force('link')
      .distance((link: NetworkGraphLink) => INITIAL_NODE_RADIUS * 4 + (link.target.id - link.source.id) / 4);
    forceRef.current.d3Force('charge').strength(-200);
}
```

**Comment by vasturiano** [comment]
@shape1541 I would look a little deeper into the repo at [d3-force-cluster](https://github.com/ericsoco/d3-force-cluster) for this. If you have some questions on specifically how to use that force you can ask in that repo directly.

And to plug that in to this module, you would simply do something like:
```js
const myClusterForce = forceCluster();
myForceCluster
  .centers(...)
  .strength(...); // your code

forceRef.current.d3Force('cluster', myForceCluster);
```
