### ISSUE TITLE
Background color rgba(0,0,0,0) shows black background

### ISSUE THREAD

**Issue by sdgandhi** [vasturiano/react-force-graph#47]
# Repro
Add `backgroundColor: "rgba(0,0,0,0)"` to ForceGraph3D props.

# Expectation
Background color is clear

# Result
Background color is black

# Info
```
"react-force-graph-3d": "^1.2.0",

macOS + Chrome
```

**Comment by vasturiano** [comment]
Thanks for the report @sdgandhi. This should now be fixed in the latest version `1.2.2`.

**Comment by sdgandhi** [comment]
Thanks @vasturiano for the quick response!

**Comment by jlangner-hubble** [comment]
Bump - this is broken again.

**Comment by vasturiano** [comment]
@BernardoOlisan can't reproduce. Please provide a simple example on https://codesandbox.io/ .
