### ISSUE TITLE
graphRef.current.cameraPosition undefined

### ISSUE THREAD

**Issue by Javalost** [vasturiano/react-force-graph#491]
Hi , 

I followed the previous issues and solutions to getting passed SSR with nextjs, but on build i'm still in encountering a problem where current.cameraPosition isn't showing up on graphRef or the reference in general. I've effectively wrapped all of my components in their own dynamic wrappers to see if it's the children causing an error in ssr, but it seems it's just the graphRef itself that isn't responding well. Using the wrapper method solved the window undefined error initially, but i still can't seem to get the ForceGraphMethods to respond well. 

I've launched a limited version of my code [here](https://codesandbox.io/p/devbox/epic-violet-6fs5pc) 

Edit : Link repaired

**Comment by vinayteki95** [comment]
@Javalost 
It seems that you've found a solution for this. I am currently facing the same issue with Next.js with respect to `graphRef.current` being null.
It would be of great help if you could explain how you solved this issue. Thanks!
