### ISSUE TITLE
Expanded nodes by default when rendering

### ISSUE THREAD

**Issue by AlbaCrespo** [vasturiano/react-force-graph#496]
Hello!!, :)
 
I'm working on a project where we have integrated the react-force-graph-2d library, we want that when we load the graph on the screen, we can see the nodes expanded

**Current situation:**

![image](https://github.com/vasturiano/react-force-graph/assets/94365864/71b6d34e-b5e8-438c-9107-6758696f27bc)

**Optimal situation**

![image](https://github.com/vasturiano/react-force-graph/assets/94365864/a5486ab2-827c-4156-b205-6498e630e100)

We have read that this may be due to having an onNodeDrag function that alters the behaviour by fixing the nodes, but the idea is that when we move a node, it keeps the position it was left in.

**Our ForceGraph2D component is:**

           
```
           <ForceGraph2D
            graphData={JSON.parse(parseFullGraph(fullGrapData))}
            onNodeDrag={node => {
            node.fx = node.x;
            node.fy = node.y;
            node.fz = node.z
            }}
            nodeLabel="name"
            nodeRelSize={NODE_R}
            cooldownTicks={0}
            ref={fgRef}
            autoPauseRedraw={false}
            nodeCanvasObjectMode={() => 'after'}
            onNodeClick={(node) => handleNodeClick(node)}
            nodeCanvasObject={paintNode}
            linkWidth={3}
            linkColor={() => '#888888'}
            linkDirectionalArrowRelPos={1}
            linkDirectionalArrowLength={8.5}
            linkCanvasObject= {(link, ctx) => {
              const fontSize = 17;
              const label = link.id;
              ctx.beginPath()
              ctx.font = ${fontSize}px Sans-Serif;
              ctx.textAlign = 'center';
              ctx.textBaseline = 'middle';
              ctx.fillStyle = 'black'; //link.color;
              ctx.fillText(label, link.x, link.y);
            }}
            linkCanvasObjectMode={() => 'after'}
            />
```

Do you know how we coould solve this problem?
Thanks in advance!!!

**Comment by vasturiano** [comment]
@AlbaCrespo could you please make a simple reproducing example on https://codesandbox.io/ in order to better understand the issue you're having?

**Comment by AlbaCrespo** [comment]
Hello!,
 
[I leave here the link](https://codesandbox.io/p/sandbox/cold-wildflower-9m964l), in the example you will see that there is a little bug when you click on a node, this is because the graph is rendered and returns to the initial position (all nodes together).

**Comment by vasturiano** [comment]
@AlbaCrespo thanks for the example.

The reason why the graph resets when you click on a node is because whenever the component rerenders you are effectively regenerating and passing a new data object. That's happening in this line:
```js
      graphData={JSON.parse(parseFullGraph(fullGrapData))}
```

If you don't want a new data object to be passed every time, you should parse the data only once on component mount and then memoize it.

**Comment by AlbaCrespo** [comment]
Many tanks for the reply @vasturiano !  That was really useful, I've managed to solve my problem. 

Thanks again, :)
