### ISSUE TITLE
"Highlights" example not working for me

### ISSUE THREAD

**Issue by TechDom** [vasturiano/react-force-graph#498]
Hi,

the library is great!
But I can not seem to get the [Highlight](https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html) example working and would love some help with it :)

What I intend:
- Highlight nodes upon hovering (e.g. by drawing a circle around them).

What I've done so far:
- Strictly followed the above example

What's wrong:
- When hovering nodes, nothing happens (also no errors).

Ideas:
- I do get the output "Hovering ..." from console output (line 10) of handleNodeHover(), so that function is called properly.
- I do get the right node logged to console (line 33, 34) after it has been set within handleNodeHover() (line 19).
- I am not sure how the paintRing() function is called, but it never outputs anything to console (line 24).

Below is my code. I left all my properties of <ForceGraph3D /> for you to see in case there might any conflicting ones.
`

    const [highlightNodes, setHighlightNodes] = useState(new Set());
    const [hoverNode, setHoverNode] = useState(null);
    const NODE_R = nodeRelSize;

    const updateHighlight = () => {
        setHighlightNodes(highlightNodes);
    };

    const handleNodeHover = node => {
        console.log("Hovering ...")
        /highlightNodes.clear();
        // Shouldn't the above be setHighlightNodes(new Set());?
        if (node) {
            highlightNodes.add(node);
            // Shoudln't the above be setHighlightNodes([...highlightNodes, node]);?
        }

        // setHoverNode(node);
        setHoverNode(node || null);
        updateHighlight();
    };

    const paintRing = useCallback((node, ctx) => {
        console.log("Painting ...")
        // add ring just for highlighted nodes
        ctx.beginPath();
        ctx.arc(node.x, node.y, NODE_R * 1.4, 0, 2 * Math.PI, false);
        ctx.fillStyle = node === hoverNode ? 'red' : 'orange';
        ctx.fill();
    }, [hoverNode]);

    useEffect(() => {
        console.log("Hover node has changed: ")
        console.log(hoverNode)
    }, [hoverNode])

   
    return (
        <div>
            <div className="reactCanvas">
                <ForceGraph3D
                    ref={fgRef}
                    graphData={graphData}
                    width={width}
                    height={height}
                    nodeLabel={nodelabel}
                    backgroundColor={backgroundColor}
                    id={id}
                    nodeResolution={nodeResolution}
                    onNodeClick={node => onNodeLeftClick(node)}
                    onNodeRightClick={node => onNodeRightClick(node)}
                    onLinkClick={link => onLinkLeftClick(link)}
                    onLinkRightClick={link => onLinkRightClick(link)}
                    onLinkHover={link => onItemHover(link)}
                    nodeThreeObject={node => nodeObjectFunction(node)}
                    nodeThreeObjectExtend={isNodeExtended}
                    nodeRelSize={nodeRelSize}
                    linkWidth={linkWidth}
                    linkResolution={linkResolution}
                    linkOpacity={0.5}
                    dagMode={getDagMode(dagMode)} // radialin
                    dagLevelDistance={nodeDistance}
                    forceEngine="d3" // d3
                    onNodeDragEnd={node => {
                        node.fx = node.x;
                        node.fy = node.y;
                        node.fz = node.z;
                    }}
                    cooldownTime={900}
                    onNodeHover={handleNodeHover}
                    nodeCanvasObjectMode={node => highlightNodes.has(node) ? 'before' : undefined}
                    nodeCanvasObject={paintRing}
                />
            </div>
        </div>
    )`

**Comment by vasturiano** [comment]
@TechDom thanks for reaching out. Could you please create a simple example on https://codesandbox.io/ ?

**Comment by TechDom** [comment]
Hey @vasturiano, thanks for taking a look at it!
I created a simple sandbox here: [https://7dzzzq.csb.app/](https://7dzzzq.csb.app/) by more or less copying the "Highlights example", except I commented out all code related to highlighting links, as I only need nodes to be highlighted for now. The code shows the same unexpected behaviour described above.

Thank you very much!
Dominik

**Comment by vasturiano** [comment]
@TechDom the `nodeCanvasObject` method is not available in the 3D version of the component. That's a 2D only feature.

In 3D the closest thing you have is `nodeThreeObject`.

https://github.com/vasturiano/react-force-graph?tab=readme-ov-file#node-styling

**Comment by TechDom** [comment]
Thanks! I didn't realize that your example is using a 2D graph.

Returning differently styled objects for `nodeThreeObject` indeed works for me now, I can work with that. Thanks for your quick support.
