### ISSUE TITLE
How to draw curved lines between nodes

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#504]
**Describe the bug**
Hey! How to draw curved lines between nodes

**To Reproduce**
Render graph

**Expected behavior**
Render graph with curved lines

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Comment by Franbr31** [comment]
Hi!,
In this [example](https://github.com/vasturiano/react-force-graph/blob/master/example/curved-links/index.html) you can see how it uses curved edges, at the end it uses the property 
linkCurvature="curvature".
```
<ForceGraphVR
        graphData={gData}
        linkCurvature="curvature"
        linkCurveRotation="rotation"
        linkDirectionalParticles={2}
      />
```

**Comment by MaksZhukov** [comment]
@Franbr31 Thanks!
