### ISSUE TITLE
Any ideas how to implement curved connections as on screenshoot

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#505]
**Describe the bug**
Any ideas how to implement curved connections as on screenshoot

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img width="422" alt="image" src="https://github.com/vasturiano/react-force-graph/assets/23615115/524dadab-0dff-4baa-95d5-e7564e04a1ae">

**Comment by vasturiano** [comment]
@MaksZhukov thanks for reaching out.

Assuming you're using the 2D mode, you'd need to write the drawing implementation on `.linkCanvasObject(link => /* your code */), so that the lines are drawn the way you intend, using Canvas commands.

**Comment by MaksZhukov** [comment]
@vasturiano Thanks!
