### ISSUE TITLE
How to have coordinates of real positions of nodes according to the window when zoom in on hover

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#508]
**Describe the bug**
How to have coordinates of real positions of nodes according to the window when zoom in on hover

**To Reproduce**
When I have zoom 1 then the position is ok
When I have zoom 1.149, the position is moved to right

**Expected behavior**
I want to have the additional position value to have real coordinates using zooming

**Screenshots**
![image](https://github.com/vasturiano/react-force-graph/assets/23615115/dc656a11-8a96-4895-9e95-b4e6aec2b2d0)
![image](https://github.com/vasturiano/react-force-graph/assets/23615115/cae3b89e-5386-4e1b-b7ce-0056bfb0d23d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
onZoom

  refCameraPositions.current.x = transform.x;
  refCameraPositions.current.y = transform.y;

onNodeHover

  setPopoverData({
      x: width / 2 + node.x - refCameraPositions.current.x,
      y:
          height / 2 +
          node.y - refCameraPositions.current.y
      name: node.name
  });

**Comment by vasturiano** [comment]
@MaksZhukov you have the utility method [graph2ScreenCoords](https://github.com/vasturiano/react-force-graph?tab=readme-ov-file#utility).

**Comment by MaksZhukov** [comment]
@vasturiano Thanks!
