### ISSUE TITLE
Link directional particle on-demand emission

### ISSUE THREAD

**Issue by sdgandhi** [vasturiano/react-force-graph#51]
Feature request:

Would be awesome to have a function to emit particles on-demand.

```
this.graph.emitDirectionalParticle(linkId)
// or
this.graph.emitDirectionalParticle(linkSrc, linkDest)
```

**Comment by sdgandhi** [comment]
no?

**Comment by vasturiano** [comment]
@sdgandhi that functionality is already supported, via the method `.emitParticle(link)`.
See example: https://vasturiano.github.io/react-force-graph/example/emit-particles/
