### ISSUE TITLE
Graph reloading when hovering the menu

### ISSUE THREAD

**Issue by uhessbai** [vasturiano/react-force-graph#518]
Hello ! 

I have an issue with a context menu which is coloring a node when hovering the linked part of the menu, therefore when i'm hovering a part of the menu, the graph is completely refreshing, which creates bumps 

Here is an example : 

![Animation](https://github.com/vasturiano/react-force-graph/assets/12765043/97b7b74f-b83a-47cd-9b50-557b6b62da91)

The app is containing the drawer and the graph : 

```JSX
export function App() {

  const [nodes, setNodes] = useState([]);
  const [links, setLinks] = useState([]);
  const [dataNodes, setDataNodes] = useState([]);
  const [menuItemHovered, setMenuItemHovered] = useState(null);

  useEffect(() => {
    fetch('../d3-dependencies.csv')
    .then(r => r.text())
    .then(d3.csvParse)
    .then(data => {
      setDataNodes(data);
      const n = [], links = [];
      data.forEach(({ size, path }) => {
        const levels = path.split('/'),
          level = levels.length - 1,
          module = level > 0 ? levels[1] : null,
          leaf = levels.pop(),
          parent = levels.join('/');
        const node = {
          path,
          leaf,
          module,
          size: +size || 20,
          level
        };
        n.push(node);
        if (parent) {
          links.push({source: parent, target: path, targetNode: node});
        }
    });
    setNodes(n);
    setLinks(links);
}) 
}, []);

const onMenuItemHover = (pathHovered) => {
  console.log({pathHovered});
  setMenuItemHovered(pathHovered);
}
  if(nodes.length === 0  || links.length === 0){
    return <p>loading</p>
  }
  return (
    <div className="App">
        <Drawer onHover={onMenuItemHover} data={dataNodes}></Drawer>
        <div id="3d-graph"></div>
        <ForceTree 
          nodeHoveredFromMenu={menuItemHovered}
          data={{nodes, links}}
        />
    </div>
  )
}
```

My drawer looks like this : 

```JSX
export default function PermanentDrawerLeft({data, onHover}) {
   
  return (
      <Drawer
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          '& .MuiDrawer-paper': {
            width: drawerWidth,
            boxSizing: 'border-box',
          },
        }}
        variant="permanent"
        anchor="left"
      >
        <Toolbar />
        <Divider />
        <List>
          {data.filter(item => item.path.split('/').length === 2).map(({size, path}) => (
            <ListItem key={path} disablePadding onMouseEnter={() => onHover(path)}>
              <ListItemButton>
                <ListItemIcon>
                    <InboxIcon />
                </ListItemIcon>
                <ListItemText primary={path} />
              </ListItemButton>
            </ListItem>
          ))}
        </List>
        <Divider />
    
      </Drawer>
  );
}
```

And here is the graph with its interactions : 

```JSX
// highlight 
const highlightNodes = new Set();
let hoverNode = null;

// colors
let lastFolder ='';
let colorIndex = 0;
const colors = [
  'rgba(171, 34, 34, 1)',
  'rgba(255, 208, 0, 1)',
  'rgba(30, 184, 97, 1)',
  'rgba(45, 151, 189, 1)',
  'rgba(116, 124, 165, 1)',
  // 'rgba(186, 97, 140, 1)',
  // 'rgba(160, 42, 184, 1)',
  'rgba(40, 19, 176, 1)',
  'rgba(234, 249, 217, 1)',
  'rgba(226, 212, 186, 1)',

]
const groupNodes = {}

// update render
const useForceUpdate = () => {
  const setToggle = useState(false)[1];
  return () => setToggle(b => !b);
};

// --- GRAPH ---  
export const ForceTree = ({ data, nodeHoveredFromMenu = null }) => {
  
  const fgRef = useRef();

  // --- resize
  const [displayWidth, setDisplayWidth] = useState(window.innerWidth);
  const [displayHeight, setDisplayHeight] = useState(window.innerHeight);
  window.addEventListener('resize', () => {
    setDisplayWidth(window.innerWidth - 240);
    setDisplayHeight(window.innerHeight);
  });

  // --- controls
  const [controls] = useState({ 'DAG Orientation': null});

  // --- update render
  const forceUpdate = useForceUpdate();
 
  // --- modal
  const [open, setOpen] = useState(false);
  
  const handleOpen = (node) => { 
    fgRef.node = node.leaf;
    setOpen(true);
  };
  const handleClose = () => setOpen(false);

  // --- hover highlight
  const [highlightNodes, setHighlightNodes] = useState(new Set());
  const [hoverNode, setHoverNode] = useState(null);


useEffect(() => {
  console.log({nodeHoveredFromMenu})
  const hoveredNode = data.nodes.find(n => n.path === nodeHoveredFromMenu);
  console.log({hoveredNode});
  handleNodeHover(hoveredNode);
}, [nodeHoveredFromMenu])

const updateHighlight = () => {
  setHighlightNodes(highlightNodes);
};

const handleNodeHover = node => {
  console.log(node);
  highlightNodes.clear();
  highlightNodes.add(node);
  setHoverNode(node || null);
  updateHighlight();
};

const handleResize = (node) => {
  //const size = highlightNodes.has(node) ? node === hoverNode ? 4 : 2 : null;
  return 4;
}

// --- Colors
  const handleColors = (node) => {
    const color = highlightNodes.has(node) ? node === hoverNode ? 'rgb(255,0,0,1)' : 'rgba(255,160,0,0.8)' : null
    if (color === null) {
     // handling drawing color
     const path = node.path.split('/');
     const folderOfFile = path[path.length -2];
     if (groupNodes.hasOwnProperty(folderOfFile)) {
        return groupNodes[folderOfFile]
     } else {
        groupNodes[folderOfFile] = colors[colorIndex];
        colorIndex++;
        if (colorIndex >= colors.length -1) {
          colorIndex = 0;
          }
      }
      lastFolder = node.path.split('/').splice(-2);
     return colors[colorIndex];
    }
    return color;
  };

  // DEV MODE : render doublé à cause du strictMode

  useEffect(() => {
    // add collision force
    fgRef.current.d3Force('collision', d3.forceCollide(node => Math.sqrt(100 / (node.level + 1))));
  }, []);
  
console.log(ForceGraph3D);

  const forceGraph =   <ForceGraph3D
    width={displayWidth}
    height={displayHeight}
    ref={fgRef}
    graphData={data}
   // dagMode={controls['DAG Orientation']}
    dagLevelDistance={300}
    backgroundColor="#101020"
    linkColor={() => 'rgba(255,255,255,0.2)'}
    nodeRelSize={2} // resize on hover : change parameter of nodeRelsize in package to wait for a function instead of number (and then make a callback checking if node is hovered)
    nodeId="path"
    nodeVal={node => 100 / (node.level * node.level + 1)}
    nodeLabel="path"
   // nodeAutoColorBy="module"
    linkDirectionalParticles={0} 
    linkDirectionalParticleWidth={0}
    nodeColor={handleColors}
    d3VelocityDecay={0.3}
    enableNodeDrag={false}
    onNodeClick={node => handleOpen(node)}
    onNodeHover={handleNodeHover}
    />

  return (
  <div className="graph-container">
      <Modal
    open={open}
    onClose={handleClose}
    aria-labelledby="modal-modal-title"
    aria-describedby="modal-modal-description"
  >
    <Box sx={style}>
      <Typography id="modal-modal-title" variant="h6" component="h2">
      {fgRef.node}
      </Typography>
      <Typography id="modal-modal-description" sx={{ mt: 2 }}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, dolor minus! Culpa omnis suscipit facere corporis veritatis modi. Ad blanditiis deserunt tempora labore cum dolores accusamus. Dolores minima autem natus!
      </Typography>
    </Box>
  </Modal>
  {forceGraph}
    </div>);
};
```

Could you help me ? 

I hope this code is not too long, let me know if you prefer getting the repository or if the question is not appropriate

Thanks for reading, have a good day !

**Comment by vasturiano** [comment]
@uhessbai thanks for reaching out. It's more practical if you submit an online example on https://codesandbox.io/. However in your case most likely this is happening because you're not memoizing the functions that you're passing to the component, for instance:
```js
nodeVal={node => 100 / (node.level * node.level + 1)}
```

Therefore at every rerender the component receives a new function and needs to recompute every node position and re-heat the layout.

Same thing might be true with your `data` prop if it's a new reference each time (that part of the code is not present above).

**Comment by uhessbai** [comment]
@vasturiano thanks for your reply ! I will come back in a few days at home, I will try that soon :)

**Comment by uhessbai** [comment]
Ok so i tried some things, for nodeVal i can use a static value which works ! As adviced i also put the code on codesanbox (config is not on point tho) at [this link ](https://codesandbox.io/p/github/uhessbai/celmalium-codesandbox/dev?workspaceId=1e0d18ab-c022-4d49-8842-a422da0295eb&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxms59z50007356kn7v4gynd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxms59z50003356kj7l79bw0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxms59z50005356kh1q2pupw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxms59z50006356km1sl6y2y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxms59z50003356kj7l79bw0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxms59z40002356koolsli7v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxms59z50003356kj7l79bw0%2522%252C%2522activeTabId%2522%253A%2522clxms59z40002356koolsli7v%2522%257D%252C%2522clxms59z50006356km1sl6y2y%2522%253A%257B%2522id%2522%253A%2522clxms59z50006356km1sl6y2y%2522%252C%2522activeTabId%2522%253A%2522clxmtdgoj002m356luau6peyx%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clxmtdgoj002m356luau6peyx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxms59z50005356kh1q2pupw%2522%253A%257B%2522id%2522%253A%2522clxms59z50005356kh1q2pupw%2522%252C%2522activeTabId%2522%253A%2522clxms59z50004356k29k07uil%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxms59z50004356k29k07uil%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxms5aer000qdjgcc75l4o8x%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clxms5vbx008v356kf4iboxzg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxms5w2400ax356kb56iu3gg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A18.4375%257D)

But for  "data" its another kind of issue : my problem is that my app component hosts the drawer and the forcetree, and the info goes from one component to the other to help the highlight of nodes and i dont know if i there is a way to solve this issue, i tried by myself and with the help of ai but my knowledge of react seems not clear enough because even though i tried multiple things i was going around in circles

Could you bring more details about your clue on this issue ? 

Also our answer greatly helped me to better understand how the layout works, thanks for that too !

**Comment by vasturiano** [comment]
@uhessbai essentially you should try to keep your `data` object memoized, i.e. its reference doesn't change from one render to the next. This is regardless of whether it belongs to the force graph component or its parent component. At the time that it is created it should not be regenerated at every render, unless needed.

**Comment by itsPreto** [comment]
Wow this thread was super helpful! I was struggling with an issue when highlighting linked nodes in a large graph where my fps would drop to 1 while hovering and it turned out these types to memoize the `graphData` and now it runs super smoothly!

@vasturiano if interested I can put up a PR for a large-graph/highlighting/performance example

**Comment by uhessbai** [comment]
@vasturiano  it works perfectly!  thanks for your help! I can post the code if someone needs it

**Comment by FrancicoVerdu** [comment]
> Wow this thread was super helpful! I was struggling with an issue when highlighting linked nodes in a large graph where my fps would drop to 1 while hovering and it turned out these types to memoize the `graphData` and now it runs super smoothly!
> 
> @vasturiano if interested I can put up a PR for a large-graph/highlighting/performance example

I'm really interested in what you mentioned because I'm having issues with highlighting nodes as well. In my project, the nodes contain very heavy 3D objects, and updating the hoverNode is triggering the nodeThreeObject, which is impacting performance

**Comment by uhessbai** [comment]
@FrancicoVerdu sure ! here is the code, i asked to a llm to extract the interesting part (memoizeddata and highlight) 

```
import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import * as d3 from 'd3';

export function DataProcessingAndHoverLogic({ children }) {
  const [dataNodes, setDataNodes] = useState([]);
  const [menuItemHovered, setMenuItemHovered] = useState(null);
  const forceTreeRef = useRef(null);

  useEffect(() => {
    fetch('../d3-dependencies.csv')
      .then(r => r.text())
      .then(d3.csvParse)
      .then(setDataNodes)
      .catch(error => console.error('Error fetching data:', error));
  }, []);

  const { nodes, links } = useMemo(() => {
    const n = [], links = [];
    dataNodes.forEach(({ size, path }) => {
      const levels = path.split('/'),
        level = levels.length - 1,
        module = level > 0 ? levels[1] : null,
        leaf = levels.pop(),
        parent = levels.join('/');
      const node = {
        path,
        leaf,
        module,
        size: +size || 20,
        level
      };
      n.push(node);
      if (parent) {
        links.push({ source: parent, target: path, targetNode: node });
      }
    });
    return { nodes: n, links };
  }, [dataNodes]);

  const memoizedData = useMemo(() => ({ nodes, links }), [nodes, links]);

  const onMenuItemHover = useCallback((pathHovered) => {
    setMenuItemHovered(pathHovered);
    if (forceTreeRef.current?.updateHoveredNode) {
      forceTreeRef.current.updateHoveredNode(pathHovered);
    }
  }, []);

  useEffect(() => {
    if (forceTreeRef.current?.updateHoveredNode) {
      forceTreeRef.current.updateHoveredNode(menuItemHovered);
    }
  }, [menuItemHovered]);

  return children({ 
    onMenuItemHover, 
    forceTreeRef, 
    memoizedData, 
    dataNodes, 
    isLoading: nodes.length === 0 || links.length === 0 
  });
}

// Usage example:
function App() {
  return (
    <DataProcessingAndHoverLogic>
      {({ onMenuItemHover, forceTreeRef, memoizedData, dataNodes, isLoading }) => (
        <div className="App">
          {isLoading ? (
            <p>Loading...</p>
          ) : (
            <>
              <Drawer onHover={onMenuItemHover} data={dataNodes} />
              <div id="3d-graph"></div>
              <ForceTree ref={forceTreeRef} data={memoizedData} />
            </>
          )}
        </div>
      )}
    </DataProcessingAndHoverLogic>
  );
}
```
