### ISSUE TITLE
Node shape as SVG image?

### ISSUE THREAD

**Issue by zvolchak** [vasturiano/react-force-graph#52]
Hello,

 I see there is an option to use custom shapes for nodes.. Is it possible to use that approach to set an SVG image for different nodes? Or maybe there is a different node to do so... something like

```
    "nodes": [ 
        { 
          "id": "id1",
          "name": "name1",
          "val": 1 ,
          "icon": svg_object_here // <----- is something like that possible?
        },
....
```
Thanks!

**Comment by vasturiano** [comment]
@zvolchak you should be able to include images, either using `nodeThreeObject` (for 3D graphs) or `nodeCanvasObject` (for 2D). But you'll have to either use a `sprite` to build a three.js node (3D), or paint the image to a canvas object (2D).

**Comment by zvolchak** [comment]
Got it!

Thanks.
