### ISSUE TITLE
node position

### ISSUE THREAD

**Issue by SukPavel** [vasturiano/react-force-graph#54]
Hi, is it possible to preserve position of nodes after state change and re-rendering? E.g. I have node label and I need to change label color or prefix without animating or starting from default layout position. I¨ve tried to inject old x and y coordinates into "data" but it is ignored. 
Thank you.

**Comment by vasturiano** [comment]
@SukPavel just changing the `nodeLabel` prop on re-render should not cause a re-initialization of the graph. Here's an example in which changes various component props (like `linkWidth`) dynamically:
https://vasturiano.github.io/react-force-graph/example/highlight/
[(source)](https://github.com/vasturiano/react-force-graph/blob/master/example/highlight/index.html)

Just make sure that the `graphData` that you pass as prop is the same instance across multiple re-renders of the component.
