### ISSUE TITLE
Unable to capture the mouse left click event on the canvas

### ISSUE THREAD

**Issue by Manojkumar226** [vasturiano/react-force-graph#541]
**Problem**
I am unable to catch the left click mouse event using window or document event listeners (e.g., window.addEventListener("mousedown, listener").This only occurs in 2D force graphs; left clicks do not activate or initiate the event, but right clicks do. 

**UseCase:**
Im trying to change the mouse pointer(cursor) styles to `grabbing`  on canvas when user tries to click the left mouse click and drag(moving) the canvas. 

@vasturiano  Is there any way to acheive my use-case mentioned above in the ForceGraph2D? 
 
I see the similar use case in earlier issues but couldn't find the solution with ForceGraph2D #423

**Comment by vasturiano** [comment]
@Manojkumar226 thanks for reaching out.

Have you tried with the `"pointerdown"` event type instead?

**Comment by Manojkumar226** [comment]
> pointerdown

Thank you @vasturiano. The pointerdown event is satisfying my use-case.
