### ISSUE TITLE
Using "click-to-focus" example inside react component causing infinite re-renders

### ISSUE THREAD

**Issue by baaraakaa** [vasturiano/react-force-graph#548]
**Describe the bug**
I'm trying to use the code from the [click-to-focus example](https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html) in a React component. As soon as I add the `ref={fgRef}` to `ForceGraph3D` I get infinite re-renders. Feels like I'm missing something simple, but i've spent a few hrs researching how refs work in react to no avail. would appreciate any help.

**Code**
````jsx
"use client"

import { ForceGraph3D } from "react-force-graph";
import { useCallback, useRef } from "react";
import { ForceGraphMethods } from 'react-force-graph-3d'

type gProps = {
  gData: {
    nodes: {}[],
    links: {}[]
  }
}

export default function Graph({ gData }: gProps) {
  const FocusGraph = () => {
    const fgRef = useRef<ForceGraphMethods>()
    //@ts-expect-error
    const handleClick = useCallback((node) => {
      if (fgRef.current === undefined) return;
      const distance = 60
      const distRatio = 1 + distance / Math.hypot(node.x, node.y, node.z)
      fgRef.current.cameraPosition(
        { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
        node, // lookAt ({ x, y, z })
        2000  // ms transition duration
      );
    }, [fgRef])

    return <ForceGraph3D
      nodeLabel="name"
      graphData={gData}
      onNodeClick={handleClick}
      ref={fgRef}
    />
  }

  return <FocusGraph />
}
````

**Screenshots**
![react dev tool](https://github.com/user-attachments/assets/23113338-4644-411c-9895-19f7dd057480)
![react dev tool](https://github.com/user-attachments/assets/2fc3cacc-9391-4ff3-a02b-858e048d0b37)

**Comment by vasturiano** [comment]
@baaraakaa tanks for reaching out.

Would you mind making a simple example like this one on https://codesandbox.io/? It's easier to troubleshoot that way instead of looking at the raw code.

**Comment by baaraakaa** [comment]
@vasturiano thank you for the quick reply, i spent quite a while today struggling to get a codesandbox to work, but in the process i realised that my issue seems to be specific to next.js 15, and I managed to resolve it for now by reverting to next.js 14.

I think i will mark this issue as closed, thanks for your work on this great tool.
