### ISSUE TITLE
Hover tooltip distorted when displaying graph on monitor

### ISSUE THREAD

**Issue by witang** [vasturiano/react-force-graph#55]
I apologize in advance if this issue has already been addressed elsewhere, and I've just missed it. 

When rendering a graph on my laptop monitor, the tooltip data label displayed when hovering over a node works perfectly. However, when I render the same graph on an external (curved) monitor, hovering directly over the node no longer brings up the tooltip. I need to move my cursor a couple dozen pixels to the left of the node I want to hover over, or zoom in extremely close to the node in question. 

I've attached a photo example below, where "Fauchelevent" is the name of the light blue node to the far right of the tooltip. Although you can't see it, my cursor is hovering out in open whitespace right above the tooltip. 

![screen shot 2018-11-19 at 11 29 59 am](https://user-images.githubusercontent.com/35241613/48730221-891e2c80-ebee-11e8-997c-a55389cd6c56.png)

Would you happen to have any idea as to why this is taking place? Much of the functionality for what I'm trying to do relies on being able to click and drag individual nodes easily. 

Thanks.

**Comment by vasturiano** [comment]
@witang I haven't seen this particular case. Does it happen with any external monitor, or only with a specific one? Is it the same exact application in both cases?
And have you noticed a similar issue in any other application, like this example: https://bl.ocks.org/mbostock/1087001

**Comment by witang** [comment]
Hi @vasturiano,
Sorry for the delayed reply. For some reason I didn't get a Github notification that you'd replied and then I left for the holidays. 

I only have one external monitor, so I haven't actually had the chance to try this on others. It is the same application in both cases though. The issue seems to persist regardless of what kind of graph I render on my curved monitor. 

The Mike Bostock example you attached works fine on both my laptop and my external monitor.

**Comment by witang** [comment]
Hi @vasturiano
Thanks again for looking into this. I just wanted to follow-up and let you know that I tested the same graph on another external monitor (not curved), and the same issue occurred. 

It's proving to make the graphs rather difficult to work with for a number of our internal users, so we would definitely appreciate any insight you have regarding this. 

Thanks.

**Comment by vasturiano** [comment]
@witang are you seeing that happening with this example? https://vasturiano.github.io/react-force-graph/example/directional-links-particles/

And can you tell me a bit about your environment, browser type/version, OS, etc?

**Comment by witang** [comment]
@vasturiano No, that example seems to work fine. I'm currently working on MacOS Sierra (10.12.6) and the latest version of Chrome. 

However, after digging further I've realized that this distortion only occurs when I've manually set the "width" and "height" props. When I remove these and allow them to default to the window width and height, dragging and hovering works normally.

**Comment by vasturiano** [comment]
@witang could you post an example online (for example on https://codepen.io/) highlighting the issue so that it's easier to troubleshoot?
