### ISSUE TITLE
ForceGraph3D Nodes Missing

### ISSUE THREAD

**Issue by wadehenning** [vasturiano/react-force-graph#56]
Hi @vasturiano ,

The links for this graph based on your example are showing up correctly, but the nodes are not being plotted.  Can you see anything obvious here that I am missing?  Thank you.

```

export default class FocusGraph extends React.Component {
    render() {
        //const data = this.props.data;
        const data = miserables;
        return <ForceGraph3D            
            graphData={data}
            nodeThreeObject={({ id }) => new THREE.Mesh(
                [
                    new THREE.BoxGeometry(Math.random() * 20, Math.random() * 20, Math.random() * 20),
                    new THREE.ConeGeometry(Math.random() * 10, Math.random() * 20),
                    new THREE.CylinderGeometry(Math.random() * 10, Math.random() * 10, Math.random() * 20),
                    new THREE.DodecahedronGeometry(Math.random() * 10),
                    new THREE.SphereGeometry(Math.random() * 10),
                    new THREE.TorusGeometry(Math.random() * 10, Math.random() * 2),
                    new THREE.TorusKnotGeometry(Math.random() * 10, Math.random() * 2)
                ][id%7],
                new THREE.MeshLambertMaterial({
                    color: Math.round(Math.random() * Math.pow(2, 24)),
                    transparent: true,
                    opacity: 0.75
                })
            )}       
            
        />;
    }
}

```

**Comment by vasturiano** [comment]
Are you importing `THREE` into the page?

**Comment by wadehenning** [comment]
I ```import * as THREE from 'three';``` at the top...

**Comment by vasturiano** [comment]
Ah yes, that example is using the numeric `id` to cycle through the various meshes (`id%7`). On the miserables, the `id` is a string so it won't. You should have a different method for doing that. You could use the `group` field, but it all depends on what the intention is. :)

**Comment by dj-neza** [comment]
Hi! I tried to do a similar thing and the nodes won't work. This is my code and I also have the proper import of three:

`<ForceGraph3D 
        ref={this.fgRef}
        graphData={network} 
        nodeLabel="name" 
        nodeThreeObject={(node) => {
          const imgTexture = new THREE.TextureLoader().load(`./images/${node.image}`);
          const material = new THREE.SpriteMaterial({ map: imgTexture });
          const sprite = new THREE.Sprite(material);
          sprite.scale.set(20, 20);
          return sprite;
        }}
      />`

I continuously get an error in the Browser **TypeError: Cannot read property 'matrixWorld of undefined** Which apparently relates to sprites. Is it possible this is not the right way of doing it anymore?

**Comment by dj-neza** [comment]
I apologise for terrible formatting of the code here...

**Comment by vasturiano** [comment]
@dj-neza it's quite likely that the issue resides elsewhere than the code snippet you included. Could you do a minimal replicating example on https://codesandbox.io/ ?

**Comment by dj-neza** [comment]
@vasturiano Yeah I'll try!

**Comment by dj-neza** [comment]
Hmm never tried to put React code into Codesandbox, is there a good way to do it when you have quite large projects?

**Comment by vasturiano** [comment]
Codesandbox does have a React scaffold mode. Ideally you want to just do a minimal example that focuses on the issue you're seeing.

**Comment by dj-neza** [comment]
The issue is I'm not completely sure if I'm importing everything the right way into React so actually it might be React causing this.. I added the import from here:

> I `import * as THREE from 'three';` at the top...
> 
> ... but you are exactly right; I had forgotten that in the past I solved this by `var THREE = require('three');`
> I made the change, but, unfortunately, this time still no nodes. I can see THREE is there.

but the var part doesn't seem to affect it at all..

**Comment by dj-neza** [comment]
https://codesandbox.io/s/infallible-banach-5kb8w

**Comment by dj-neza** [comment]
This is the errors I'm getting and if you look closely you can see that the links are showing just without the nodes.

**Comment by vasturiano** [comment]
@dj-neza thanks for creating the example.

The nodes are missing mostly because the img files are not included in the project.

About the errors, you can fix them by importing from the 3d module specifically, instead of the full bundle. 
So
```
import ForceGraph3D from "react-force-graph-3d";
```
instead of
```
import { ForceGraph3D } from "react-force-graph";
```

It's also recommended to upgrade to the latest versions of the packages. You'll also need to update React to a version that supports hooks `>=16.8.0.`

**Comment by dj-neza** [comment]
Hi! 
Thanks for the swift answer!
I added the img files in folder images in the Sandbox so they should be there or actually it's only one for now but it's the one that I linked in my network.json.

**Comment by dj-neza** [comment]
So the lack of images shouldn't be a problem but codesandbox might not show it to you because I had to login to be able to add them - try creating images foulder within src and add a image sample there and link it to the nodes.

**Comment by dj-neza** [comment]
@vasturiano  Thanks I managed to load the images, however, on hover they start to flicker and dissappear even after applying  
  ```
 nodeThreeObjectExtend={true}
 nodeOpacity={0}
```

**Comment by vasturiano** [comment]
If you're doing images as nodes you probably want to do `nodeThreeObjectExtend={false}`, other wise you'll have overlapping objects.

**Comment by dj-neza** [comment]
Yeah, thanks for all the help. :) If you manage to figure out the flicker let me know!

**Comment by sharp211** [comment]
Hi @vasturiano  :),

I mapped an icon to a node using CSS2DRenderer, CSS2DObject.
But the nodes are invisible on zooming the graph.
Could u please let me know what the problem is?

<ForceGraph3D
    graphData={data}
    extraRenderers={[new CSS2DRenderer()]}
    nodeThreeObject={node => {
        const nodeEl = document.createElement('i');
        nodeEl.className = icons[node.group];
        nodeEl.style.color = "#ccc";
        nodeEl.style.fontSize = "13px";
        return new CSS2DObject(nodeEl);
    }}
/>

**Comment by vasturiano** [comment]
@sharp211 from your code snippet it seems you are not setting any content on the the nodes, only styling. But to be sure better create an example on https://codesandbox.io.

**Comment by sharp211** [comment]
It's not my full content.
I'm adding the others here.

<ForceGraph3D
                            nodeRelSize={NODE_R}
                            ref={fgRef}
                            graphData={data}
                            nodeOpacity={1}
                            extraRenderers={[new CSS3DRenderer()]}
                            autoPauseRedraw={false}
                            nodeThreeObject={node => {
                                const nodeEl = document.createElement('i');
                                nodeEl.className = icons[node.group];
                                nodeEl.style.color = "#ccc";
                                nodeEl.style.fontSize = "13px";
                                return new CSS3DObject(nodeEl);
                            }}

                            nodeThreeObjectExtend={true}

                            linkOpacity={.8}
                            linkDirectionalParticles={4}
                            linkDirectionalParticleWidth={node => highlightNode === node ? 4 : 2}
                            linkWidth={link => highlightLinks.includes(link) ? 2 : 1}
                            linkColor={link => highlightLinks.indexOf(item => item === link.target || item === link.source) > -1 ? "#456cc8" : link.color}
                            onNodeClick={handleNodeClick}
                            nodeCanvasObjectMode={node => highlightNode === node ? 'before' : undefined}
                            nodeColor={node => highlightNode === node ? "#c3e6e7" : "#0a525d"}
                        />
