### ISSUE TITLE
Always show label or disable showing label when hovering over node

### ISSUE THREAD

**Issue by phamcong** [vasturiano/react-force-graph#57]
Hello,

I would like to always display the label of node not only hovering on the node. How could I do that?
If not, how can I disable the showing label when hovering over node?

Thank you in advance.

**Comment by vasturiano** [comment]
@phamcong to build text into the nodes themselves, so that they're always showing, please refer to this example: https://vasturiano.github.io/react-force-graph/example/text-nodes/index-3d.html

To disable the hover labels, you can simply do `nodeLabel={() => ''}`.

**Comment by MarkWYH** [comment]
@phamcong hello,did u finded the way to always show the label?

**Comment by gitvge** [comment]
I used the text node example with a sprite and added .linkThreeObjectExtend, which allows to show both. not sure if you could tweak the sprite so that it sits below the shape
