### ISSUE TITLE
GL_OUT_OF_MEMORY problem

### ISSUE THREAD

**Issue by qianlongwuyong2018** [vasturiano/react-force-graph#58]
When I tried to update the graph, the browser(Google Chrome) gets stuck and the graph shows very slow. At the same time, I found in the console that it gives GL_OUT_OF_MEMORY problem. Could you provide me any ideas about why this happens?

I am using React and it seems it works on my local mac but gives this error when in the windows 7 enviroment.

**Comment by vasturiano** [comment]
@qianlongwuyong2018 do you have a reproduceable example online that could be tested?
I'm assuming you don't get an error in the lib's examples like: https://vasturiano.github.io/react-force-graph/example/basic/

And how many nodes/links are in your data set?

**Comment by qianlongwuyong2018** [comment]
@vasturiano I think the data set is not too big: 300 nodes and 300 links. After first rendering the graph, if you wait for like 10 seconds, the graph is disappeared(actually it stills there but all nodes and edges become black, if you use mouse to move on the screen, the labels of nodes will be showed), and then you can find the screen gives out of memory problem.

**Comment by qianlongwuyong2018** [comment]
@vasturiano I am sorry I can't provide a reproduceable example because the example on my local machine works good but it fails on a specific machine.
