### ISSUE TITLE
LinkDirectionalArrowColor does not function when passed as a string

### ISSUE THREAD

**Issue by lvl9lightspell** [vasturiano/react-force-graph#60]
The API states that the linkDirectionalArrowColor property can be passed as either a string or a function. However, `<ForceGraph2D linkDirectionalArrowColor={'#FFFFFF'}/>` will not correctly color arrowheads while `<ForceGraph2D linkDirectionalArrowColor={() => '#FFFFFF'}/>` will.

If I'm misunderstanding the API please feel free to correct me.

**Comment by vasturiano** [comment]
@lvl9lightspell a `string` represents the link object attribute/key to use for extracting the value, not the value itself.

`linkDirectionalArrowColor="color"`
is basically a shortcut to the equivalent:
`linkDirectionalArrowColor={link => link.color}`

So, if you want to set a constant value for all links, the correct form is as you specified above, using an accessor method.

**Comment by lvl9lightspell** [comment]
Ahh. Okay, got it. Thanks for the response!
