### ISSUE TITLE
How do you change the charge of the nodes in the graph?

### ISSUE THREAD

**Issue by mmenkiti** [vasturiano/react-force-graph#61]
I would like to make the nodes further apart in the force graph, and I assume that doing so would requite an increase in the "charge" of the nodes, how would I go about doing this?

**Comment by vasturiano** [comment]
@mmenkiti assuming you have a `ref` to the graph React element, you can simply do:
```
graphRef.d3Force('charge').strength(<number>);
```
The default strength is `-60`.

**Comment by mmenkiti** [comment]
Thanks

**Comment by mmenkiti** [comment]
Thanks!

This is a great library!
