### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by mmenkiti** [vasturiano/react-force-graph#63]
whenever I mount the component, it always zooms in too close. I tried to change the zoom attribute, but it doesn't seem like the zoom is changing, no matter what value I use.

Am I doing something wrong?

render() {
  return (
		<div>
		<ForceGraph2D
		ref={el => { this.fg = el; }}
		nodeCanvasObject= {this.nodeCanvasObject}
		graphData={this.props.graphData}
		onNodeHover={this.handleHover}
		nodeLabel={this.label}
		linkDirectionalArrowLength={5}
		linkOpacity	={0.2}
		linkColor	={this.linkColor}
		linkWidth	={5}
		dagMode={'radialin'}
		dagLevelDistance={50}
		zoom={0.01,10}
		/>
		</div>
	);
}

**Comment by vasturiano** [comment]
@mmenkiti `zoom` is a component *method*, not a *prop*. you should invoke it as `this.fg.zoom(0.01, 10)`.

**Comment by xgaia** [comment]
Hello,

@vasturiano, I'm trying to use the `zoom` method, can you specify how to use it?
```javascript
<ForceGraph2D
graphData={this.props.graphState}
width={this.w}
height={this.h}
zoom={(num, ms) => {
  // ???
}}
backgroundColor="Gainsboro"
onNodeClick={this.handleSelection}
nodeCanvasObject={this.drawNode}
linkCanvasObject={this.drawLink}
/>
```

**Comment by vasturiano** [comment]
@xgaia as mentioned above you should use it as a component method, not prop. Here's an example which does a similar thing, but for `cameraPosition` instead: https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html#L24

**Comment by xgaia** [comment]
Thanks it worked.

**Comment by skhaide1** [comment]
My for dynamic force2d load how to use zoom
