### ISSUE TITLE
Conditionally rendering 2D graph loses node interaction events.

### ISSUE THREAD

**Issue by bnowlin** [vasturiano/react-force-graph#65]
https://jsfiddle.net/szn6bhk0/13/

1. Load jsfiddle
2. See 2d graph
3. Mouse over node - See text of the node
4. Click hide
5. Click show
6. Mouse over node - nothing happens

Edit: Our use case is a 3D / 2D toggle button for user's preference.

**Comment by vasturiano** [comment]
@bnowlin thanks for your report!

This has just been fixed in the latest version of `react-force-graph-2d`. So, if you use the latest (`1.5.2`), you shouldn't experience this issue any more:
```
<script src="//unpkg.com/react-force-graph-2d@1.5.2"></script>
```

**Comment by bnowlin** [comment]
Update fixed issue. Thank you for your effort.
