### ISSUE TITLE
Q: 2d graph - node aligments

### ISSUE THREAD

**Issue by mwubgadeashish** [vasturiano/react-force-graph#66]
I am using ForceGraph2D and I am not able to keep distance between the nodes. It would be help if you can let me know how use maximum available width and height so that nodes in group are not overlapping.
![image](https://user-images.githubusercontent.com/20344499/52492928-1e421900-2b7f-11e9-8960-a0bfe6e3c123.png)

`<ForceGraph2D
        graphData={jsonData.data}
        nodeId="id"
        linkSource="source"
        linkTarget="target"
        dagMode={"radialout"}
        dagLevelDistance={15}

        nodeAutoColorBy="group"
        nodeVal="val"
        nodeLabel="id"
        nodeRelSize={7}
        nodeColor="color"
        onNodeClick={this.onNodeClick}
        nodeCanvasObject={(node, ctx, globalScale) => {
          const label = node.id;
          const fontSize = 12/globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding
          ctx.fillStyle = 'transparent';
          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y+labelYAxis - bckgDimensions[1] / 2, ...bckgDimensions);
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          ctx.fillText(label, node.x, node.y+labelYAxis);
          ctx.beginPath(); ctx.arc(node.x, node.y, circleRadious, 0, 2 * Math.PI, false); ctx.fill();
        }}

        linkLabel={"value"}
        linkWidth={1}
        linkDirectionalArrowLength={5.5}
        linkDirectionalArrowRelPos={1}
        linkDirectionalParticles={0}
        onLinkClick={this.onLinkClick}
      />`

**Comment by vasturiano** [comment]
@mwubgadeashish there's possibly multiple ways to solve this issue

1) You can increase the repulsive force of the nodes, to spread them a little wider. You do that by increasing the strength of the `charge` force, something like this:
```
myGraphRef.d3Force('charge').strength(-150)
```

2) You can add collision forces to the nodes, to prevent them from overlapping. See this example for more details:
https://vasturiano.github.io/react-force-graph/example/collision-detection/

3) If it can be solved just by zooming in a little closer, you can simply programatically adjust the zoom level, with:
```
myGraphRef.zoom(<number>)
```

Hope that helps.

**Comment by mwubgadeashish** [comment]
@vasturiano Thanks for quick help....

#1 above worked for me by just adding
`
  componentDidMount() {
    this.fg.d3Force('charge').strength(-150)
  }
render(){
....
      <ForceGraph2D
        ref={el => this.fg = el}

}
`

#3 above will use to implement manual zoom.

Once again thanks for help and its a great component !!!

Thanks,
Ashish
