### ISSUE TITLE
Node - How to add image with arc and text

### ISSUE THREAD

**Issue by mwubgadeashish** [vasturiano/react-force-graph#67]
@vasturiano 

I have added arc and Text for the node and also want to add node.logo in same representation of 2d graph. I have tried the example provided but can not see the mages.

Ex tried: https://github.com/vasturiano/react-force-graph/blob/master/example/img-nodes/index.html
Sample Node:

{"id": "323d77de-daf5-5b3e-bb34-xxxxx7bbe8a", "name": "Apple", "type": "organization", "group": 2, "color": "#fc6b23", "logo": "https://crunchbase-production-res.cloudinary.com/image/upload/h_120,w_120,f_jpg/v1507847753/placeholder_zgpxrr.png"},

```
        nodeCanvasObject={(node, ctx, globalScale) => {
          //console.log('ctx', ctx);
          const label = node.name;
          const fontSize = 12/globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding
          ctx.fillStyle = 'transparent';
          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y+labelYAxis - bckgDimensions[1] / 2, ...bckgDimensions);
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          if(node.type === 'edge') {
            ctx.beginPath(); ctx.arc(node.x, node.y, edgeRadious * 1.2, 0, 2 * Math.PI, false); ctx.fill();
            ctx.beginPath();
            ctx.arc(node.x, node.y, edgeRadious, 0, 2 * Math.PI, false);
            ctx.fillStyle = 'white';
            ctx.fill();
          } else {
            ctx.fillText(label, node.x, node.y+labelYAxis);
            if (highlightNodes.indexOf(node) !== -1) {
              ctx.fillStyle = 'black';
            }

            ctx.beginPath(); ctx.arc(node.x, node.y, circleRadious * 1.2, 0, 2 * Math.PI, false); ctx.fill();
           //if node.logo then show here

           //else below arc
            ctx.beginPath();
            ctx.arc(node.x, node.y, circleRadious, 0, 2 * Math.PI, false);
            ctx.fillStyle = 'white';
            ctx.fill();
          }
        }}
```

![image](https://user-images.githubusercontent.com/20344499/52671344-abfb6c80-2ecf-11e9-9e57-8fcac4bbe497.png)

**Comment by mwubgadeashish** [comment]
@vasturiano 

In above mentored example I have tried `nodeCanvasObject` but it did not worked for me. might be doing something wrong.

more info:

`
import { ForceGraph2D} from 'react-force-graph';
import TextSprite from 'three.textsprite';
......

        nodeThreeObject={({ logo }) => {
          const imgTexture = new TextSprite.TextureLoader().load(`${logo}`);
          const material = new TextSprite.SpriteMaterial({ map: imgTexture });
          const sprite = new TextSprite.Sprite(material);
          sprite.scale.set(12, 12);
          return sprite;
        }}

`

**Comment by vasturiano** [comment]
@mwubgadeashish if you are in `2d` mode, make sure to use `nodeCanvasObject`, not `nodeThreeObject`. This example from `force-graph` may be of help here: https://github.com/vasturiano/force-graph/blob/master/example/img-nodes/index.html

**Comment by mwubgadeashish** [comment]
@vasturiano thanks for response. I am getting following error:

`
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'`

my code is:

`import { ForceGraph2D} from 'react-force-graph';
...
return <div className="force-chart" id="force-chart">
<ForceGraph2D
        ref={el => this.fg = el}
        graphData={data}
        nodeId="id"
        linkSource="source"
        linkTarget="target"
        dagMode={"radialout"}
        dagLevelDistance={40}
        zoom={false}
        width = {width}
        height = {height}
        backgroundColor="transparent"
        nodeAutoColorBy="group"
        nodeVal="val"
        nodeLabel={this.onNodeRollover}
        nodeRelSize={7}
        nodeColor="color"
        onNodeClick={this.onNodeClick}
        nodeCanvasObject={(node, ctx, globalScale) => {
          //console.log('ctx', ctx);
          const label = node.name;
          const fontSize = 12/globalScale;
          const size = 12;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding
          ctx.fillStyle = 'transparent';
          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y+labelYAxis - bckgDimensions[1] / 2, ...bckgDimensions);
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          ctx.fillText(label, node.x, node.y+labelYAxis);
          if(node.type === 'edge') {
            ctx.beginPath(); ctx.arc(node.x, node.y, edgeRadious * 1.2, 0, 2 * Math.PI, false); ctx.fill();
            ctx.beginPath();
            ctx.arc(node.x, node.y, edgeRadious, 0, 2 * Math.PI, false);
            ctx.fillStyle = 'white';
            ctx.fill();
          } else {
            if (highlightNodes.indexOf(node) !== -1) {
              ctx.fillStyle = 'black';
            }
            ctx.beginPath(); ctx.arc(node.x, node.y, circleRadious * 1.2, 0, 2 * Math.PI, false); ctx.fill();
            if(node.logo) {
              ctx.drawImage(node.logo, node.x - size / 2, node.y - size / 2, size, size);
            } else {
              ctx.beginPath();
              ctx.arc(node.x, node.y, circleRadious, 0, 2 * Math.PI, false);
              ctx.fillStyle = 'white';
              ctx.fill();
            }
          }
        }}
        linkLabel={"value"}
        linkWidth={link => link === highlightLink ? 2 : 1}
        linkDirectionalArrowLength={3.4}
        linkDirectionalArrowRelPos={1}
        linkDirectionalParticles={0}
        onLinkClick={this.onLinkClick}
        onLinkHover={this.onLinkHover}
      />
    </div>`

**Comment by mwubgadeashish** [comment]
I am also getting one more warning and wanted to let you know:

`aframe-master.js:58526 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`

**Comment by Abubakr077** [comment]
@qasimalbaqali what is "Graph" in your code, can you explain that?

![Screenshot_7](https://user-images.githubusercontent.com/18698636/68365301-0f11eb00-0152-11ea-9836-21a9ca62465d.png)

**Comment by qasimalbaqali** [comment]
@Abubakr077 I can't remember exactly, but re-reading this, I might have made a mistake assigning the Graph to the value of NODE_R, since this variable holds the node radius which is a number/int. So just replace it with a number instead of the `Graph`.
