### ISSUE TITLE
Trigger Node Highlight from External Component

### ISSUE THREAD

**Issue by wadehenning** [vasturiano/react-force-graph#69]
Is it possible to trigger a node event from an interaction with an external component?  Suppose as a base case we use the Les Miserables data.  If I have a list of name components and also a 3D force graph of nodes associated with each name, when I hover over the name on the list, I would like the associated node to highlight like in the example without re-rendering the whole graph.

**Comment by SZBoatwright** [comment]
Try this:

In graphData.nodes, add `isSelected: true/false` on each node. Your data structure should look like this:

	graphData = {{
		nodes: [
			{
				id: node-id,
				name: node-name,
				isSelected: true or false,
				etc...
			},
			etc...
		]
	}}

 and then in your `ForceGraph3D` component, add this prop: 

`nodeColor={node => node.isSelected ? '#000000' : '#ffffff'}`


When a user hovers over the corresponding item in the list beside the graph, just set `isSelected` to true/false on the corresponding nodes. 

Hope that helps! 🙂

**Comment by wadehenning** [comment]
Thanks for your excellent answer.  With that in mind, I thought I would try and change the scale of my sprite, but it does not do anything.  Can you offer advice? Thank you!

```
nodeThreeObject={({ id, points, cluster, keyword, isSelected }) => {        
          let sprite = new THREE.Sprite( this.generateMaterial(points, cluster, colors, id, keyword));
          
          //make the sprite bigger with hover on adjoining component
          let spriteWidth = isSelected ?  this.state.canvasWidth*5 : this.state.canvasWidth
          let spriteHeight = isSelected ? this.state.canvasHeight*5 : this.state.canvasHeight         
          sprite.scale.set(spriteWidth,spriteHeight,1); 
          return sprite;      
        }}
```
