### ISSUE TITLE
changing node drag functionality to include multiple nodes

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/react-force-graph#70]
I have a list of selected nodes in the application that I'm building that is held outside of the forcegraph, and it would be awesome if there were a way for those selected nodes to also be dragged when I drag a node. 

So, as an example, if I have three nodes selected, and I drag one of those nodes, I would like for all currently selected nodes to drag alongside it instead of just the node I clicked on. 

Is there any way to do this?

**Comment by SZBoatwright** [comment]
I tried that but am having some issues. Here's a gif since that's easier than describing it: 

![](https://sh-drop.s3.us-east-1.amazonaws.com/zb/node-drag-glitch.gif)

I think what might be happening is that I'm changing the position of the nodes in state, which blocks out forcegraph from editing the position of those nodes. Is there a way that I can go into the physics engine and modify the node positions directly?

**Comment by vasturiano** [comment]
@SZBoatwright it's difficult to say from just a gif, but perhaps something is incorrect with the x,y calculations of the nodes you wish to drag. They are actually moving, but to the wrong position.
Manipulating the `x`,`y` coordinates is how you modify the positions directly. Those are the same attributes that the force engine modifies. Further, if you'd like the force engine to stay out of changing them, you can set (fixed) `fx`,`fy` attributes on the nodes, they are propagated directly to the x, y attributes, without interference from the force engine. Just make sure to reset them (back to `null` or `undefined`) at the end of the drag so the force engine takes over.

**Comment by SZBoatwright** [comment]
Thanks!

Using fx and fy is actually perfect because I would like nodes to stay where they are dragged to anyways.

I also moved graph data out of state, which I think fixed the issue. When using `this.setState()` I had to overwrite all of the nodes instead of just the ones that were being updated. It's working great now. 👍🏻
