### ISSUE TITLE
Graph instance (this.fg) is undefined. 

### ISSUE THREAD

**Issue by naumanzchaudhry** [vasturiano/react-force-graph#71]
Trying this out. I want to set the link distance (ForceGraph2D)
```
import {ForceGraph2D} from 'react-force-graph';
```

```
componentDidMount(){
      this.fg.d3Force("link").distance(120)
}
```

In my render method.
```
<ForceGraph2D
       ref={el => { this.fg = el; }}
      // other graph props.
/>
```
**ISSUE**
> this.fg is undefined

What am I doing wrong?

**Comment by jsslngz** [comment]
I have the same problem, how did you make it work? @naumanzchaudhry

**Comment by naumanzchaudhry** [comment]
@jsslngz How you are using it?
