### ISSUE TITLE
Showing context menu 

### ISSUE THREAD

**Issue by naumanzchaudhry** [vasturiano/react-force-graph#72]
I need to present a context menu with some options to perform actions when right clicked a node. I know that there is a `onNodeRightClick` callback available. How would I do that?

**Comment by SZBoatwright** [comment]
The best way to do this would probably be to make a separate React component that opens up when you right click on a node.

The component could have an isShowing prop that would be set to true when onNodeRightClick fires. The location of the context menu could be set by the x,y values of another event on the document body since the onNodeRightClick event doesn't return any DOM coordinates.

**Comment by naumanzchaudhry** [comment]
Thanks much for taking your time to comment. Already done similar thing. On node right click I show/hide a context menu with a state variable. And I determine the position of this context menu by registering a onMouseMove event (which gives me coordinates with event.clientX and event.clientY) on a div which wraps our graph component.

**Comment by Antti-Kaikkonen** [comment]
I'm trying to make a context menu like this that would open as soon as the right mouse button goes down instead of waiting for the mouse button to be released. However I can't find a way to register a "mousedown" event listener. Any help would be appreciated.

**Comment by naumanzchaudhry** [comment]
@Antti-Kaikkonen please check my last comment.

**Comment by Antti-Kaikkonen** [comment]
Yeah sorry. I thought I already tried it but the events didn't trigger my function. I must have had a typo or something in my code because I got it working now:
```
<div 
  onContextMenu={(e)=>{console.log("CONTEXT MENU", e)}}
  onMouseDown={(e) => {console.log("MOUSE DOWN", e)}}
>
  <ForceGraph2D
    ...
  />
</div>
```

**Comment by kunal-singh** [comment]
I was stuck in the same issue for some time. Here is a barebones [working example](https://codesandbox.io/p/sandbox/react-force-graph-context-menu-84cdjc) for people stuck in a similar problem. I am using radix-ui context menu here, I think a similar approach would work for any other lib too.
