### ISSUE TITLE
onNodeClick() not firing when control key is down

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/react-force-graph#73]
I'm trying to implement multi-selection into my forcegraph. So far on click, I have nodes being added to a list of selected nodes, and those selected nodes are rendered as selected. 

My issue is coming when I try to control-click on nodes (for multi-selection). For some reason, onNodeClick() isn't fired then. 

Just wondering if this is a bug or something I can turn off. Thanks!

**Comment by vasturiano** [comment]
@SZBoatwright I believe control-click is interpreted as right-clicking, at least in some OSes. So, you should instead use the `onNodeRightClick` event callback.

**Comment by SZBoatwright** [comment]
Thanks!

**Comment by ulisescarreonalvarez** [comment]
@SZBoatwright @vasturiano  Hi guys, is it possible to change the style of a single node in on a click event?

Regards in advance
