### ISSUE TITLE
Differentiating canvas & node click

### ISSUE THREAD

**Issue by naumanzchaudhry** [vasturiano/react-force-graph#74]
I am trying to differentiate the canvas and node click. As the node is also a part of the canvas hence it fires both events one by one. 

Basically, on node click I use `centerAt` and `zoom` to focus the clicked node. While on canvas click I want to reset the zoom level to a default value. 

If I setup a click handler on  a graph wrapping `div`. It will give me an `event` object not the node object. 

How should I approach that? @vasturiano

**Comment by vasturiano** [comment]
@naumanzchaudhry you are right that node click events bubble up the DOM so you're able to detect them in your wrapping div. This is by design. if you're trying to differentiate the wrapping div clicks without the node click, I suppose you could verify whether a node click event was issued at the same time, using some state variable on your side.

**Comment by vasturiano** [comment]
There's also another (possibly easier) way to do it. You can keep track of which node is currently under the mouse pointer using `onNoveHover(node)`. If there's no node under the pointer that callback will return `null`. If you assign that to a variable, and that is currently `null` at the time of click, you know the user has clicked on the empty space / background.

**Comment by naumanzchaudhry** [comment]
> There's also another (possibly easier) way to do it. You can keep track of which node is currently under the mouse pointer using `onNoveHover(node)`. If there's no node under the pointer that callback will return `null`. If you assign that to a variable, and that is currently `null` at the time of click, you know the user has clicked on the empty space / background.

Haven't checked the first one yet. But the second one works fine.

**Comment by naumanzchaudhry** [comment]
> There's also another (possibly easier) way to do it. You can keep track of which node is currently under the mouse pointer using `onNoveHover(node)`. If there's no node under the pointer that callback will return `null`. If you assign that to a variable, and that is currently `null` at the time of click, you know the user has clicked on the empty space / background.

Worked perfectly fine!
