### ISSUE TITLE
Is there a way to modify the canvas ourselves?

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/react-force-graph#75]
I'm currently trying to add in box selection to my graph. My problem is that I don't have a way to add elements to the canvas without them immediately being overwritten. Would it be possible to add a callback when the canvas is rendered each frame for adding in our own canvas elements?

I've already looked into adding in extra canvas elements to the node canvas object, but that seems pretty messy to me. I'm also looking for a way to convert DOM coordinates (from a click event) into coordinates for your canvas object.

**Two Issues**
- I need a way to draw to the canvas. Whenever I try to myself, whatever I draw immediately gets overwritten, unless I use the node/link canvas object.
- I need a way to convert DOM coordinates into canvas coordinates

Let me know if you have any suggestions, thanks!

**Comment by naumanzchaudhry** [comment]
@SZBoatwright for your second issue. Mouse position gives you the exact coordinates. You can get this by wrapping your graph component with a `div` and registering a `onMouseMove` event on that. Because you are registering the event on graph's direct parent and not whole `body` you get the `canvas` coordinates.

```
<div onClick={this.handleCanvasClick}>
     <ForceGraph2D />
</div>
```
And the handler

```
handleCanvasClick = event => {
     const coordinates = [event.clientX, event.clientY]
}
```

**Comment by SZBoatwright** [comment]
@naumanzchaudhry Sorry, I didn't explain what I'm trying to get very well. I'm trying to get the position of my mouse relative to the nodes in the simulation. Adding an onClick event listener will give me the position of the mouse relative to the canvas element when I click on it, but not relative to the nodes in the canvas if that makes sense.

**Comment by SZBoatwright** [comment]
@naumanzchaudhry Let me go ahead and take back what I just said. 😅 What you suggested actually _does_ give me the correct canvas position, it was just being offset by the node position since the only way I've found to directly modify the canvas is within the `nodeCanvasObject` prop. 

So now I do have a box drawing on the screen when I drag my mouse, but it's happening when the nodes are drawn which seems messy to me. So I'm still trying to figure out two things:
- How to add my own elements to the canvas during each render update. I'm currently doing this within the `nodeCanvasObject` and it works, but I would rather have a less hacky way to do it.
- How to translate the node position to the screen position. I suppose there might be a way to do this within the `nodeCanvasObject` somehow, but it would be great if there were `nodeDomX` and `nodeDomY` keys in the node object or something similar

**Comment by vasturiano** [comment]
@SZBoatwright 
On your first question I guess there's two ways to go about, depending on what you intend. If you don't want your extra items to move with the canvas pan/zoom you can just add a background (or foreground) canvas overlay, external to `force-graph` that show the overlap. If you want the new items to interact with the existing nodes, by means on canvas pan etc, you should do it via `nodeCanvasObject` as you mentioned. I'd suggest actually adding extra elements in your `graphData` nodes array that represent this extra objects, and then use `nodeCanvasObject` to decide how to draw them. You can even fix them to specific positions using `fx`, `fy` attributes.

On the second point, you can determine the current canvas translation by calling the `.centerAt()` (x, y translation) and `.zoom()` (scale) methods. From there it should be easy to calculate where nodes x, y positions are rendered in document coordinates.

Let me know if that helps.
