### ISSUE TITLE
Groups as Nodes not draggable

### ISSUE THREAD

**Issue by amedov-denis** [vasturiano/react-force-graph#78]
Hi @vasturiano ,

I'm using the following function for `nodeThreeObject` prop:

```jsx
 get3dNode = (node: INode) => {
    const text = new SpriteText(node.name);
    text.color = "white";
    text.textHeight = 3;

    const geometry = new THREE.SphereGeometry(5, 32, 32);
    const material = new THREE.MeshBasicMaterial({
      color: node.color,
      opacity: 0.8
    });
    const mesh = new THREE.Mesh(geometry, material);

    const group = new THREE.Group();

    text.position.setZ(10);
    group.add(text);
    group.add(mesh);

    return group;
  };
```

But now the nodes are not draggable any more.
Also `onNodeDrag` is not called anymore 

Directly returning `mesh` is behaving as expected.
Returning `group` is not draggable

Thanks for your support!

**Comment by amedov-denis** [comment]
I found this workaround using a transparent sphere as drag handler.
https://github.com/vasturiano/3d-force-graph/blob/ee61559422568ed2a25a7154da7d443af7574493/example/text-nodes/index.html

```jsx
get3dNode = (node: INode) => {
    // use a sphere as a drag handler
    const obj = new THREE.Mesh(
      new THREE.SphereGeometry(10),
      new THREE.MeshBasicMaterial({
        depthWrite: false,
        transparent: true,
        opacity: 0
      })
    );

    // add node as child
    const geometry = new THREE.SphereGeometry(5, 32, 32);
    const material = new THREE.MeshBasicMaterial({
      color: node.color,
      opacity: 0.8
    });
    const nodeMesh = new THREE.Mesh(geometry, material);

    obj.add(nodeMesh);

    if (node.name) {
      // add sprite as child
      const text = new SpriteText(node.name);
      text.color = "white";
      text.textHeight = 3;
      text.position.setZ(10);

      obj.add(text);
    }

    return obj;
};
```

I'm not really sure why this is needed, but it works! :)

**Comment by vasturiano** [comment]
@amedov-denis thanks for reaching out. The top level object is what's used for drag handles, and `three-drag` doesn't work well with groups (or sprites), that's why having a `mesh` instead of a `group` works.

You can also promote your visible sphere to top mesh and use that as drag handle. The text element would simply be a child of it.
