### ISSUE TITLE
import npm installed modules instead of unpkg

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#79]
I want to import npm installed modules 
however, I am **unable to import d3.csvParse & d3.forceCollide**

**Also, errors** 
**1. this.fg is undefined**
**2.  d undefined   if (d.nodes.length || d.links.length)  in node_modules/force-graph/dist/force-graph.module.js:865**

Here are my import statements
```
import React from 'react';
import ForceGraph2D from 'react-force-graph-2d';
import * as d3 from "d3";
import dat from 'dat-gui';
import ReactDOM from 'react-dom';
import {quadtree} from 'd3-quadtree';
import * as fg from 'd3-fg';
import { d3Force, forceCollide } from 'd3-force';
```

Code - https://github.com/vasturiano/react-force-graph/blob/master/example/tree/index.html

**There are no errors if i load the library via a script tag**

**Comment by Parul-Kudtarkar** [comment]
PS. I would like to add additional/customize events hence installing modules locally instead of using unpkg

**Comment by Parul-Kudtarkar** [comment]
Hello, Any solution to above  issue?

**Comment by vasturiano** [comment]
@Parul-Kudtarkar this seems related to those other D3 modules, and not specific to this library.
https://github.com/d3/d3-force
https://github.com/d3/d3-dsv

One possible cause is that you're app is expecting strictly ES5 modules while the modules above are known to have ES6 code. But I'd suggest asking the question there.
