### ISSUE TITLE
Node label is not showing HTML content

### ISSUE THREAD

**Issue by Majky336** [vasturiano/react-force-graph#81]
Hey there,

first of all, thanks for great work! I have found just little issue, when trying to return some HTMLelement inside `nodeLabel` prop. Example:

```
createNodeLabel = node => {
    const { firstAtt, secondAtt } = node;

    return (
        <div>
            <div>{firstAtt}</div>
            <div>{secondAtt }</div>
        </div>
    );
}
...
render() {
    return (
         <ForceGraph3D
            graphData={graphData}
            nodeLabel={this.createNodeLabel}
          />
    );
}
```
If using this code, after hover on node I get tooltip with `[object Object]` text inside it. Returning string or string literal in `createNodeLabel` works. In the docs there is written that HTML is supported, so what am I doing wrong? Could you help please?

**Comment by vasturiano** [comment]
@Majky336 Thanks for reaching out. `nodeLabel` supports HTML but not JSX as you're passing now.
Just use string literals to pass the tooltip content:
```
return ```<div>
  <div>{firstAtt}</div>
  <div>{secondAtt }</div>
</div>```;
```

**Comment by Majky336** [comment]
Thanks for guiding me, I didn't realize that I can use it like this. Thanks for the help and keep up the great work! :)

**Comment by vasturiano** [comment]
@ItFlyingStart please use single ticks in the string literal, and if you wish to include variables in the template they should be preceeded by a `$`, like so:
```js
return `<div>
  <div>${id}</div>
  <div>${group}</div>
</div>`;
```

**Comment by ItFlyingStart** [comment]
That works. Thank you so much.
