### ISSUE TITLE
Link color not triggering on rerender

### ISSUE THREAD

**Issue by Majky336** [vasturiano/react-force-graph#82]
Hello, right now I am currently facing an issue with rerendering of the links. When passing a callback for linkColor props, the callback is only called on initial render. It seems like it is not reacting to any state changes.

An example below: The console will output the render every time I hover on a different node in graph although the `createLinkColor` callback is not triggering. I even tried to use console.log in `shouldComponentUpdate` and it was showing that the `highlightPath` array has changed. I also followed one of your examples for highlighting nodes and links and tried to implement it in a similar way. 

The behaviour works, if the whole tree is "builded" again. For example if I add nodeClick callback and change some prop, then the link color changes. Can I achieve dynamic changing of link colors on node change? 

```
class Tree extends Component {
  constructor(props) {
    super(props);

    this.state = { highlightPath: [], hoveredNode: null };
  }

  createLinkColor = link => {
    const { highlightPath } = this.state;
    const { source, target } = link || {};

    console.log('createLinkColor', highlightPath);

    if (highlightPath.includes(source) && highlightPath.includes(target)) {
      return "red";
    }

    return "#000000";
  };

  handleNodeHover = node => {
    const { hoveredNode } = this.state;
    const { nodes } = this.props;
    const { id: hoveredNodeId } = hoveredNode || {};
    const { id } = node || {};

    if (node && id !== hoveredNodeId) {
      let que = [id];
      let highlightPath = [id];

      while (que.length > 0) {
        const parentID = que.shift();
        const nextParent = nodes.find(node => node.id === parentID);
        const { parent } = nextParent || {};

        if (nextParent && nextParent.id !== 0) {
          que.push(parent);
          highlightPath.push(parent);
        }
      }

      this.setState({ hoveredNode: node, highlightPath });
    }
  };

  render() {
    const { graphData } = this.props;
    const { highlightPath } = this.state;
    console.log("render", highlightPath);

    if (!graphData) {
      return <h1>No data.</h1>;
    }

    return (
        <ForceGraph3D
          backgroundColor="#ffffff"
          graphData={graphData}
          linkWidth={2}
          linkColor={this.createLinkColor}
        />
    );
  }
}

export default Tree;
```

**Comment by vasturiano** [comment]
@Majky336 the `<ForceGraph3D/>` component is not updating because none of its props are changing between renders. What you're passing to `linkColor` is a reference to the function, and that reference remains the same across renders. This is normal React behavior. 
The issue starts because your `createLinkColor` function is not pure, but changes behaviour based on the components state. If you have that function re-declared at every render instead of being a class method, it should trigger the component update.

Again, please keep in mind this is not `react-force-graph` specific, just React functionality.
