### ISSUE TITLE
ForceGraph2D how to do in ondragnode the orphans nodes do not move out

### ISSUE THREAD

**Issue by salgadonline** [vasturiano/react-force-graph#83]
When I start drag a node in a graph the others graphs around start move out. I wanna know if is there a way to keep them static?

**Comment by vasturiano** [comment]
@salgadonline you can set `.cooldownTicks(0)` to limit the iterations of the force engine at every drag.

**Comment by salgadonline** [comment]
First thank you for this amazing tool!!! 

I try to set the value in my component using the ref of ForceGraph2D fg:

componentDidMount() {        
        this.fg.zoom(2.0, 1);
        this.fg.d3Force('charge').strength(-10);
        this.fg.cooldownTicks(0);
    }
with no success...

Thanks in advance for the help!!!
best regards.

**Comment by vasturiano** [comment]
@salgadonline sorry for the misleading, it should be a component prop:
`<ForceGraph2D cooldownTicks={0} ... />`

**Comment by salgadonline** [comment]
Thanks a lot!!! it works fine.
