### ISSUE TITLE
VR force graph not initially rendering when doctype is declared

### ISSUE THREAD

**Issue by pfernandez** [vasturiano/react-force-graph#85]
Please see the example [on Codepen](https://codepen.io/paul4nandez/pen/dLLgqP). Click Settings > Javascript at the top see the included dependencies.

If you change `ForceGraphVR` to `ForceGraph2D` or `ForceGraph3D`, it works.

I also tried this with a fresh install of `create-react-app` with the same result. The "goggles" icon actually does appear, and clicking it does show a graph, however the initial rendering does not load.

### Update
I found that removing the `<!DOCTYPE html>` tag from index.html in `create-react-app` fixes the problem. Conversely, you can reproduce the issue by adding `<!DOCTYPE html>` to the [basic example](https://github.com/vasturiano/react-force-graph/blob/master/example/basic/index.html). I'll change the title of this issue, because obviously this isn't a React versioning thing.

**Comment by ulisescarreonalvarez** [comment]
Hi,

So, how can we fix this issue without removing the doctype tag?

**Comment by parties** [comment]
@vasturiano why was this closed?
