### ISSUE TITLE
Manual force reheat / simulate node movement/dragging? Re-applying forces.

### ISSUE THREAD

**Issue by Kira9204** [vasturiano/react-force-graph#89]
Hi! 

Im trying to create a "freeze / disable forces" mode (toggle) when using this graph. It's useful since it makes it easier to visualize and drag between the nodes to create new links etc, but i can't get the node to retract once it get out of the freeze mode.

Current approach: When disabling forces, store the forces away and then disable them
<pre>
export const applyGraphForces = (graphRef) => {
      graphRef.current.d3Force('link').iterations(1).distance((link) => FORCE_LINK_DISTANCE);
      graphRef.current.d3Force('charge').strength(FORCE_MANYBODIES_STRENGTH)
.distanceMax(NODE_RELSIZE);
      graphRef.current.d3Force('collide', d3ForceCollide(FORCE_COLLIDE_RADIUS));
      graphRef.current.d3Force('center', null);
      graphRef.current.zoom(ZOOM, 0);
};

export const clearGraphForces = (graphRef) => {
        forceGraphForces = {
          charge: graphRef.current.d3Force('charge'),
          link: graphRef.current.d3Force('link'),
          collide: graphRef.current.d3Force('collide')
        };
        graphRef.current.d3Force('charge', null);
        graphRef.current.d3Force('link', null);
        graphRef.current.d3Force('collide', null);
};

Then re-apply the stored away forces when the prop switches back
`
export const reApplyForces = (graphRef) => {
       graphRef.current.d3Force('link', forceGraphForces.link);
       graphRef.current.d3Force('charge', forceGraphForces.charge);
       graphRef.current.d3Force('collide', forceGraphForces.collide);
};
</pre>
The problem is that once you've put a large distance between the nodes, and then flip back the forces (reApplyForces with or without applyGraphForces), the distance doesn't retract much if at all.
However, you drag one of the nodes, even just slightly, the forces kicks in and the distance shrinks to the expected one.
Do you have some suggesting to working around this problem without calling refresh()?
Maybe manually triggering some node force or simulating dragging a node in the canvas?

<img width="1075" alt="Screenshot 2019-05-17 at 21 04 18" src="https://user-images.githubusercontent.com/2965460/57950418-76f42100-78e7-11e9-9a69-4745fc67ab16.png">

**Comment by vasturiano** [comment]
Hi @Kira9204, I'd suggest setting `.cooldownTicks(0)` if you want to disengage the force layout (and reset its value when you'd like the forces to be active again).

**Comment by naumanzchaudhry** [comment]
Hi @Kira9204 just an off-topic question. Can you please share how you are drawing `images` as nodes. I am using `ForceGraph2D` and doing it like this but don't have such fine results as yours. 

```
import userImage from 'assets/user.png'

_paintNode = (node, ctx) => {
     let image = new Image();
     image.src = userImage;
     
    // drawing the image.
    ctx.drawImage(image, node.x, node.y);
}
```

**Comment by Kira9204** [comment]
@naumanzchaudhry Have a look at the sandbox i've made [here,](https://codesandbox.io/s/vigilant-allen-rgtwn?fontsize=14), you can of couse make it prettier, buit it works well as a demonstration. In the project im using it for i have a lot of custom logic in both the nodes and links department when drawing.
Something like this should do the trick in you want to render both images and labels with a round border around the text:

```
  const image = loadedImages.get(node.id);
  if (image) {
    ctx.drawImage(
      image,
      node.x - IMAGE_SIZE / 2,
      node.y - IMAGE_SIZE / 2,
      IMAGE_SIZE,
      IMAGE_SIZE
    );
  }

  ctx.font = `${IMAGE_SIZE / 3}px Sans-Serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  const textSize = ctx.measureText(node.name);
  ctx.fillStyle = '#E6E6E6';

  const textRRY = isThisNodeSelected
    ? node.y + IMAGE_SIZE - 5
    : node.y + IMAGE_SIZE * 0.7 - 5;

  ctx.roundRect(
    node.x - textSize.width / 2 - 5,
    textRRY,
    textSize.width + 10,
    IMAGE_SIZE / 3 + 2,
    3
  );
  ctx.fill();

  ctx.fillStyle = '#000';

  const filltextY = isThisNodeSelected
    ? node.y + IMAGE_SIZE
    : node.y + IMAGE_SIZE * 0.7;
  ctx.fillText(node.name, node.x, filltextY);
```
@vasturiano Your solution worked perfectly! This is a really awesome library!  Thank you for the support :)
