### ISSUE TITLE
Collapsible Force Layout

### ISSUE THREAD

**Issue by naumanzchaudhry** [vasturiano/react-force-graph#90]
I am trying to have a collapsible force layout. Is there any option available at the moment? An example [d3 collapsible force layout](https://bl.ocks.org/mbostock/1093130).

In a simplest version, I can register a click handler on node which toggles the  view for descendant nodes of a particular node.  What is the best way to show/hide the nodes without effecting performance?

**Comment by naumanzchaudhry** [comment]
@vasturiano can you please comment on this?

**Comment by vasturiano** [comment]
This should be doable by manipulating the data in the graph using `.graphData(...)` on `nodeClick` interactions.
Would be great to have an example file showcasing this functionality. Would you be willing to put together a PR for it?
