### ISSUE TITLE
Translation values of the canvas

### ISSUE THREAD

**Issue by platonovsimeon** [vasturiano/react-force-graph#91]
Is there a way to get the translation values (zoom and pan) of the canvas?

**Comment by vasturiano** [comment]
@platonovsimeon yes, you can simply call the getter methods `.zoom()` and `.centerAt()`.

**Comment by platonovsimeon** [comment]
```
const transform = canvas.__zoom;
const x = (event.clientX-transform.x)/transform.k;
const y = (event.clientY-transform.y)/transform.k;
```
I would like to be able to create nodes by clicking on canvas. This code gives me almost correct position for the node. Is there a way to make the position more correct?
