### ISSUE TITLE
Creating nodes by clicking on canvas

### ISSUE THREAD

**Issue by platonovsimeon** [vasturiano/react-force-graph#92]
```
const transform = canvas.__zoom;
 const x = (event.clientX-transform.x)/transform.k;
 const y = (event.clientY-transform.y)/transform.k;
```
I would like to create nodes by clicking on canvas. This gives me almost correct position for the node. Is there a way to make this more correct?

**Comment by vasturiano** [comment]
@platonovsimeon keep in mind that the `0,0` location of the canvas is not the upper-left but the center of the canvas. Not sure, but that may be the reason for your skew. If so, you should translate the pointer locations by half of the canvas size.
