### ISSUE TITLE
download graph as jpeg or png 

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#93]
Any recommendations on downloading dynamically generated graphs by react-force-graph module in png or jpeg format?

**Comment by vasturiano** [comment]
@Parul-Kudtarkar you could use [Canvas2Image] to convert the content of the canvas at any given time to an image.
You can get the canvas DOM element by calling `myGraph.renderer().domElement`.

**Comment by Parul-Kudtarkar** [comment]
Thanks @vasturiano ! Also, is there an inbuilt legend to use with react-force-graph such as @vx/legend?

**Comment by vasturiano** [comment]
There is a simple tooltip that you can use with `nodeLabel` and `linkLabel`. Otherwise you can implement your own using `onNodeHover`/`onLinkHover`.
