### ISSUE TITLE
How to make node positions fixed ? 

### ISSUE THREAD

**Issue by rohankk2** [vasturiano/react-force-graph#95]
Suppose I drag a node out it just moves back to its original position. I want the node to stay in the new position i moved it to. How to do this ?

**Comment by vasturiano** [comment]
Whenever you're satisfied with the generated layout you can set `cooldownTicks={0}`. This will tell the force layout engine to no longer make corrections when dragging nodes.

**Comment by ddor254** [comment]
@vasturiano  how can we accomplish that ? when i do : 
`cooldownTicks={this.state.coolDownTicks }` 
and in 'onNodeDragEnd`: `this.setState({coolDownTicks:0})` 

this cause re-render with `cooldownTicks = 0`, but the node does not stay in the position i dragged him to.

**Comment by vasturiano** [comment]
@ddor254 if you wish to fix a single node after it has been dragged, I suggest a different approach: to add `fx`, `fy` and `fz` attributes to just that node so the others are not affected. 

Like in this [example](https://vasturiano.github.io/react-force-graph/example/fix-dragged-nodes/):
https://github.com/vasturiano/react-force-graph/blob/fbb2d51dd73ac733f83fb7ce72eb6bb7e54cb6a3/example/fix-dragged-nodes/index.html#L22-L26

**Comment by ddor254** [comment]
@vasturiano  thank you for the quick response, I will try it.

where can i read about the `fx,fy, fz` and the other node's attributes??

i mean - where can i read about the `node` object and the `link` object ?

**Comment by vasturiano** [comment]
https://github.com/vasturiano/d3-force-3d#simulation_nodes
https://github.com/vasturiano/d3-force-3d#forceLink

**Comment by ddor254** [comment]
@vasturiano  thank you for your response and help .
