### ISSUE TITLE
 Force directed tree distance between links at various level

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [vasturiano/react-force-graph#97]
![Screen Shot 2019-06-14 at 6 57 42 PM](https://user-images.githubusercontent.com/22722805/59545678-aa21d400-8ed6-11e9-8fde-69b48f8088f9.png)

As you can see above - some of the links have 2 levels and others 3 levels (red in the figure attached). In my case rendering is better when I do not use dag mode, is there a way to customize the link length  (where level 4 is spread out)

**Comment by vasturiano** [comment]
@Parul-Kudtarkar you can access the link force using `myGraph.d3Force('link')`.
Then there's various settings you can configure, including the length via the `distance` prop: `myGraph.d3Force('link').distance(<num or fn>)`.

See more at https://github.com/vasturiano/d3-force-3d#forceLink .

**Comment by Parul-Kudtarkar** [comment]
Thanks @vasturiano this helps!

**Comment by furiousOyster** [comment]
I there perhaps a snippet of code someone can share showing how to access the d3Force function using the ForceGraph3D Reach component ?  I've been browsing through the runtime objects and the source and I can't seem to figure it out.  I can see the d3Force function on the ForceGraph3D prototype, but I can't figure out how to call it.  Help ?

**Comment by vasturiano** [comment]
@furiousOyster see the code in the following example. It is for the 2D variant, but the React pattern is the same:
https://github.com/vasturiano/react-force-graph/blob/master/example/collision-detection/index.html#L29

Keep in mind you need to have a `ref` to the graph element:
https://github.com/vasturiano/react-force-graph/blob/master/example/collision-detection/index.html#L49

**Comment by furiousOyster** [comment]
thanks !!
