### ISSUE TITLE
Node Position on Canvas does not reflect x,y coordinate of underlying data

### ISSUE THREAD

**Issue by abzgupta** [vasturiano/react-force-graph#99]
**Describe the bug**
Nodes on the canvas are not aligned to the proper X and Y position on the canvas. 

**To Reproduce**
```
import React, { Component } from "react";
import { ForceGraph2D } from "react-force-graph";
import * as d3 from "d3";
import { node } from "prop-types";

; 

const data = [
  { name: "a", age: 27 },
  { name: "a", age: 21 },
  { name: "a", age: 37 },
  { name: "b", age: 23 },
  { name: "b", age: 33 },
  { name: "c", age: 23 },
  { name: "d", age: 33 }
];

var foci_points = {
  'a': { x: 10, y: 10 },
  'b': { x: 10, y: 150 },
  'c': { x: 250, y: 250 },
  'd': { x: 350, y: 350 }
};

export default class Bubbles extends Component {
  componentDidMount() {
    
    
    this.fg.d3Force("center", null);
    this.fg.d3Force('charge').strength(0);
    this.fg.d3Force('x', d3.forceX().x(function(d){ 
      const foci_d = foci_points
      return foci_d[d.name].x
    }));
    this.fg.d3Force('y', d3.forceY().y(function(d){ 
      const foci_d = foci_points
      return foci_d[d.name].y
    }));

    this.fg.d3Force("collide", d3.forceCollide(5)); 
    
  }
  render() {
    return (
      <ForceGraph2D
        ref={el => (this.fg = el)}
        graphData={{ nodes:data, links: [] }} 
        foci_points={foci_points}
        cooldownTime={Infinity}
        d3AlphaDecay={0.0228}
        d3VelocityDecay={0.2}
        width={1500}
        height={1500}
        nodeColor={"red"}
        backgroundColor={"lightgray"} 
        enableZoomPanInteraction={false}
      />
    );
  }
}

```

**Expected behavior**
The layout is consistent with the foci dictionary in terms of relevant distance from each of the foci. However, I was expecting the nodes to be pushed further to the left because the x coordinates were set = 10.  

**Screenshots**
![Screen Shot 2019-06-24 at 2 05 37 PM](https://user-images.githubusercontent.com/11993996/60052402-fbc21f80-9689-11e9-9644-d829ad5a8695.png)

**Desktop (please complete the following information):**
 - OS: [macOS Mojave Version 10.14.4]
 - Browser [Chrome]

**Additional context**

From the screenshot, we can see there is a node on the bottom right corner of the canvas. That would me, intuitively , that the position is 1000,1000 however if you refer to the foci_dict in the code, it should be around 350,350. 
![Screen Shot 2019-06-24 at 2 19 51 PM](https://user-images.githubusercontent.com/11993996/60052853-2eb8e300-968b-11e9-947c-89cddf552220.png)

I have tried to use the centerAt property passing in 500, 500 (which corresponds to width/2, height/2) but that did not work.

**Comment by vasturiano** [comment]
@abzgupta thanks for reaching out. That is because there is a zoom engaged in the canvas. This is done automatically by default, but you can override it. Please look into the `zoom` method in the docs.

> Set the 2D canvas zoom amount. The zoom is defined in terms of the scale transform of each px. A value of 1 indicates unity, larger values zoom in and smaller values zoom out. An optional 2nd argument defines the duration of the transition (in ms) to animate the canvas motion. By default the zoom is set to a value inversely proportional to the amount of nodes in the system.

You can reset it simply by calling `myGraph.zoom(1)` after mount.

**Comment by abzgupta** [comment]
Thank you for the quick reply. I really appreciate it. I can see that the zoom was set to >2. 

I tried to pass in the value via props, I also changed it in the componentDidMount method, but that didn't fix the issue. 

```
import React, { Component } from "react";
import { ForceGraph2D } from "react-force-graph";
import * as d3 from "d3";
import { node } from "prop-types";

; 

const data = [
  { name: "a", age: 27 },
  { name: "a", age: 21 },
  { name: "a", age: 37 },
  { name: "b", age: 23 },
  { name: "b", age: 33 },
  { name: "c", age: 23 },
  { name: "d", age: 33 }
];

var foci_points = {
  'a': { x: 10, y: 10 },
  'b': { x: 10, y: 150 },
  'c': { x: 250, y: 250 },
  'd': { x: 350, y: 350 }
};

export default class Bubbles extends Component {
  componentDidMount() {
    this.fg.zoom(1); 
    console.log(this.fg.props)
    this.fg.d3Force("center", null);
    this.fg.d3Force('charge').strength(0);
    this.fg.d3Force('x', d3.forceX().x(function(d){ 
      const foci_d = foci_points
      return foci_d[d.name].x
    }));
    this.fg.d3Force('y', d3.forceY().y(function(d){ 
      const foci_d = foci_points
      return foci_d[d.name].y
    }));

    this.fg.d3Force("collide", d3.forceCollide(5)); 
    
  }
  
  render() {
    return (
      <ForceGraph2D
        ref={el => (this.fg = el)}
        graphData={{ nodes:data, links: [] }} 
        foci_points={foci_points}
        cooldownTime={Infinity}
        d3AlphaDecay={0.0228}
        d3VelocityDecay={0.2}
        width={1500}
        height={1500}
        nodeColor={"red"}
        backgroundColor={"lightgray"} 
        enableZoomPanInteraction={false}
        zoom={1}
      />
    );
  }
}

```

In the screenshot below, we can see that the props were passed in properly (i.e zoom was set to 1) . 
![Screen Shot 2019-06-25 at 12 00 36 AM](https://user-images.githubusercontent.com/11993996/60076467-7fa4f780-96dc-11e9-8fa4-58982d25f8a9.png)

Perhaps I am doing this incorrectly?

**Comment by vasturiano** [comment]
@abzgupta could you try setting the zoom level to any other value different from 1, like `.zoom(1 + 1e-9)`?
I suspect your zoom is not being used because it is exactly the same value as the initial (1).

**Comment by abzgupta** [comment]
So, setting the zoom at 1.0000001 just zoomed out the canvas, however the nodes were still being drawn in the center. For some reason, there was an offset of width/2 , height/2  when drawing the nodes. 

In the code below, I just adjusted the position of forceX and forceY using container dimensions passed in by the props. This gave me the desired result. 


```
import React, { Component } from "react";
import { ForceGraph2D } from "react-force-graph";
import * as d3 from "d3";
import { node } from "prop-types";

; 

const data = [
  { name: "a", age: 27 },
  { name: "a", age: 21 },
  { name: "a", age: 37 },
  { name: "b", age: 23 },
  { name: "b", age: 33 },
  { name: "c", age: 23 },
  { name: "d", age: 33 }
];

var foci_points = {
  'a': { x: 10, y: 10 },
  'b': { x: 10, y: 150 },
  'c': { x: 250, y: 250 },
  'd': { x: 350, y: 350 }
};

export default class Bubbles extends Component {
  componentDidMount() {
    this.fg.d3Force("center", null);
    this.fg.zoom(1.0000000001); 
    const fg_props = this.fg.props;
    
    this.fg.d3Force('charge').strength(0);
    this.fg.d3Force('x', d3.forceX().x(function(d){ 
      const foci_d = foci_points
      return  -fg_props.width/2 +  foci_d[d.name].x ;
    }));
    this.fg.d3Force('y', d3.forceY().y(function(d){ 
      const foci_d = foci_points
      return -fg_props.height/2 + foci_d[d.name].y
    }));

    this.fg.d3Force("collide", d3.forceCollide(5)); 
  }
  
  render() {
    return (
      <ForceGraph2D
        ref={el => (this.fg = el)}
        graphData={{ nodes:data, links: [] }} 
        foci_points={foci_points}
        cooldownTime={Infinity}
        d3AlphaDecay={0.0228}
        d3VelocityDecay={0.2}
        width={1500}
        height={1500}
        nodeColor={"red"}
        backgroundColor={"lightgray"} 
        enableZoomPanInteraction={false}
      />
    );
  }
}
```


![Screen Shot 2019-06-26 at 1 09 41 PM](https://user-images.githubusercontent.com/11993996/60211352-b03b7d00-9813-11e9-9cfe-718c9fb8a7d4.png)

As you can see from the screen shot above, the nodes are in the expected position. If this is the desired behavior (manually offsetting the position) , please feel free to close this. 

Once again, thanks for your continued support.

**Comment by vasturiano** [comment]
Yes, the `0,0` coordinates are the center of the canvas, not the top-left point.
If you wish to make it so, simply do `centerAt(-width/2, -height/2)`.

**Comment by abzgupta** [comment]
Perfect, I will remember that. Thank you!
